# Generated by rpcgen.py from nlm_prot.x on Wed Jun 24 11:38:48 2026
import nlm_prot_const as const
class nlm_holder:
    # XDR definition:
    # struct nlm_holder {
    #     bool exclusive;
    #     int svid;
    #     netobj oh;
    #     unsigned l_offset;
    #     unsigned l_len;
    # };
    def __init__(self, exclusive=None, svid=None, oh=None, l_offset=None, l_len=None):
        self.exclusive = exclusive
        self.svid = svid
        self.oh = oh
        self.l_offset = l_offset
        self.l_len = l_len

    def __repr__(self):
        out = []
        if self.exclusive is not None:
            out += ['exclusive=%s' % repr(self.exclusive)]
        if self.svid is not None:
            out += ['svid=%s' % repr(self.svid)]
        if self.oh is not None:
            out += ['oh=%s' % repr(self.oh)]
        if self.l_offset is not None:
            out += ['l_offset=%s' % repr(self.l_offset)]
        if self.l_len is not None:
            out += ['l_len=%s' % repr(self.l_len)]
        return 'nlm_holder(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm_testrply:
    # XDR definition:
    # union nlm_testrply switch(nlm_stats stat) {
    #     case nlm_denied:
    #         nlm_holder holder;
    #     default:
    #         void;
    # };
    def __init__(self, stat=None, holder=None):
        self.stat = stat
        self.holder = holder

    switch = property(lambda s: {const.nlm_denied:s.holder,}.get(s.stat, None))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.stat is not None:
            out += ['stat=%s' % const.nlm_stats.get(self.stat, self.stat)]
        if self.holder is not None:
            out += ['holder=%s' % repr(self.holder)]
        return 'nlm_testrply(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm_stat:
    # XDR definition:
    # struct nlm_stat {
    #     nlm_stats stat;
    # };
    def __init__(self, stat=None):
        self.stat = stat

    def __repr__(self):
        out = []
        if self.stat is not None:
            out += ['stat=%s' % const.nlm_stats.get(self.stat, self.stat)]
        return 'nlm_stat(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm_res:
    # XDR definition:
    # struct nlm_res {
    #     netobj cookie;
    #     nlm_stat stat;
    # };
    def __init__(self, cookie=None, stat=None):
        self.cookie = cookie
        self.stat = stat

    def __getattr__(self, attr):
        return getattr(self.stat, attr)

    def __repr__(self):
        out = []
        if self.cookie is not None:
            out += ['cookie=%s' % repr(self.cookie)]
        if self.stat is not None:
            out += ['stat=%s' % repr(self.stat)]
        return 'nlm_res(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm_testres:
    # XDR definition:
    # struct nlm_testres {
    #     netobj cookie;
    #     nlm_testrply stat;
    # };
    def __init__(self, cookie=None, stat=None):
        self.cookie = cookie
        self.stat = stat

    def __getattr__(self, attr):
        return getattr(self.stat, attr)

    def __repr__(self):
        out = []
        if self.cookie is not None:
            out += ['cookie=%s' % repr(self.cookie)]
        if self.stat is not None:
            out += ['stat=%s' % repr(self.stat)]
        return 'nlm_testres(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm_lock:
    # XDR definition:
    # struct nlm_lock {
    #     string caller_name<LM_MAXSTRLEN>;
    #     netobj fh;
    #     netobj oh;
    #     int svid;
    #     unsigned l_offset;
    #     unsigned l_len;
    # };
    def __init__(self, caller_name=None, fh=None, oh=None, svid=None, l_offset=None, l_len=None):
        self.caller_name = caller_name
        self.fh = fh
        self.oh = oh
        self.svid = svid
        self.l_offset = l_offset
        self.l_len = l_len

    def __repr__(self):
        out = []
        if self.caller_name is not None:
            out += ['caller_name=%s' % repr(self.caller_name)]
        if self.fh is not None:
            out += ['fh=%s' % repr(self.fh)]
        if self.oh is not None:
            out += ['oh=%s' % repr(self.oh)]
        if self.svid is not None:
            out += ['svid=%s' % repr(self.svid)]
        if self.l_offset is not None:
            out += ['l_offset=%s' % repr(self.l_offset)]
        if self.l_len is not None:
            out += ['l_len=%s' % repr(self.l_len)]
        return 'nlm_lock(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm_lockargs:
    # XDR definition:
    # struct nlm_lockargs {
    #     netobj cookie;
    #     bool block;
    #     bool exclusive;
    #     nlm_lock alock;
    #     bool reclaim;
    #     int state;
    # };
    def __init__(self, cookie=None, block=None, exclusive=None, alock=None, reclaim=None, state=None):
        self.cookie = cookie
        self.block = block
        self.exclusive = exclusive
        self.alock = alock
        self.reclaim = reclaim
        self.state = state

    def __getattr__(self, attr):
        return getattr(self.alock, attr)

    def __repr__(self):
        out = []
        if self.cookie is not None:
            out += ['cookie=%s' % repr(self.cookie)]
        if self.block is not None:
            out += ['block=%s' % repr(self.block)]
        if self.exclusive is not None:
            out += ['exclusive=%s' % repr(self.exclusive)]
        if self.alock is not None:
            out += ['alock=%s' % repr(self.alock)]
        if self.reclaim is not None:
            out += ['reclaim=%s' % repr(self.reclaim)]
        if self.state is not None:
            out += ['state=%s' % repr(self.state)]
        return 'nlm_lockargs(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm_cancargs:
    # XDR definition:
    # struct nlm_cancargs {
    #     netobj cookie;
    #     bool block;
    #     bool exclusive;
    #     nlm_lock alock;
    # };
    def __init__(self, cookie=None, block=None, exclusive=None, alock=None):
        self.cookie = cookie
        self.block = block
        self.exclusive = exclusive
        self.alock = alock

    def __getattr__(self, attr):
        return getattr(self.alock, attr)

    def __repr__(self):
        out = []
        if self.cookie is not None:
            out += ['cookie=%s' % repr(self.cookie)]
        if self.block is not None:
            out += ['block=%s' % repr(self.block)]
        if self.exclusive is not None:
            out += ['exclusive=%s' % repr(self.exclusive)]
        if self.alock is not None:
            out += ['alock=%s' % repr(self.alock)]
        return 'nlm_cancargs(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm_testargs:
    # XDR definition:
    # struct nlm_testargs {
    #     netobj cookie;
    #     bool exclusive;
    #     nlm_lock alock;
    # };
    def __init__(self, cookie=None, exclusive=None, alock=None):
        self.cookie = cookie
        self.exclusive = exclusive
        self.alock = alock

    def __getattr__(self, attr):
        return getattr(self.alock, attr)

    def __repr__(self):
        out = []
        if self.cookie is not None:
            out += ['cookie=%s' % repr(self.cookie)]
        if self.exclusive is not None:
            out += ['exclusive=%s' % repr(self.exclusive)]
        if self.alock is not None:
            out += ['alock=%s' % repr(self.alock)]
        return 'nlm_testargs(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm_unlockargs:
    # XDR definition:
    # struct nlm_unlockargs {
    #     netobj cookie;
    #     nlm_lock alock;
    # };
    def __init__(self, cookie=None, alock=None):
        self.cookie = cookie
        self.alock = alock

    def __getattr__(self, attr):
        return getattr(self.alock, attr)

    def __repr__(self):
        out = []
        if self.cookie is not None:
            out += ['cookie=%s' % repr(self.cookie)]
        if self.alock is not None:
            out += ['alock=%s' % repr(self.alock)]
        return 'nlm_unlockargs(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm_share:
    # XDR definition:
    # struct nlm_share {
    #     string caller_name<LM_MAXSTRLEN>;
    #     netobj fh;
    #     netobj oh;
    #     fsh_mode mode;
    #     fsh_access access;
    # };
    def __init__(self, caller_name=None, fh=None, oh=None, mode=None, access=None):
        self.caller_name = caller_name
        self.fh = fh
        self.oh = oh
        self.mode = mode
        self.access = access

    def __repr__(self):
        out = []
        if self.caller_name is not None:
            out += ['caller_name=%s' % repr(self.caller_name)]
        if self.fh is not None:
            out += ['fh=%s' % repr(self.fh)]
        if self.oh is not None:
            out += ['oh=%s' % repr(self.oh)]
        if self.mode is not None:
            out += ['mode=%s' % const.fsh_mode.get(self.mode, self.mode)]
        if self.access is not None:
            out += ['access=%s' % const.fsh_access.get(self.access, self.access)]
        return 'nlm_share(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm_shareargs:
    # XDR definition:
    # struct nlm_shareargs {
    #     netobj cookie;
    #     nlm_share share;
    #     bool reclaim;
    # };
    def __init__(self, cookie=None, share=None, reclaim=None):
        self.cookie = cookie
        self.share = share
        self.reclaim = reclaim

    def __getattr__(self, attr):
        return getattr(self.share, attr)

    def __repr__(self):
        out = []
        if self.cookie is not None:
            out += ['cookie=%s' % repr(self.cookie)]
        if self.share is not None:
            out += ['share=%s' % repr(self.share)]
        if self.reclaim is not None:
            out += ['reclaim=%s' % repr(self.reclaim)]
        return 'nlm_shareargs(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm_shareres:
    # XDR definition:
    # struct nlm_shareres {
    #     netobj cookie;
    #     nlm_stats stat;
    #     int sequence;
    # };
    def __init__(self, cookie=None, stat=None, sequence=None):
        self.cookie = cookie
        self.stat = stat
        self.sequence = sequence

    def __repr__(self):
        out = []
        if self.cookie is not None:
            out += ['cookie=%s' % repr(self.cookie)]
        if self.stat is not None:
            out += ['stat=%s' % const.nlm_stats.get(self.stat, self.stat)]
        if self.sequence is not None:
            out += ['sequence=%s' % repr(self.sequence)]
        return 'nlm_shareres(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm_notify:
    # XDR definition:
    # struct nlm_notify {
    #     string name<LM_MAXNAMELEN>;
    #     int state;
    # };
    def __init__(self, name=None, state=None):
        self.name = name
        self.state = state

    def __repr__(self):
        out = []
        if self.name is not None:
            out += ['name=%s' % repr(self.name)]
        if self.state is not None:
            out += ['state=%s' % repr(self.state)]
        return 'nlm_notify(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm4_holder:
    # XDR definition:
    # struct nlm4_holder {
    #     bool exclusive;
    #     int32 svid;
    #     netobj oh;
    #     uint64 l_offset;
    #     uint64 l_len;
    # };
    def __init__(self, exclusive=None, svid=None, oh=None, l_offset=None, l_len=None):
        self.exclusive = exclusive
        self.svid = svid
        self.oh = oh
        self.l_offset = l_offset
        self.l_len = l_len

    def __repr__(self):
        out = []
        if self.exclusive is not None:
            out += ['exclusive=%s' % repr(self.exclusive)]
        if self.svid is not None:
            out += ['svid=%s' % repr(self.svid)]
        if self.oh is not None:
            out += ['oh=%s' % repr(self.oh)]
        if self.l_offset is not None:
            out += ['l_offset=%s' % repr(self.l_offset)]
        if self.l_len is not None:
            out += ['l_len=%s' % repr(self.l_len)]
        return 'nlm4_holder(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm4_testrply:
    # XDR definition:
    # union nlm4_testrply switch(nlm4_stats stat) {
    #     case NLM4_DENIED:
    #         nlm4_holder holder;
    #     default:
    #         void;
    # };
    def __init__(self, stat=None, holder=None):
        self.stat = stat
        self.holder = holder

    switch = property(lambda s: {const.NLM4_DENIED:s.holder,}.get(s.stat, None))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.stat is not None:
            out += ['stat=%s' % const.nlm4_stats.get(self.stat, self.stat)]
        if self.holder is not None:
            out += ['holder=%s' % repr(self.holder)]
        return 'nlm4_testrply(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm4_stat:
    # XDR definition:
    # struct nlm4_stat {
    #     nlm4_stats stat;
    # };
    def __init__(self, stat=None):
        self.stat = stat

    def __repr__(self):
        out = []
        if self.stat is not None:
            out += ['stat=%s' % const.nlm4_stats.get(self.stat, self.stat)]
        return 'nlm4_stat(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm4_res:
    # XDR definition:
    # struct nlm4_res {
    #     netobj cookie;
    #     nlm4_stat stat;
    # };
    def __init__(self, cookie=None, stat=None):
        self.cookie = cookie
        self.stat = stat

    def __getattr__(self, attr):
        return getattr(self.stat, attr)

    def __repr__(self):
        out = []
        if self.cookie is not None:
            out += ['cookie=%s' % repr(self.cookie)]
        if self.stat is not None:
            out += ['stat=%s' % repr(self.stat)]
        return 'nlm4_res(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm4_testres:
    # XDR definition:
    # struct nlm4_testres {
    #     netobj cookie;
    #     nlm4_testrply stat;
    # };
    def __init__(self, cookie=None, stat=None):
        self.cookie = cookie
        self.stat = stat

    def __getattr__(self, attr):
        return getattr(self.stat, attr)

    def __repr__(self):
        out = []
        if self.cookie is not None:
            out += ['cookie=%s' % repr(self.cookie)]
        if self.stat is not None:
            out += ['stat=%s' % repr(self.stat)]
        return 'nlm4_testres(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm4_lock:
    # XDR definition:
    # struct nlm4_lock {
    #     string caller_name<LM_MAXSTRLEN>;
    #     netobj fh;
    #     netobj oh;
    #     int32 svid;
    #     uint64 l_offset;
    #     uint64 l_len;
    # };
    def __init__(self, caller_name=None, fh=None, oh=None, svid=None, l_offset=None, l_len=None):
        self.caller_name = caller_name
        self.fh = fh
        self.oh = oh
        self.svid = svid
        self.l_offset = l_offset
        self.l_len = l_len

    def __repr__(self):
        out = []
        if self.caller_name is not None:
            out += ['caller_name=%s' % repr(self.caller_name)]
        if self.fh is not None:
            out += ['fh=%s' % repr(self.fh)]
        if self.oh is not None:
            out += ['oh=%s' % repr(self.oh)]
        if self.svid is not None:
            out += ['svid=%s' % repr(self.svid)]
        if self.l_offset is not None:
            out += ['l_offset=%s' % repr(self.l_offset)]
        if self.l_len is not None:
            out += ['l_len=%s' % repr(self.l_len)]
        return 'nlm4_lock(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm4_lockargs:
    # XDR definition:
    # struct nlm4_lockargs {
    #     netobj cookie;
    #     bool block;
    #     bool exclusive;
    #     nlm4_lock alock;
    #     bool reclaim;
    #     int32 state;
    # };
    def __init__(self, cookie=None, block=None, exclusive=None, alock=None, reclaim=None, state=None):
        self.cookie = cookie
        self.block = block
        self.exclusive = exclusive
        self.alock = alock
        self.reclaim = reclaim
        self.state = state

    def __getattr__(self, attr):
        return getattr(self.alock, attr)

    def __repr__(self):
        out = []
        if self.cookie is not None:
            out += ['cookie=%s' % repr(self.cookie)]
        if self.block is not None:
            out += ['block=%s' % repr(self.block)]
        if self.exclusive is not None:
            out += ['exclusive=%s' % repr(self.exclusive)]
        if self.alock is not None:
            out += ['alock=%s' % repr(self.alock)]
        if self.reclaim is not None:
            out += ['reclaim=%s' % repr(self.reclaim)]
        if self.state is not None:
            out += ['state=%s' % repr(self.state)]
        return 'nlm4_lockargs(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm4_cancargs:
    # XDR definition:
    # struct nlm4_cancargs {
    #     netobj cookie;
    #     bool block;
    #     bool exclusive;
    #     nlm4_lock alock;
    # };
    def __init__(self, cookie=None, block=None, exclusive=None, alock=None):
        self.cookie = cookie
        self.block = block
        self.exclusive = exclusive
        self.alock = alock

    def __getattr__(self, attr):
        return getattr(self.alock, attr)

    def __repr__(self):
        out = []
        if self.cookie is not None:
            out += ['cookie=%s' % repr(self.cookie)]
        if self.block is not None:
            out += ['block=%s' % repr(self.block)]
        if self.exclusive is not None:
            out += ['exclusive=%s' % repr(self.exclusive)]
        if self.alock is not None:
            out += ['alock=%s' % repr(self.alock)]
        return 'nlm4_cancargs(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm4_testargs:
    # XDR definition:
    # struct nlm4_testargs {
    #     netobj cookie;
    #     bool exclusive;
    #     nlm4_lock alock;
    # };
    def __init__(self, cookie=None, exclusive=None, alock=None):
        self.cookie = cookie
        self.exclusive = exclusive
        self.alock = alock

    def __getattr__(self, attr):
        return getattr(self.alock, attr)

    def __repr__(self):
        out = []
        if self.cookie is not None:
            out += ['cookie=%s' % repr(self.cookie)]
        if self.exclusive is not None:
            out += ['exclusive=%s' % repr(self.exclusive)]
        if self.alock is not None:
            out += ['alock=%s' % repr(self.alock)]
        return 'nlm4_testargs(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm4_unlockargs:
    # XDR definition:
    # struct nlm4_unlockargs {
    #     netobj cookie;
    #     nlm4_lock alock;
    # };
    def __init__(self, cookie=None, alock=None):
        self.cookie = cookie
        self.alock = alock

    def __getattr__(self, attr):
        return getattr(self.alock, attr)

    def __repr__(self):
        out = []
        if self.cookie is not None:
            out += ['cookie=%s' % repr(self.cookie)]
        if self.alock is not None:
            out += ['alock=%s' % repr(self.alock)]
        return 'nlm4_unlockargs(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm4_share:
    # XDR definition:
    # struct nlm4_share {
    #     string caller_name<LM_MAXSTRLEN>;
    #     netobj fh;
    #     netobj oh;
    #     fsh4_mode mode;
    #     fsh4_access access;
    # };
    def __init__(self, caller_name=None, fh=None, oh=None, mode=None, access=None):
        self.caller_name = caller_name
        self.fh = fh
        self.oh = oh
        self.mode = mode
        self.access = access

    def __repr__(self):
        out = []
        if self.caller_name is not None:
            out += ['caller_name=%s' % repr(self.caller_name)]
        if self.fh is not None:
            out += ['fh=%s' % repr(self.fh)]
        if self.oh is not None:
            out += ['oh=%s' % repr(self.oh)]
        if self.mode is not None:
            out += ['mode=%s' % const.fsh4_mode.get(self.mode, self.mode)]
        if self.access is not None:
            out += ['access=%s' % const.fsh4_access.get(self.access, self.access)]
        return 'nlm4_share(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm4_shareargs:
    # XDR definition:
    # struct nlm4_shareargs {
    #     netobj cookie;
    #     nlm4_share share;
    #     bool reclaim;
    # };
    def __init__(self, cookie=None, share=None, reclaim=None):
        self.cookie = cookie
        self.share = share
        self.reclaim = reclaim

    def __getattr__(self, attr):
        return getattr(self.share, attr)

    def __repr__(self):
        out = []
        if self.cookie is not None:
            out += ['cookie=%s' % repr(self.cookie)]
        if self.share is not None:
            out += ['share=%s' % repr(self.share)]
        if self.reclaim is not None:
            out += ['reclaim=%s' % repr(self.reclaim)]
        return 'nlm4_shareargs(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm4_shareres:
    # XDR definition:
    # struct nlm4_shareres {
    #     netobj cookie;
    #     nlm4_stats stat;
    #     int32 sequence;
    # };
    def __init__(self, cookie=None, stat=None, sequence=None):
        self.cookie = cookie
        self.stat = stat
        self.sequence = sequence

    def __repr__(self):
        out = []
        if self.cookie is not None:
            out += ['cookie=%s' % repr(self.cookie)]
        if self.stat is not None:
            out += ['stat=%s' % const.nlm4_stats.get(self.stat, self.stat)]
        if self.sequence is not None:
            out += ['sequence=%s' % repr(self.sequence)]
        return 'nlm4_shareres(%s)' % ', '.join(out)
    __str__ = __repr__

class nlm4_notify:
    # XDR definition:
    # struct nlm4_notify {
    #     string name<LM_MAXNAMELEN>;
    #     int32 state;
    # };
    def __init__(self, name=None, state=None):
        self.name = name
        self.state = state

    def __repr__(self):
        out = []
        if self.name is not None:
            out += ['name=%s' % repr(self.name)]
        if self.state is not None:
            out += ['state=%s' % repr(self.state)]
        return 'nlm4_notify(%s)' % ', '.join(out)
    __str__ = __repr__

