# Generated by rpcgen.py from nlm_prot.x on Wed Jun 24 11:38:48 2026
import nlm_prot_const as const
import nlm_prot_type as types
import xdrlib
from xdrlib import Error as XDRError

class nullclass(object):
    pass

def _str2bytes(data):
    # Python 3: xdrlib requires bytes for opaque/string fields.  Python 2 str
    # values were raw bytes, so latin-1 reproduces those byte values exactly
    # (and is identical to ASCII/utf-8 for plain text).
    if isinstance(data, str):
        return data.encode('latin-1')
    return data

class NLM_PROTPacker(xdrlib.Packer):
    def __init__(self, check_enum=True, check_array=True):
        xdrlib.Packer.__init__(self)
        self.check_enum = check_enum
        self.check_array = check_array

    pack_int = xdrlib.Packer.pack_int
    pack_long = xdrlib.Packer.pack_int
    pack_uint = xdrlib.Packer.pack_uint
    pack_unsigned = xdrlib.Packer.pack_uint
    pack_hyper = xdrlib.Packer.pack_hyper
    pack_uhyper = xdrlib.Packer.pack_uhyper
    pack_float = xdrlib.Packer.pack_float
    pack_double = xdrlib.Packer.pack_double
    pack_quadruple = xdrlib.Packer.pack_double
    pack_bool = xdrlib.Packer.pack_bool
    def pack_opaque(self, data):
        return xdrlib.Packer.pack_opaque(self, _str2bytes(data))
    def pack_string(self, data):
        return xdrlib.Packer.pack_string(self, _str2bytes(data))
    def pack_fopaque(self, n, data):
        return xdrlib.Packer.pack_fopaque(self, n, _str2bytes(data))
    def pack_fstring(self, n, data):
        return xdrlib.Packer.pack_fstring(self, n, _str2bytes(data))
    pack_int32 = pack_int

    pack_uint64 = pack_uhyper

    def pack_netobj(self, data):
        if hasattr(self, 'filter_netobj'):
            data = getattr(self, 'filter_netobj')(data)
        if len(data) > const.MAXNETOBJ_SZ and self.check_array:
            raise XDRError('array length too long for data')
        self.pack_opaque(data)

    def pack_nlm_stats(self, data):
        if hasattr(self, 'filter_nlm_stats'):
            data = getattr(self, 'filter_nlm_stats')(data)
        if self.check_enum and data not in [const.nlm_granted, const.nlm_denied, const.nlm_denied_nolocks, const.nlm_blocked, const.nlm_denied_grace_period, const.nlm_deadlck]:
            raise XDRError('value=%s not in enum nlm_stats' % data)
        self.pack_int(data)

    def pack_nlm_holder(self, data):
        if hasattr(self, 'filter_nlm_holder'):
            data = getattr(self, 'filter_nlm_holder')(data)
        if data.exclusive is None:
            raise TypeError('data.exclusive == None')
        self.pack_bool(data.exclusive)
        if data.svid is None:
            raise TypeError('data.svid == None')
        self.pack_int(data.svid)
        if data.oh is None:
            raise TypeError('data.oh == None')
        self.pack_netobj(data.oh)
        if data.l_offset is None:
            raise TypeError('data.l_offset == None')
        self.pack_unsigned(data.l_offset)
        if data.l_len is None:
            raise TypeError('data.l_len == None')
        self.pack_unsigned(data.l_len)

    def pack_nlm_testrply(self, data):
        if hasattr(self, 'filter_nlm_testrply'):
            data = getattr(self, 'filter_nlm_testrply')(data)
        if data.stat is None:
            raise TypeError('data.stat == None')
        self.pack_nlm_stats(data.stat)
        if data.stat == const.nlm_denied:
            if data.holder is None:
                raise TypeError('data.holder == None')
            self.pack_nlm_holder(data.holder)
        else:
            pass

    def pack_nlm_stat(self, data):
        if hasattr(self, 'filter_nlm_stat'):
            data = getattr(self, 'filter_nlm_stat')(data)
        if data.stat is None:
            raise TypeError('data.stat == None')
        self.pack_nlm_stats(data.stat)

    def pack_nlm_res(self, data):
        if hasattr(self, 'filter_nlm_res'):
            data = getattr(self, 'filter_nlm_res')(data)
        if data.cookie is None:
            raise TypeError('data.cookie == None')
        self.pack_netobj(data.cookie)
        if data.stat is None:
            raise TypeError('data.stat == None')
        self.pack_nlm_stat(data.stat)

    def pack_nlm_testres(self, data):
        if hasattr(self, 'filter_nlm_testres'):
            data = getattr(self, 'filter_nlm_testres')(data)
        if data.cookie is None:
            raise TypeError('data.cookie == None')
        self.pack_netobj(data.cookie)
        if data.stat is None:
            raise TypeError('data.stat == None')
        self.pack_nlm_testrply(data.stat)

    def pack_nlm_lock(self, data):
        if hasattr(self, 'filter_nlm_lock'):
            data = getattr(self, 'filter_nlm_lock')(data)
        if data.caller_name is None:
            raise TypeError('data.caller_name == None')
        if len(data.caller_name) > const.LM_MAXSTRLEN and self.check_array:
            raise XDRError('array length too long for data.caller_name')
        self.pack_string(data.caller_name)
        if data.fh is None:
            raise TypeError('data.fh == None')
        self.pack_netobj(data.fh)
        if data.oh is None:
            raise TypeError('data.oh == None')
        self.pack_netobj(data.oh)
        if data.svid is None:
            raise TypeError('data.svid == None')
        self.pack_int(data.svid)
        if data.l_offset is None:
            raise TypeError('data.l_offset == None')
        self.pack_unsigned(data.l_offset)
        if data.l_len is None:
            raise TypeError('data.l_len == None')
        self.pack_unsigned(data.l_len)

    def pack_nlm_lockargs(self, data):
        if hasattr(self, 'filter_nlm_lockargs'):
            data = getattr(self, 'filter_nlm_lockargs')(data)
        if data.cookie is None:
            raise TypeError('data.cookie == None')
        self.pack_netobj(data.cookie)
        if data.block is None:
            raise TypeError('data.block == None')
        self.pack_bool(data.block)
        if data.exclusive is None:
            raise TypeError('data.exclusive == None')
        self.pack_bool(data.exclusive)
        if data.alock is None:
            raise TypeError('data.alock == None')
        self.pack_nlm_lock(data.alock)
        if data.reclaim is None:
            raise TypeError('data.reclaim == None')
        self.pack_bool(data.reclaim)
        if data.state is None:
            raise TypeError('data.state == None')
        self.pack_int(data.state)

    def pack_nlm_cancargs(self, data):
        if hasattr(self, 'filter_nlm_cancargs'):
            data = getattr(self, 'filter_nlm_cancargs')(data)
        if data.cookie is None:
            raise TypeError('data.cookie == None')
        self.pack_netobj(data.cookie)
        if data.block is None:
            raise TypeError('data.block == None')
        self.pack_bool(data.block)
        if data.exclusive is None:
            raise TypeError('data.exclusive == None')
        self.pack_bool(data.exclusive)
        if data.alock is None:
            raise TypeError('data.alock == None')
        self.pack_nlm_lock(data.alock)

    def pack_nlm_testargs(self, data):
        if hasattr(self, 'filter_nlm_testargs'):
            data = getattr(self, 'filter_nlm_testargs')(data)
        if data.cookie is None:
            raise TypeError('data.cookie == None')
        self.pack_netobj(data.cookie)
        if data.exclusive is None:
            raise TypeError('data.exclusive == None')
        self.pack_bool(data.exclusive)
        if data.alock is None:
            raise TypeError('data.alock == None')
        self.pack_nlm_lock(data.alock)

    def pack_nlm_unlockargs(self, data):
        if hasattr(self, 'filter_nlm_unlockargs'):
            data = getattr(self, 'filter_nlm_unlockargs')(data)
        if data.cookie is None:
            raise TypeError('data.cookie == None')
        self.pack_netobj(data.cookie)
        if data.alock is None:
            raise TypeError('data.alock == None')
        self.pack_nlm_lock(data.alock)

    def pack_fsh_mode(self, data):
        if hasattr(self, 'filter_fsh_mode'):
            data = getattr(self, 'filter_fsh_mode')(data)
        if self.check_enum and data not in [const.fsm_DN, const.fsm_DR, const.fsm_DW, const.fsm_DRW]:
            raise XDRError('value=%s not in enum fsh_mode' % data)
        self.pack_int(data)

    def pack_fsh_access(self, data):
        if hasattr(self, 'filter_fsh_access'):
            data = getattr(self, 'filter_fsh_access')(data)
        if self.check_enum and data not in [const.fsa_NONE, const.fsa_R, const.fsa_W, const.fsa_RW]:
            raise XDRError('value=%s not in enum fsh_access' % data)
        self.pack_int(data)

    def pack_nlm_share(self, data):
        if hasattr(self, 'filter_nlm_share'):
            data = getattr(self, 'filter_nlm_share')(data)
        if data.caller_name is None:
            raise TypeError('data.caller_name == None')
        if len(data.caller_name) > const.LM_MAXSTRLEN and self.check_array:
            raise XDRError('array length too long for data.caller_name')
        self.pack_string(data.caller_name)
        if data.fh is None:
            raise TypeError('data.fh == None')
        self.pack_netobj(data.fh)
        if data.oh is None:
            raise TypeError('data.oh == None')
        self.pack_netobj(data.oh)
        if data.mode is None:
            raise TypeError('data.mode == None')
        self.pack_fsh_mode(data.mode)
        if data.access is None:
            raise TypeError('data.access == None')
        self.pack_fsh_access(data.access)

    def pack_nlm_shareargs(self, data):
        if hasattr(self, 'filter_nlm_shareargs'):
            data = getattr(self, 'filter_nlm_shareargs')(data)
        if data.cookie is None:
            raise TypeError('data.cookie == None')
        self.pack_netobj(data.cookie)
        if data.share is None:
            raise TypeError('data.share == None')
        self.pack_nlm_share(data.share)
        if data.reclaim is None:
            raise TypeError('data.reclaim == None')
        self.pack_bool(data.reclaim)

    def pack_nlm_shareres(self, data):
        if hasattr(self, 'filter_nlm_shareres'):
            data = getattr(self, 'filter_nlm_shareres')(data)
        if data.cookie is None:
            raise TypeError('data.cookie == None')
        self.pack_netobj(data.cookie)
        if data.stat is None:
            raise TypeError('data.stat == None')
        self.pack_nlm_stats(data.stat)
        if data.sequence is None:
            raise TypeError('data.sequence == None')
        self.pack_int(data.sequence)

    def pack_nlm_notify(self, data):
        if hasattr(self, 'filter_nlm_notify'):
            data = getattr(self, 'filter_nlm_notify')(data)
        if data.name is None:
            raise TypeError('data.name == None')
        if len(data.name) > const.LM_MAXNAMELEN and self.check_array:
            raise XDRError('array length too long for data.name')
        self.pack_string(data.name)
        if data.state is None:
            raise TypeError('data.state == None')
        self.pack_int(data.state)

    def pack_nlm4_stats(self, data):
        if hasattr(self, 'filter_nlm4_stats'):
            data = getattr(self, 'filter_nlm4_stats')(data)
        if self.check_enum and data not in [const.NLM4_GRANTED, const.NLM4_DENIED, const.NLM4_DENIED_NOLOCKS, const.NLM4_BLOCKED, const.NLM4_DENIED_GRACE_PERIOD, const.NLM4_DEADLCK, const.NLM4_ROFS, const.NLM4_STALE_FH, const.NLM4_FBIG, const.NLM4_FAILED]:
            raise XDRError('value=%s not in enum nlm4_stats' % data)
        self.pack_int(data)

    def pack_nlm4_holder(self, data):
        if hasattr(self, 'filter_nlm4_holder'):
            data = getattr(self, 'filter_nlm4_holder')(data)
        if data.exclusive is None:
            raise TypeError('data.exclusive == None')
        self.pack_bool(data.exclusive)
        if data.svid is None:
            raise TypeError('data.svid == None')
        self.pack_int32(data.svid)
        if data.oh is None:
            raise TypeError('data.oh == None')
        self.pack_netobj(data.oh)
        if data.l_offset is None:
            raise TypeError('data.l_offset == None')
        self.pack_uint64(data.l_offset)
        if data.l_len is None:
            raise TypeError('data.l_len == None')
        self.pack_uint64(data.l_len)

    def pack_nlm4_testrply(self, data):
        if hasattr(self, 'filter_nlm4_testrply'):
            data = getattr(self, 'filter_nlm4_testrply')(data)
        if data.stat is None:
            raise TypeError('data.stat == None')
        self.pack_nlm4_stats(data.stat)
        if data.stat == const.NLM4_DENIED:
            if data.holder is None:
                raise TypeError('data.holder == None')
            self.pack_nlm4_holder(data.holder)
        else:
            pass

    def pack_nlm4_stat(self, data):
        if hasattr(self, 'filter_nlm4_stat'):
            data = getattr(self, 'filter_nlm4_stat')(data)
        if data.stat is None:
            raise TypeError('data.stat == None')
        self.pack_nlm4_stats(data.stat)

    def pack_nlm4_res(self, data):
        if hasattr(self, 'filter_nlm4_res'):
            data = getattr(self, 'filter_nlm4_res')(data)
        if data.cookie is None:
            raise TypeError('data.cookie == None')
        self.pack_netobj(data.cookie)
        if data.stat is None:
            raise TypeError('data.stat == None')
        self.pack_nlm4_stat(data.stat)

    def pack_nlm4_testres(self, data):
        if hasattr(self, 'filter_nlm4_testres'):
            data = getattr(self, 'filter_nlm4_testres')(data)
        if data.cookie is None:
            raise TypeError('data.cookie == None')
        self.pack_netobj(data.cookie)
        if data.stat is None:
            raise TypeError('data.stat == None')
        self.pack_nlm4_testrply(data.stat)

    def pack_nlm4_lock(self, data):
        if hasattr(self, 'filter_nlm4_lock'):
            data = getattr(self, 'filter_nlm4_lock')(data)
        if data.caller_name is None:
            raise TypeError('data.caller_name == None')
        if len(data.caller_name) > const.LM_MAXSTRLEN and self.check_array:
            raise XDRError('array length too long for data.caller_name')
        self.pack_string(data.caller_name)
        if data.fh is None:
            raise TypeError('data.fh == None')
        self.pack_netobj(data.fh)
        if data.oh is None:
            raise TypeError('data.oh == None')
        self.pack_netobj(data.oh)
        if data.svid is None:
            raise TypeError('data.svid == None')
        self.pack_int32(data.svid)
        if data.l_offset is None:
            raise TypeError('data.l_offset == None')
        self.pack_uint64(data.l_offset)
        if data.l_len is None:
            raise TypeError('data.l_len == None')
        self.pack_uint64(data.l_len)

    def pack_nlm4_lockargs(self, data):
        if hasattr(self, 'filter_nlm4_lockargs'):
            data = getattr(self, 'filter_nlm4_lockargs')(data)
        if data.cookie is None:
            raise TypeError('data.cookie == None')
        self.pack_netobj(data.cookie)
        if data.block is None:
            raise TypeError('data.block == None')
        self.pack_bool(data.block)
        if data.exclusive is None:
            raise TypeError('data.exclusive == None')
        self.pack_bool(data.exclusive)
        if data.alock is None:
            raise TypeError('data.alock == None')
        self.pack_nlm4_lock(data.alock)
        if data.reclaim is None:
            raise TypeError('data.reclaim == None')
        self.pack_bool(data.reclaim)
        if data.state is None:
            raise TypeError('data.state == None')
        self.pack_int32(data.state)

    def pack_nlm4_cancargs(self, data):
        if hasattr(self, 'filter_nlm4_cancargs'):
            data = getattr(self, 'filter_nlm4_cancargs')(data)
        if data.cookie is None:
            raise TypeError('data.cookie == None')
        self.pack_netobj(data.cookie)
        if data.block is None:
            raise TypeError('data.block == None')
        self.pack_bool(data.block)
        if data.exclusive is None:
            raise TypeError('data.exclusive == None')
        self.pack_bool(data.exclusive)
        if data.alock is None:
            raise TypeError('data.alock == None')
        self.pack_nlm4_lock(data.alock)

    def pack_nlm4_testargs(self, data):
        if hasattr(self, 'filter_nlm4_testargs'):
            data = getattr(self, 'filter_nlm4_testargs')(data)
        if data.cookie is None:
            raise TypeError('data.cookie == None')
        self.pack_netobj(data.cookie)
        if data.exclusive is None:
            raise TypeError('data.exclusive == None')
        self.pack_bool(data.exclusive)
        if data.alock is None:
            raise TypeError('data.alock == None')
        self.pack_nlm4_lock(data.alock)

    def pack_nlm4_unlockargs(self, data):
        if hasattr(self, 'filter_nlm4_unlockargs'):
            data = getattr(self, 'filter_nlm4_unlockargs')(data)
        if data.cookie is None:
            raise TypeError('data.cookie == None')
        self.pack_netobj(data.cookie)
        if data.alock is None:
            raise TypeError('data.alock == None')
        self.pack_nlm4_lock(data.alock)

    def pack_fsh4_mode(self, data):
        if hasattr(self, 'filter_fsh4_mode'):
            data = getattr(self, 'filter_fsh4_mode')(data)
        if self.check_enum and data not in [const.FSM_DN, const.FSM_DR, const.FSM_DW, const.FSM_DRW]:
            raise XDRError('value=%s not in enum fsh4_mode' % data)
        self.pack_int(data)

    def pack_fsh4_access(self, data):
        if hasattr(self, 'filter_fsh4_access'):
            data = getattr(self, 'filter_fsh4_access')(data)
        if self.check_enum and data not in [const.FSA_NONE, const.FSA_R, const.FSA_W, const.FSA_RW]:
            raise XDRError('value=%s not in enum fsh4_access' % data)
        self.pack_int(data)

    def pack_nlm4_share(self, data):
        if hasattr(self, 'filter_nlm4_share'):
            data = getattr(self, 'filter_nlm4_share')(data)
        if data.caller_name is None:
            raise TypeError('data.caller_name == None')
        if len(data.caller_name) > const.LM_MAXSTRLEN and self.check_array:
            raise XDRError('array length too long for data.caller_name')
        self.pack_string(data.caller_name)
        if data.fh is None:
            raise TypeError('data.fh == None')
        self.pack_netobj(data.fh)
        if data.oh is None:
            raise TypeError('data.oh == None')
        self.pack_netobj(data.oh)
        if data.mode is None:
            raise TypeError('data.mode == None')
        self.pack_fsh4_mode(data.mode)
        if data.access is None:
            raise TypeError('data.access == None')
        self.pack_fsh4_access(data.access)

    def pack_nlm4_shareargs(self, data):
        if hasattr(self, 'filter_nlm4_shareargs'):
            data = getattr(self, 'filter_nlm4_shareargs')(data)
        if data.cookie is None:
            raise TypeError('data.cookie == None')
        self.pack_netobj(data.cookie)
        if data.share is None:
            raise TypeError('data.share == None')
        self.pack_nlm4_share(data.share)
        if data.reclaim is None:
            raise TypeError('data.reclaim == None')
        self.pack_bool(data.reclaim)

    def pack_nlm4_shareres(self, data):
        if hasattr(self, 'filter_nlm4_shareres'):
            data = getattr(self, 'filter_nlm4_shareres')(data)
        if data.cookie is None:
            raise TypeError('data.cookie == None')
        self.pack_netobj(data.cookie)
        if data.stat is None:
            raise TypeError('data.stat == None')
        self.pack_nlm4_stats(data.stat)
        if data.sequence is None:
            raise TypeError('data.sequence == None')
        self.pack_int32(data.sequence)

    def pack_nlm4_notify(self, data):
        if hasattr(self, 'filter_nlm4_notify'):
            data = getattr(self, 'filter_nlm4_notify')(data)
        if data.name is None:
            raise TypeError('data.name == None')
        if len(data.name) > const.LM_MAXNAMELEN and self.check_array:
            raise XDRError('array length too long for data.name')
        self.pack_string(data.name)
        if data.state is None:
            raise TypeError('data.state == None')
        self.pack_int32(data.state)

class NLM_PROTUnpacker(xdrlib.Unpacker):
    def __init__(self, data, check_enum=True, check_array=True):
        xdrlib.Unpacker.__init__(self, data)
        self.check_enum = check_enum
        self.check_array = check_array

    unpack_int = xdrlib.Unpacker.unpack_int
    unpack_long = xdrlib.Unpacker.unpack_int
    unpack_uint = xdrlib.Unpacker.unpack_uint
    unpack_unsigned = xdrlib.Unpacker.unpack_uint
    unpack_hyper = xdrlib.Unpacker.unpack_hyper
    unpack_uhyper = xdrlib.Unpacker.unpack_uhyper
    unpack_float = xdrlib.Unpacker.unpack_float
    unpack_double = xdrlib.Unpacker.unpack_double
    unpack_quadruple = xdrlib.Unpacker.unpack_double
    unpack_bool = xdrlib.Unpacker.unpack_bool
    unpack_opaque = xdrlib.Unpacker.unpack_opaque
    unpack_string = xdrlib.Unpacker.unpack_string
    unpack_int32 = unpack_int

    unpack_uint64 = unpack_uhyper

    def unpack_netobj(self):
        data = self.unpack_opaque()
        if len(data) > const.MAXNETOBJ_SZ and self.check_array:
            raise XDRError('array length too long for data')
        if hasattr(self, 'filter_netobj'):
            data = getattr(self, 'filter_netobj')(data)
        return data

    def unpack_nlm_stats(self):
        data = self.unpack_int()
        if self.check_enum and data not in [const.nlm_granted, const.nlm_denied, const.nlm_denied_nolocks, const.nlm_blocked, const.nlm_denied_grace_period, const.nlm_deadlck]:
            raise XDRError('value=%s not in enum nlm_stats' % data)
        if hasattr(self, 'filter_nlm_stats'):
            data = getattr(self, 'filter_nlm_stats')(data)
        return data

    def unpack_nlm_holder(self):
        data = types.nlm_holder()
        data.exclusive = self.unpack_bool()
        data.svid = self.unpack_int()
        data.oh = self.unpack_netobj()
        data.l_offset = self.unpack_unsigned()
        data.l_len = self.unpack_unsigned()
        if hasattr(self, 'filter_nlm_holder'):
            data = getattr(self, 'filter_nlm_holder')(data)
        return data

    def unpack_nlm_testrply(self):
        data = types.nlm_testrply()
        data.stat = self.unpack_nlm_stats()
        if data.stat == const.nlm_denied:
            data.holder = self.unpack_nlm_holder()
        else:
            pass
        if hasattr(self, 'filter_nlm_testrply'):
            data = getattr(self, 'filter_nlm_testrply')(data)
        return data

    def unpack_nlm_stat(self):
        data = types.nlm_stat()
        data.stat = self.unpack_nlm_stats()
        if hasattr(self, 'filter_nlm_stat'):
            data = getattr(self, 'filter_nlm_stat')(data)
        return data

    def unpack_nlm_res(self):
        data = types.nlm_res()
        data.cookie = self.unpack_netobj()
        data.stat = self.unpack_nlm_stat()
        if hasattr(self, 'filter_nlm_res'):
            data = getattr(self, 'filter_nlm_res')(data)
        return data

    def unpack_nlm_testres(self):
        data = types.nlm_testres()
        data.cookie = self.unpack_netobj()
        data.stat = self.unpack_nlm_testrply()
        if hasattr(self, 'filter_nlm_testres'):
            data = getattr(self, 'filter_nlm_testres')(data)
        return data

    def unpack_nlm_lock(self):
        data = types.nlm_lock()
        data.caller_name = self.unpack_string()
        if len(data.caller_name) > const.LM_MAXSTRLEN and self.check_array:
            raise XDRError('array length too long for data.caller_name')
        data.fh = self.unpack_netobj()
        data.oh = self.unpack_netobj()
        data.svid = self.unpack_int()
        data.l_offset = self.unpack_unsigned()
        data.l_len = self.unpack_unsigned()
        if hasattr(self, 'filter_nlm_lock'):
            data = getattr(self, 'filter_nlm_lock')(data)
        return data

    def unpack_nlm_lockargs(self):
        data = types.nlm_lockargs()
        data.cookie = self.unpack_netobj()
        data.block = self.unpack_bool()
        data.exclusive = self.unpack_bool()
        data.alock = self.unpack_nlm_lock()
        data.reclaim = self.unpack_bool()
        data.state = self.unpack_int()
        if hasattr(self, 'filter_nlm_lockargs'):
            data = getattr(self, 'filter_nlm_lockargs')(data)
        return data

    def unpack_nlm_cancargs(self):
        data = types.nlm_cancargs()
        data.cookie = self.unpack_netobj()
        data.block = self.unpack_bool()
        data.exclusive = self.unpack_bool()
        data.alock = self.unpack_nlm_lock()
        if hasattr(self, 'filter_nlm_cancargs'):
            data = getattr(self, 'filter_nlm_cancargs')(data)
        return data

    def unpack_nlm_testargs(self):
        data = types.nlm_testargs()
        data.cookie = self.unpack_netobj()
        data.exclusive = self.unpack_bool()
        data.alock = self.unpack_nlm_lock()
        if hasattr(self, 'filter_nlm_testargs'):
            data = getattr(self, 'filter_nlm_testargs')(data)
        return data

    def unpack_nlm_unlockargs(self):
        data = types.nlm_unlockargs()
        data.cookie = self.unpack_netobj()
        data.alock = self.unpack_nlm_lock()
        if hasattr(self, 'filter_nlm_unlockargs'):
            data = getattr(self, 'filter_nlm_unlockargs')(data)
        return data

    def unpack_fsh_mode(self):
        data = self.unpack_int()
        if self.check_enum and data not in [const.fsm_DN, const.fsm_DR, const.fsm_DW, const.fsm_DRW]:
            raise XDRError('value=%s not in enum fsh_mode' % data)
        if hasattr(self, 'filter_fsh_mode'):
            data = getattr(self, 'filter_fsh_mode')(data)
        return data

    def unpack_fsh_access(self):
        data = self.unpack_int()
        if self.check_enum and data not in [const.fsa_NONE, const.fsa_R, const.fsa_W, const.fsa_RW]:
            raise XDRError('value=%s not in enum fsh_access' % data)
        if hasattr(self, 'filter_fsh_access'):
            data = getattr(self, 'filter_fsh_access')(data)
        return data

    def unpack_nlm_share(self):
        data = types.nlm_share()
        data.caller_name = self.unpack_string()
        if len(data.caller_name) > const.LM_MAXSTRLEN and self.check_array:
            raise XDRError('array length too long for data.caller_name')
        data.fh = self.unpack_netobj()
        data.oh = self.unpack_netobj()
        data.mode = self.unpack_fsh_mode()
        data.access = self.unpack_fsh_access()
        if hasattr(self, 'filter_nlm_share'):
            data = getattr(self, 'filter_nlm_share')(data)
        return data

    def unpack_nlm_shareargs(self):
        data = types.nlm_shareargs()
        data.cookie = self.unpack_netobj()
        data.share = self.unpack_nlm_share()
        data.reclaim = self.unpack_bool()
        if hasattr(self, 'filter_nlm_shareargs'):
            data = getattr(self, 'filter_nlm_shareargs')(data)
        return data

    def unpack_nlm_shareres(self):
        data = types.nlm_shareres()
        data.cookie = self.unpack_netobj()
        data.stat = self.unpack_nlm_stats()
        data.sequence = self.unpack_int()
        if hasattr(self, 'filter_nlm_shareres'):
            data = getattr(self, 'filter_nlm_shareres')(data)
        return data

    def unpack_nlm_notify(self):
        data = types.nlm_notify()
        data.name = self.unpack_string()
        if len(data.name) > const.LM_MAXNAMELEN and self.check_array:
            raise XDRError('array length too long for data.name')
        data.state = self.unpack_int()
        if hasattr(self, 'filter_nlm_notify'):
            data = getattr(self, 'filter_nlm_notify')(data)
        return data

    def unpack_nlm4_stats(self):
        data = self.unpack_int()
        if self.check_enum and data not in [const.NLM4_GRANTED, const.NLM4_DENIED, const.NLM4_DENIED_NOLOCKS, const.NLM4_BLOCKED, const.NLM4_DENIED_GRACE_PERIOD, const.NLM4_DEADLCK, const.NLM4_ROFS, const.NLM4_STALE_FH, const.NLM4_FBIG, const.NLM4_FAILED]:
            raise XDRError('value=%s not in enum nlm4_stats' % data)
        if hasattr(self, 'filter_nlm4_stats'):
            data = getattr(self, 'filter_nlm4_stats')(data)
        return data

    def unpack_nlm4_holder(self):
        data = types.nlm4_holder()
        data.exclusive = self.unpack_bool()
        data.svid = self.unpack_int32()
        data.oh = self.unpack_netobj()
        data.l_offset = self.unpack_uint64()
        data.l_len = self.unpack_uint64()
        if hasattr(self, 'filter_nlm4_holder'):
            data = getattr(self, 'filter_nlm4_holder')(data)
        return data

    def unpack_nlm4_testrply(self):
        data = types.nlm4_testrply()
        data.stat = self.unpack_nlm4_stats()
        if data.stat == const.NLM4_DENIED:
            data.holder = self.unpack_nlm4_holder()
        else:
            pass
        if hasattr(self, 'filter_nlm4_testrply'):
            data = getattr(self, 'filter_nlm4_testrply')(data)
        return data

    def unpack_nlm4_stat(self):
        data = types.nlm4_stat()
        data.stat = self.unpack_nlm4_stats()
        if hasattr(self, 'filter_nlm4_stat'):
            data = getattr(self, 'filter_nlm4_stat')(data)
        return data

    def unpack_nlm4_res(self):
        data = types.nlm4_res()
        data.cookie = self.unpack_netobj()
        data.stat = self.unpack_nlm4_stat()
        if hasattr(self, 'filter_nlm4_res'):
            data = getattr(self, 'filter_nlm4_res')(data)
        return data

    def unpack_nlm4_testres(self):
        data = types.nlm4_testres()
        data.cookie = self.unpack_netobj()
        data.stat = self.unpack_nlm4_testrply()
        if hasattr(self, 'filter_nlm4_testres'):
            data = getattr(self, 'filter_nlm4_testres')(data)
        return data

    def unpack_nlm4_lock(self):
        data = types.nlm4_lock()
        data.caller_name = self.unpack_string()
        if len(data.caller_name) > const.LM_MAXSTRLEN and self.check_array:
            raise XDRError('array length too long for data.caller_name')
        data.fh = self.unpack_netobj()
        data.oh = self.unpack_netobj()
        data.svid = self.unpack_int32()
        data.l_offset = self.unpack_uint64()
        data.l_len = self.unpack_uint64()
        if hasattr(self, 'filter_nlm4_lock'):
            data = getattr(self, 'filter_nlm4_lock')(data)
        return data

    def unpack_nlm4_lockargs(self):
        data = types.nlm4_lockargs()
        data.cookie = self.unpack_netobj()
        data.block = self.unpack_bool()
        data.exclusive = self.unpack_bool()
        data.alock = self.unpack_nlm4_lock()
        data.reclaim = self.unpack_bool()
        data.state = self.unpack_int32()
        if hasattr(self, 'filter_nlm4_lockargs'):
            data = getattr(self, 'filter_nlm4_lockargs')(data)
        return data

    def unpack_nlm4_cancargs(self):
        data = types.nlm4_cancargs()
        data.cookie = self.unpack_netobj()
        data.block = self.unpack_bool()
        data.exclusive = self.unpack_bool()
        data.alock = self.unpack_nlm4_lock()
        if hasattr(self, 'filter_nlm4_cancargs'):
            data = getattr(self, 'filter_nlm4_cancargs')(data)
        return data

    def unpack_nlm4_testargs(self):
        data = types.nlm4_testargs()
        data.cookie = self.unpack_netobj()
        data.exclusive = self.unpack_bool()
        data.alock = self.unpack_nlm4_lock()
        if hasattr(self, 'filter_nlm4_testargs'):
            data = getattr(self, 'filter_nlm4_testargs')(data)
        return data

    def unpack_nlm4_unlockargs(self):
        data = types.nlm4_unlockargs()
        data.cookie = self.unpack_netobj()
        data.alock = self.unpack_nlm4_lock()
        if hasattr(self, 'filter_nlm4_unlockargs'):
            data = getattr(self, 'filter_nlm4_unlockargs')(data)
        return data

    def unpack_fsh4_mode(self):
        data = self.unpack_int()
        if self.check_enum and data not in [const.FSM_DN, const.FSM_DR, const.FSM_DW, const.FSM_DRW]:
            raise XDRError('value=%s not in enum fsh4_mode' % data)
        if hasattr(self, 'filter_fsh4_mode'):
            data = getattr(self, 'filter_fsh4_mode')(data)
        return data

    def unpack_fsh4_access(self):
        data = self.unpack_int()
        if self.check_enum and data not in [const.FSA_NONE, const.FSA_R, const.FSA_W, const.FSA_RW]:
            raise XDRError('value=%s not in enum fsh4_access' % data)
        if hasattr(self, 'filter_fsh4_access'):
            data = getattr(self, 'filter_fsh4_access')(data)
        return data

    def unpack_nlm4_share(self):
        data = types.nlm4_share()
        data.caller_name = self.unpack_string()
        if len(data.caller_name) > const.LM_MAXSTRLEN and self.check_array:
            raise XDRError('array length too long for data.caller_name')
        data.fh = self.unpack_netobj()
        data.oh = self.unpack_netobj()
        data.mode = self.unpack_fsh4_mode()
        data.access = self.unpack_fsh4_access()
        if hasattr(self, 'filter_nlm4_share'):
            data = getattr(self, 'filter_nlm4_share')(data)
        return data

    def unpack_nlm4_shareargs(self):
        data = types.nlm4_shareargs()
        data.cookie = self.unpack_netobj()
        data.share = self.unpack_nlm4_share()
        data.reclaim = self.unpack_bool()
        if hasattr(self, 'filter_nlm4_shareargs'):
            data = getattr(self, 'filter_nlm4_shareargs')(data)
        return data

    def unpack_nlm4_shareres(self):
        data = types.nlm4_shareres()
        data.cookie = self.unpack_netobj()
        data.stat = self.unpack_nlm4_stats()
        data.sequence = self.unpack_int32()
        if hasattr(self, 'filter_nlm4_shareres'):
            data = getattr(self, 'filter_nlm4_shareres')(data)
        return data

    def unpack_nlm4_notify(self):
        data = types.nlm4_notify()
        data.name = self.unpack_string()
        if len(data.name) > const.LM_MAXNAMELEN and self.check_array:
            raise XDRError('array length too long for data.name')
        data.state = self.unpack_int32()
        if hasattr(self, 'filter_nlm4_notify'):
            data = getattr(self, 'filter_nlm4_notify')(data)
        return data

