# Generated by rpcgen.py from nsm.x on Wed Jun 24 11:38:48 2026
import nsm_const as const
class sm_name:
    # XDR definition:
    # struct sm_name {
    #     string mon_name<SM_MAXSTRLEN>;
    # };
    def __init__(self, mon_name=None):
        self.mon_name = mon_name

    def __repr__(self):
        out = []
        if self.mon_name is not None:
            out += ['mon_name=%s' % repr(self.mon_name)]
        return 'sm_name(%s)' % ', '.join(out)
    __str__ = __repr__

class sm_stat_res:
    # XDR definition:
    # struct sm_stat_res {
    #     res res_stat;
    #     int state;
    # };
    def __init__(self, res_stat=None, state=None):
        self.res_stat = res_stat
        self.state = state

    def __repr__(self):
        out = []
        if self.res_stat is not None:
            out += ['res_stat=%s' % const.res.get(self.res_stat, self.res_stat)]
        if self.state is not None:
            out += ['state=%s' % repr(self.state)]
        return 'sm_stat_res(%s)' % ', '.join(out)
    __str__ = __repr__

class sm_stat:
    # XDR definition:
    # struct sm_stat {
    #     int state;
    # };
    def __init__(self, state=None):
        self.state = state

    def __repr__(self):
        out = []
        if self.state is not None:
            out += ['state=%s' % repr(self.state)]
        return 'sm_stat(%s)' % ', '.join(out)
    __str__ = __repr__

class my_id:
    # XDR definition:
    # struct my_id {
    #     string my_name<SM_MAXSTRLEN>;
    #     int my_prog;
    #     int my_vers;
    #     int my_proc;
    # };
    def __init__(self, my_name=None, my_prog=None, my_vers=None, my_proc=None):
        self.my_name = my_name
        self.my_prog = my_prog
        self.my_vers = my_vers
        self.my_proc = my_proc

    def __repr__(self):
        out = []
        if self.my_name is not None:
            out += ['my_name=%s' % repr(self.my_name)]
        if self.my_prog is not None:
            out += ['my_prog=%s' % repr(self.my_prog)]
        if self.my_vers is not None:
            out += ['my_vers=%s' % repr(self.my_vers)]
        if self.my_proc is not None:
            out += ['my_proc=%s' % repr(self.my_proc)]
        return 'my_id(%s)' % ', '.join(out)
    __str__ = __repr__

class mon_id:
    # XDR definition:
    # struct mon_id {
    #     string mon_name<SM_MAXSTRLEN>;
    #     my_id my_id;
    # };
    def __init__(self, mon_name=None, my_id=None):
        self.mon_name = mon_name
        self.my_id = my_id

    def __getattr__(self, attr):
        return getattr(self.my_id, attr)

    def __repr__(self):
        out = []
        if self.mon_name is not None:
            out += ['mon_name=%s' % repr(self.mon_name)]
        if self.my_id is not None:
            out += ['my_id=%s' % repr(self.my_id)]
        return 'mon_id(%s)' % ', '.join(out)
    __str__ = __repr__

class mon:
    # XDR definition:
    # struct mon {
    #     mon_id mon_id;
    #     opaque priv[16];
    # };
    def __init__(self, mon_id=None, priv=None):
        self.mon_id = mon_id
        self.priv = priv

    def __getattr__(self, attr):
        return getattr(self.mon_id, attr)

    def __repr__(self):
        out = []
        if self.mon_id is not None:
            out += ['mon_id=%s' % repr(self.mon_id)]
        if self.priv is not None:
            out += ['priv=%s' % repr(self.priv)]
        return 'mon(%s)' % ', '.join(out)
    __str__ = __repr__

class stat_chge:
    # XDR definition:
    # struct stat_chge {
    #     string mon_name<SM_MAXSTRLEN>;
    #     int state;
    # };
    def __init__(self, mon_name=None, state=None):
        self.mon_name = mon_name
        self.state = state

    def __repr__(self):
        out = []
        if self.mon_name is not None:
            out += ['mon_name=%s' % repr(self.mon_name)]
        if self.state is not None:
            out += ['state=%s' % repr(self.state)]
        return 'stat_chge(%s)' % ', '.join(out)
    __str__ = __repr__

class nsm_callback_status:
    # XDR definition:
    # struct nsm_callback_status {
    #     string mon_name<SM_MAXSTRLEN>;
    #     int state;
    #     opaque priv[16];
    # };
    def __init__(self, mon_name=None, state=None, priv=None):
        self.mon_name = mon_name
        self.state = state
        self.priv = priv

    def __repr__(self):
        out = []
        if self.mon_name is not None:
            out += ['mon_name=%s' % repr(self.mon_name)]
        if self.state is not None:
            out += ['state=%s' % repr(self.state)]
        if self.priv is not None:
            out += ['priv=%s' % repr(self.priv)]
        return 'nsm_callback_status(%s)' % ', '.join(out)
    __str__ = __repr__

