# Generated by rpcgen.py from nsm.x on Wed Jun 24 11:38:48 2026
SM_NULL = 0
SM_STAT = 1
SM_MON = 2
SM_UNMON = 3
SM_UNMON_ALL = 4
SM_SIMU_CRASH = 5
SM_NOTIFY = 6
SM_MAXSTRLEN = 1024
STAT_SUCC = 0
STAT_FAIL = 1
res = {
    0 : 'STAT_SUCC',
    1 : 'STAT_FAIL',
}
SM_PROG = 100024
SM_VERS = 1
