# Generated by rpcgen.py from nsm.x on Wed Jun 24 11:38:48 2026
import nsm_const as const
import nsm_type as types
import xdrlib
from xdrlib import Error as XDRError

class nullclass(object):
    pass

def _str2bytes(data):
    # Python 3: xdrlib requires bytes for opaque/string fields.  Python 2 str
    # values were raw bytes, so latin-1 reproduces those byte values exactly
    # (and is identical to ASCII/utf-8 for plain text).
    if isinstance(data, str):
        return data.encode('latin-1')
    return data

class NSMPacker(xdrlib.Packer):
    def __init__(self, check_enum=True, check_array=True):
        xdrlib.Packer.__init__(self)
        self.check_enum = check_enum
        self.check_array = check_array

    pack_int = xdrlib.Packer.pack_int
    pack_long = xdrlib.Packer.pack_int
    pack_uint = xdrlib.Packer.pack_uint
    pack_unsigned = xdrlib.Packer.pack_uint
    pack_hyper = xdrlib.Packer.pack_hyper
    pack_uhyper = xdrlib.Packer.pack_uhyper
    pack_float = xdrlib.Packer.pack_float
    pack_double = xdrlib.Packer.pack_double
    pack_quadruple = xdrlib.Packer.pack_double
    pack_bool = xdrlib.Packer.pack_bool
    def pack_opaque(self, data):
        return xdrlib.Packer.pack_opaque(self, _str2bytes(data))
    def pack_string(self, data):
        return xdrlib.Packer.pack_string(self, _str2bytes(data))
    def pack_fopaque(self, n, data):
        return xdrlib.Packer.pack_fopaque(self, n, _str2bytes(data))
    def pack_fstring(self, n, data):
        return xdrlib.Packer.pack_fstring(self, n, _str2bytes(data))
    def pack_sm_name(self, data):
        if hasattr(self, 'filter_sm_name'):
            data = getattr(self, 'filter_sm_name')(data)
        if data.mon_name is None:
            raise TypeError('data.mon_name == None')
        if len(data.mon_name) > const.SM_MAXSTRLEN and self.check_array:
            raise XDRError('array length too long for data.mon_name')
        self.pack_string(data.mon_name)

    def pack_res(self, data):
        if hasattr(self, 'filter_res'):
            data = getattr(self, 'filter_res')(data)
        if self.check_enum and data not in [const.STAT_SUCC, const.STAT_FAIL]:
            raise XDRError('value=%s not in enum res' % data)
        self.pack_int(data)

    def pack_sm_stat_res(self, data):
        if hasattr(self, 'filter_sm_stat_res'):
            data = getattr(self, 'filter_sm_stat_res')(data)
        if data.res_stat is None:
            raise TypeError('data.res_stat == None')
        self.pack_res(data.res_stat)
        if data.state is None:
            raise TypeError('data.state == None')
        self.pack_int(data.state)

    def pack_sm_stat(self, data):
        if hasattr(self, 'filter_sm_stat'):
            data = getattr(self, 'filter_sm_stat')(data)
        if data.state is None:
            raise TypeError('data.state == None')
        self.pack_int(data.state)

    def pack_my_id(self, data):
        if hasattr(self, 'filter_my_id'):
            data = getattr(self, 'filter_my_id')(data)
        if data.my_name is None:
            raise TypeError('data.my_name == None')
        if len(data.my_name) > const.SM_MAXSTRLEN and self.check_array:
            raise XDRError('array length too long for data.my_name')
        self.pack_string(data.my_name)
        if data.my_prog is None:
            raise TypeError('data.my_prog == None')
        self.pack_int(data.my_prog)
        if data.my_vers is None:
            raise TypeError('data.my_vers == None')
        self.pack_int(data.my_vers)
        if data.my_proc is None:
            raise TypeError('data.my_proc == None')
        self.pack_int(data.my_proc)

    def pack_mon_id(self, data):
        if hasattr(self, 'filter_mon_id'):
            data = getattr(self, 'filter_mon_id')(data)
        if data.mon_name is None:
            raise TypeError('data.mon_name == None')
        if len(data.mon_name) > const.SM_MAXSTRLEN and self.check_array:
            raise XDRError('array length too long for data.mon_name')
        self.pack_string(data.mon_name)
        if data.my_id is None:
            raise TypeError('data.my_id == None')
        self.pack_my_id(data.my_id)

    def pack_mon(self, data):
        if hasattr(self, 'filter_mon'):
            data = getattr(self, 'filter_mon')(data)
        if data.mon_id is None:
            raise TypeError('data.mon_id == None')
        self.pack_mon_id(data.mon_id)
        if data.priv is None:
            raise TypeError('data.priv == None')
        self.pack_fopaque(16, data.priv)

    def pack_stat_chge(self, data):
        if hasattr(self, 'filter_stat_chge'):
            data = getattr(self, 'filter_stat_chge')(data)
        if data.mon_name is None:
            raise TypeError('data.mon_name == None')
        if len(data.mon_name) > const.SM_MAXSTRLEN and self.check_array:
            raise XDRError('array length too long for data.mon_name')
        self.pack_string(data.mon_name)
        if data.state is None:
            raise TypeError('data.state == None')
        self.pack_int(data.state)

    def pack_nsm_callback_status(self, data):
        if hasattr(self, 'filter_nsm_callback_status'):
            data = getattr(self, 'filter_nsm_callback_status')(data)
        if data.mon_name is None:
            raise TypeError('data.mon_name == None')
        if len(data.mon_name) > const.SM_MAXSTRLEN and self.check_array:
            raise XDRError('array length too long for data.mon_name')
        self.pack_string(data.mon_name)
        if data.state is None:
            raise TypeError('data.state == None')
        self.pack_int(data.state)
        if data.priv is None:
            raise TypeError('data.priv == None')
        self.pack_fopaque(16, data.priv)

class NSMUnpacker(xdrlib.Unpacker):
    def __init__(self, data, check_enum=True, check_array=True):
        xdrlib.Unpacker.__init__(self, data)
        self.check_enum = check_enum
        self.check_array = check_array

    unpack_int = xdrlib.Unpacker.unpack_int
    unpack_long = xdrlib.Unpacker.unpack_int
    unpack_uint = xdrlib.Unpacker.unpack_uint
    unpack_unsigned = xdrlib.Unpacker.unpack_uint
    unpack_hyper = xdrlib.Unpacker.unpack_hyper
    unpack_uhyper = xdrlib.Unpacker.unpack_uhyper
    unpack_float = xdrlib.Unpacker.unpack_float
    unpack_double = xdrlib.Unpacker.unpack_double
    unpack_quadruple = xdrlib.Unpacker.unpack_double
    unpack_bool = xdrlib.Unpacker.unpack_bool
    unpack_opaque = xdrlib.Unpacker.unpack_opaque
    unpack_string = xdrlib.Unpacker.unpack_string
    def unpack_sm_name(self):
        data = types.sm_name()
        data.mon_name = self.unpack_string()
        if len(data.mon_name) > const.SM_MAXSTRLEN and self.check_array:
            raise XDRError('array length too long for data.mon_name')
        if hasattr(self, 'filter_sm_name'):
            data = getattr(self, 'filter_sm_name')(data)
        return data

    def unpack_res(self):
        data = self.unpack_int()
        if self.check_enum and data not in [const.STAT_SUCC, const.STAT_FAIL]:
            raise XDRError('value=%s not in enum res' % data)
        if hasattr(self, 'filter_res'):
            data = getattr(self, 'filter_res')(data)
        return data

    def unpack_sm_stat_res(self):
        data = types.sm_stat_res()
        data.res_stat = self.unpack_res()
        data.state = self.unpack_int()
        if hasattr(self, 'filter_sm_stat_res'):
            data = getattr(self, 'filter_sm_stat_res')(data)
        return data

    def unpack_sm_stat(self):
        data = types.sm_stat()
        data.state = self.unpack_int()
        if hasattr(self, 'filter_sm_stat'):
            data = getattr(self, 'filter_sm_stat')(data)
        return data

    def unpack_my_id(self):
        data = types.my_id()
        data.my_name = self.unpack_string()
        if len(data.my_name) > const.SM_MAXSTRLEN and self.check_array:
            raise XDRError('array length too long for data.my_name')
        data.my_prog = self.unpack_int()
        data.my_vers = self.unpack_int()
        data.my_proc = self.unpack_int()
        if hasattr(self, 'filter_my_id'):
            data = getattr(self, 'filter_my_id')(data)
        return data

    def unpack_mon_id(self):
        data = types.mon_id()
        data.mon_name = self.unpack_string()
        if len(data.mon_name) > const.SM_MAXSTRLEN and self.check_array:
            raise XDRError('array length too long for data.mon_name')
        data.my_id = self.unpack_my_id()
        if hasattr(self, 'filter_mon_id'):
            data = getattr(self, 'filter_mon_id')(data)
        return data

    def unpack_mon(self):
        data = types.mon()
        data.mon_id = self.unpack_mon_id()
        data.priv = self.unpack_fopaque(16)
        if hasattr(self, 'filter_mon'):
            data = getattr(self, 'filter_mon')(data)
        return data

    def unpack_stat_chge(self):
        data = types.stat_chge()
        data.mon_name = self.unpack_string()
        if len(data.mon_name) > const.SM_MAXSTRLEN and self.check_array:
            raise XDRError('array length too long for data.mon_name')
        data.state = self.unpack_int()
        if hasattr(self, 'filter_stat_chge'):
            data = getattr(self, 'filter_stat_chge')(data)
        return data

    def unpack_nsm_callback_status(self):
        data = types.nsm_callback_status()
        data.mon_name = self.unpack_string()
        if len(data.mon_name) > const.SM_MAXSTRLEN and self.check_array:
            raise XDRError('array length too long for data.mon_name')
        data.state = self.unpack_int()
        data.priv = self.unpack_fopaque(16)
        if hasattr(self, 'filter_nsm_callback_status'):
            data = getattr(self, 'filter_nsm_callback_status')(data)
        return data

