# Generated by rpcgen.py from acl.x on Wed Jun 24 11:38:48 2026
import acl_const as const
import acl_type as types
import xdrlib
from xdrlib import Error as XDRError

class nullclass(object):
    pass

def _str2bytes(data):
    # Python 3: xdrlib requires bytes for opaque/string fields.  Python 2 str
    # values were raw bytes, so latin-1 reproduces those byte values exactly
    # (and is identical to ASCII/utf-8 for plain text).
    if isinstance(data, str):
        return data.encode('latin-1')
    return data

class ACLPacker(xdrlib.Packer):
    def __init__(self, check_enum=True, check_array=True):
        xdrlib.Packer.__init__(self)
        self.check_enum = check_enum
        self.check_array = check_array

    pack_int = xdrlib.Packer.pack_int
    pack_long = xdrlib.Packer.pack_int
    pack_uint = xdrlib.Packer.pack_uint
    pack_unsigned = xdrlib.Packer.pack_uint
    pack_hyper = xdrlib.Packer.pack_hyper
    pack_uhyper = xdrlib.Packer.pack_uhyper
    pack_float = xdrlib.Packer.pack_float
    pack_double = xdrlib.Packer.pack_double
    pack_quadruple = xdrlib.Packer.pack_double
    pack_bool = xdrlib.Packer.pack_bool
    def pack_opaque(self, data):
        return xdrlib.Packer.pack_opaque(self, _str2bytes(data))
    def pack_string(self, data):
        return xdrlib.Packer.pack_string(self, _str2bytes(data))
    def pack_fopaque(self, n, data):
        return xdrlib.Packer.pack_fopaque(self, n, _str2bytes(data))
    def pack_fstring(self, n, data):
        return xdrlib.Packer.pack_fstring(self, n, _str2bytes(data))
    def pack_ftype3(self, data):
        if hasattr(self, 'filter_ftype3'):
            data = getattr(self, 'filter_ftype3')(data)
        if self.check_enum and data not in [const.NF3REG, const.NF3DIR, const.NF3BLK, const.NF3CHR, const.NF3LNK, const.NF3SOCK, const.NF3FIFO]:
            raise XDRError('value=%s not in enum ftype3' % data)
        self.pack_int(data)

    def pack_nfsftype(self, data):
        if hasattr(self, 'filter_nfsftype'):
            data = getattr(self, 'filter_nfsftype')(data)
        if self.check_enum and data not in [const.NFNON, const.NFREG, const.NFDIR, const.NFBLK, const.NFCHR, const.NFLNK]:
            raise XDRError('value=%s not in enum nfsftype' % data)
        self.pack_int(data)

    def pack_nfsstat3(self, data):
        if hasattr(self, 'filter_nfsstat3'):
            data = getattr(self, 'filter_nfsstat3')(data)
        if self.check_enum and data not in [const.NFS3_OK, const.NFS3ERR_PERM, const.NFS3ERR_NOENT, const.NFS3ERR_IO, const.NFS3ERR_NXIO, const.NFS3ERR_ACCES, const.NFS3ERR_EXIST, const.NFS3ERR_XDEV, const.NFS3ERR_NODEV, const.NFS3ERR_NOTDIR, const.NFS3ERR_ISDIR, const.NFS3ERR_INVAL, const.NFS3ERR_FBIG, const.NFS3ERR_NOSPC, const.NFS3ERR_ROFS, const.NFS3ERR_MLINK, const.NFS3ERR_NAMETOOLONG, const.NFS3ERR_NOTEMPTY, const.NFS3ERR_DQUOT, const.NFS3ERR_STALE, const.NFS3ERR_REMOTE, const.NFS3ERR_BADHANDLE, const.NFS3ERR_NOT_SYNC, const.NFS3ERR_BAD_COOKIE, const.NFS3ERR_NOTSUPP, const.NFS3ERR_TOOSMALL, const.NFS3ERR_SERVERFAULT, const.NFS3ERR_BADTYPE, const.NFS3ERR_JUKEBOX, const.NFS3ERR_FPRINTNOTFOUND, const.NFS3ERR_ABORTED]:
            raise XDRError('value=%s not in enum nfsstat3' % data)
        self.pack_int(data)

    pack_uint64 = pack_uhyper

    pack_int64 = pack_hyper

    pack_uint32 = pack_uint

    pack_int32 = pack_int

    pack_uid = pack_int

    pack_o_mode = pack_uint32

    pack_u_int = pack_uint

    def pack_nfs_fh(self, data):
        if hasattr(self, 'filter_nfs_fh'):
            data = getattr(self, 'filter_nfs_fh')(data)
        if data.data is None:
            raise TypeError('data.data == None')
        self.pack_fopaque(const.NFS_FHSIZE, data.data)

    def pack_nfs_fh3(self, data):
        if hasattr(self, 'filter_nfs_fh3'):
            data = getattr(self, 'filter_nfs_fh3')(data)
        if data.data is None:
            raise TypeError('data.data == None')
        if len(data.data) > const.NFS3_FHSIZE and self.check_array:
            raise XDRError('array length too long for data.data')
        self.pack_opaque(data.data)

    def pack_nfs_fh4(self, data):
        if hasattr(self, 'filter_nfs_fh4'):
            data = getattr(self, 'filter_nfs_fh4')(data)
        if data.data is None:
            raise TypeError('data.data == None')
        self.pack_fopaque(const.NFS_FHSIZE, data.data)

    def pack_post_op_attr(self, data):
        if hasattr(self, 'filter_post_op_attr'):
            data = getattr(self, 'filter_post_op_attr')(data)
        if data.present is None:
            raise TypeError('data.present == None')
        self.pack_bool(data.present)
        if data.present == const.TRUE:
            if data.attributes is None:
                raise TypeError('data.attributes == None')
            self.pack_fattr3(data.attributes)
        elif data.present == const.FALSE:
            pass
        else:
            raise XDRError('bad switch=%s' % data.present)

    def pack_specdata3(self, data):
        if hasattr(self, 'filter_specdata3'):
            data = getattr(self, 'filter_specdata3')(data)
        if data.major is None:
            raise TypeError('data.major == None')
        self.pack_uint32(data.major)
        if data.minor is None:
            raise TypeError('data.minor == None')
        self.pack_uint32(data.minor)

    def pack_fattr3(self, data):
        if hasattr(self, 'filter_fattr3'):
            data = getattr(self, 'filter_fattr3')(data)
        if data.type is None:
            raise TypeError('data.type == None')
        self.pack_ftype3(data.type)
        if data.mode is None:
            raise TypeError('data.mode == None')
        self.pack_uint32(data.mode)
        if data.nlink is None:
            raise TypeError('data.nlink == None')
        self.pack_uint32(data.nlink)
        if data.uid is None:
            raise TypeError('data.uid == None')
        self.pack_uint32(data.uid)
        if data.gid is None:
            raise TypeError('data.gid == None')
        self.pack_uint32(data.gid)
        if data.size is None:
            raise TypeError('data.size == None')
        self.pack_uint64(data.size)
        if data.used is None:
            raise TypeError('data.used == None')
        self.pack_uint64(data.used)
        if data.rdev is None:
            raise TypeError('data.rdev == None')
        self.pack_specdata3(data.rdev)
        if data.fsid is None:
            raise TypeError('data.fsid == None')
        self.pack_uint64(data.fsid)
        if data.fileid is None:
            raise TypeError('data.fileid == None')
        self.pack_uint64(data.fileid)
        if data.atime is None:
            raise TypeError('data.atime == None')
        self.pack_nfstime3(data.atime)
        if data.mtime is None:
            raise TypeError('data.mtime == None')
        self.pack_nfstime3(data.mtime)
        if data.ctime is None:
            raise TypeError('data.ctime == None')
        self.pack_nfstime3(data.ctime)

    def pack_nfstime3(self, data):
        if hasattr(self, 'filter_nfstime3'):
            data = getattr(self, 'filter_nfstime3')(data)
        if data.seconds is None:
            raise TypeError('data.seconds == None')
        self.pack_uint32(data.seconds)
        if data.nseconds is None:
            raise TypeError('data.nseconds == None')
        self.pack_uint32(data.nseconds)

    def pack_nfsfattr(self, data):
        if hasattr(self, 'filter_nfsfattr'):
            data = getattr(self, 'filter_nfsfattr')(data)
        if data.na_type is None:
            raise TypeError('data.na_type == None')
        self.pack_nfsftype(data.na_type)
        if data.na_mode is None:
            raise TypeError('data.na_mode == None')
        self.pack_uint64(data.na_mode)
        if data.na_nlink is None:
            raise TypeError('data.na_nlink == None')
        self.pack_uint64(data.na_nlink)
        if data.na_uid is None:
            raise TypeError('data.na_uid == None')
        self.pack_uint64(data.na_uid)
        if data.na_gid is None:
            raise TypeError('data.na_gid == None')
        self.pack_uint64(data.na_gid)
        if data.na_size is None:
            raise TypeError('data.na_size == None')
        self.pack_uint64(data.na_size)
        if data.na_blocksize is None:
            raise TypeError('data.na_blocksize == None')
        self.pack_uint64(data.na_blocksize)
        if data.na_rdev is None:
            raise TypeError('data.na_rdev == None')
        self.pack_uint64(data.na_rdev)
        if data.na_blocks is None:
            raise TypeError('data.na_blocks == None')
        self.pack_uint64(data.na_blocks)
        if data.na_fsid is None:
            raise TypeError('data.na_fsid == None')
        self.pack_uint64(data.na_fsid)
        if data.na_nodeid is None:
            raise TypeError('data.na_nodeid == None')
        self.pack_uint64(data.na_nodeid)
        if data.na_atime is None:
            raise TypeError('data.na_atime == None')
        self.pack_nfstime3(data.na_atime)
        if data.na_mtime is None:
            raise TypeError('data.na_mtime == None')
        self.pack_nfstime3(data.na_mtime)
        if data.na_ctime is None:
            raise TypeError('data.na_ctime == None')
        self.pack_nfstime3(data.na_ctime)

    def pack_aclent(self, data):
        if hasattr(self, 'filter_aclent'):
            data = getattr(self, 'filter_aclent')(data)
        if data.type is None:
            raise TypeError('data.type == None')
        self.pack_int(data.type)
        if data.id is None:
            raise TypeError('data.id == None')
        self.pack_uid(data.id)
        if data.perm is None:
            raise TypeError('data.perm == None')
        self.pack_o_mode(data.perm)

    def pack_secattr(self, data):
        if hasattr(self, 'filter_secattr'):
            data = getattr(self, 'filter_secattr')(data)
        if data.mask is None:
            raise TypeError('data.mask == None')
        self.pack_u_int(data.mask)
        if data.aclcnt is None:
            raise TypeError('data.aclcnt == None')
        self.pack_int(data.aclcnt)
        if data.aclent is None:
            raise TypeError('data.aclent == None')
        if len(data.aclent) > const.NFS_ACL_MAX_ENTRIES and self.check_array:
            raise XDRError('array length too long for data.aclent')
        self.pack_array(data.aclent, self.pack_aclent)
        if data.dfaclcnt is None:
            raise TypeError('data.dfaclcnt == None')
        self.pack_int(data.dfaclcnt)
        if data.dfaclent is None:
            raise TypeError('data.dfaclent == None')
        if len(data.dfaclent) > const.NFS_ACL_MAX_ENTRIES and self.check_array:
            raise XDRError('array length too long for data.dfaclent')
        self.pack_array(data.dfaclent, self.pack_aclent)

    def pack_GETACL2args(self, data):
        if hasattr(self, 'filter_GETACL2args'):
            data = getattr(self, 'filter_GETACL2args')(data)
        if data.fh is None:
            raise TypeError('data.fh == None')
        self.pack_nfs_fh(data.fh)
        if data.mask is None:
            raise TypeError('data.mask == None')
        self.pack_u_int(data.mask)

    def pack_GETACL2resok(self, data):
        if hasattr(self, 'filter_GETACL2resok'):
            data = getattr(self, 'filter_GETACL2resok')(data)
        if data.attr is None:
            raise TypeError('data.attr == None')
        self.pack_nfsfattr(data.attr)
        if data.acl is None:
            raise TypeError('data.acl == None')
        self.pack_secattr(data.acl)

    def pack_GETACL2res(self, data):
        if hasattr(self, 'filter_GETACL2res'):
            data = getattr(self, 'filter_GETACL2res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat(data.status)
        if data.status == const.ACL2_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_GETACL2resok(data.resok)
        else:
            pass

    def pack_SETACL2args(self, data):
        if hasattr(self, 'filter_SETACL2args'):
            data = getattr(self, 'filter_SETACL2args')(data)
        if data.fh is None:
            raise TypeError('data.fh == None')
        self.pack_nfs_fh(data.fh)
        if data.acl is None:
            raise TypeError('data.acl == None')
        self.pack_secattr(data.acl)

    def pack_SETACL2resok(self, data):
        if hasattr(self, 'filter_SETACL2resok'):
            data = getattr(self, 'filter_SETACL2resok')(data)
        if data.attr is None:
            raise TypeError('data.attr == None')
        self.pack_nfsfattr(data.attr)

    def pack_SETACL2res(self, data):
        if hasattr(self, 'filter_SETACL2res'):
            data = getattr(self, 'filter_SETACL2res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat(data.status)
        if data.status == const.ACL2_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_SETACL2resok(data.resok)
        else:
            pass

    def pack_GETATTR2args(self, data):
        if hasattr(self, 'filter_GETATTR2args'):
            data = getattr(self, 'filter_GETATTR2args')(data)
        if data.fh is None:
            raise TypeError('data.fh == None')
        self.pack_nfs_fh(data.fh)

    def pack_GETATTR2resok(self, data):
        if hasattr(self, 'filter_GETATTR2resok'):
            data = getattr(self, 'filter_GETATTR2resok')(data)
        if data.attr is None:
            raise TypeError('data.attr == None')
        self.pack_nfs_fh(data.attr)

    def pack_GETATTR2res(self, data):
        if hasattr(self, 'filter_GETATTR2res'):
            data = getattr(self, 'filter_GETATTR2res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat(data.status)
        if data.status == const.ACL2_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_GETATTR2resok(data.resok)
        else:
            pass

    def pack_ACCESS2args(self, data):
        if hasattr(self, 'filter_ACCESS2args'):
            data = getattr(self, 'filter_ACCESS2args')(data)
        if data.fh is None:
            raise TypeError('data.fh == None')
        self.pack_nfs_fh(data.fh)
        if data.access is None:
            raise TypeError('data.access == None')
        self.pack_uint32(data.access)

    def pack_ACCESS2resok(self, data):
        if hasattr(self, 'filter_ACCESS2resok'):
            data = getattr(self, 'filter_ACCESS2resok')(data)
        if data.attr is None:
            raise TypeError('data.attr == None')
        self.pack_nfsfattr(data.attr)
        if data.access is None:
            raise TypeError('data.access == None')
        self.pack_uint32(data.access)

    def pack_ACCESS2res(self, data):
        if hasattr(self, 'filter_ACCESS2res'):
            data = getattr(self, 'filter_ACCESS2res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat(data.status)
        if data.status == const.ACL2_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_ACCESS2resok(data.resok)
        else:
            pass

    def pack_GETXATTRDIR2args(self, data):
        if hasattr(self, 'filter_GETXATTRDIR2args'):
            data = getattr(self, 'filter_GETXATTRDIR2args')(data)
        if data.fh is None:
            raise TypeError('data.fh == None')
        self.pack_nfs_fh(data.fh)
        if data.create is None:
            raise TypeError('data.create == None')
        self.pack_bool(data.create)

    def pack_GETXATTRDIR2resok(self, data):
        if hasattr(self, 'filter_GETXATTRDIR2resok'):
            data = getattr(self, 'filter_GETXATTRDIR2resok')(data)
        if data.fh is None:
            raise TypeError('data.fh == None')
        self.pack_nfs_fh(data.fh)
        if data.attr is None:
            raise TypeError('data.attr == None')
        self.pack_nfsfattr(data.attr)

    def pack_GETXATTRDIR2res(self, data):
        if hasattr(self, 'filter_GETXATTRDIR2res'):
            data = getattr(self, 'filter_GETXATTRDIR2res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat(data.status)
        if data.status == const.ACL2_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_GETXATTRDIR2resok(data.resok)
        else:
            pass

    def pack_GETACL3args(self, data):
        if hasattr(self, 'filter_GETACL3args'):
            data = getattr(self, 'filter_GETACL3args')(data)
        if data.fh is None:
            raise TypeError('data.fh == None')
        self.pack_nfs_fh3(data.fh)
        if data.mask is None:
            raise TypeError('data.mask == None')
        self.pack_u_int(data.mask)

    def pack_GETACL3resok(self, data):
        if hasattr(self, 'filter_GETACL3resok'):
            data = getattr(self, 'filter_GETACL3resok')(data)
        if data.attr is None:
            raise TypeError('data.attr == None')
        self.pack_post_op_attr(data.attr)
        if data.acl is None:
            raise TypeError('data.acl == None')
        self.pack_secattr(data.acl)

    def pack_GETACL3resfail(self, data):
        if hasattr(self, 'filter_GETACL3resfail'):
            data = getattr(self, 'filter_GETACL3resfail')(data)
        if data.attr is None:
            raise TypeError('data.attr == None')
        self.pack_post_op_attr(data.attr)

    def pack_GETACL3res(self, data):
        if hasattr(self, 'filter_GETACL3res'):
            data = getattr(self, 'filter_GETACL3res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat3(data.status)
        if data.status == const.ACL3_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_GETACL3resok(data.resok)
        else:
            if data.resfail is None:
                raise TypeError('data.resfail == None')
            self.pack_GETACL3resfail(data.resfail)

    def pack_SETACL3args(self, data):
        if hasattr(self, 'filter_SETACL3args'):
            data = getattr(self, 'filter_SETACL3args')(data)
        if data.fh is None:
            raise TypeError('data.fh == None')
        self.pack_nfs_fh3(data.fh)
        if data.acl is None:
            raise TypeError('data.acl == None')
        self.pack_secattr(data.acl)

    def pack_SETACL3resok(self, data):
        if hasattr(self, 'filter_SETACL3resok'):
            data = getattr(self, 'filter_SETACL3resok')(data)
        if data.attr is None:
            raise TypeError('data.attr == None')
        self.pack_post_op_attr(data.attr)

    def pack_SETACL3resfail(self, data):
        if hasattr(self, 'filter_SETACL3resfail'):
            data = getattr(self, 'filter_SETACL3resfail')(data)
        if data.attr is None:
            raise TypeError('data.attr == None')
        self.pack_post_op_attr(data.attr)

    def pack_SETACL3res(self, data):
        if hasattr(self, 'filter_SETACL3res'):
            data = getattr(self, 'filter_SETACL3res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat3(data.status)
        if data.status == const.ACL3_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_SETACL3resok(data.resok)
        else:
            if data.resfail is None:
                raise TypeError('data.resfail == None')
            self.pack_SETACL3resfail(data.resfail)

    def pack_GETXATTRDIR3args(self, data):
        if hasattr(self, 'filter_GETXATTRDIR3args'):
            data = getattr(self, 'filter_GETXATTRDIR3args')(data)
        if data.fh is None:
            raise TypeError('data.fh == None')
        self.pack_nfs_fh3(data.fh)
        if data.create is None:
            raise TypeError('data.create == None')
        self.pack_bool(data.create)

    def pack_GETXATTRDIR3resok(self, data):
        if hasattr(self, 'filter_GETXATTRDIR3resok'):
            data = getattr(self, 'filter_GETXATTRDIR3resok')(data)
        if data.fh is None:
            raise TypeError('data.fh == None')
        self.pack_nfs_fh3(data.fh)
        if data.attr is None:
            raise TypeError('data.attr == None')
        self.pack_post_op_attr(data.attr)

    def pack_GETXATTRDIR3res(self, data):
        if hasattr(self, 'filter_GETXATTRDIR3res'):
            data = getattr(self, 'filter_GETXATTRDIR3res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat3(data.status)
        if data.status == const.ACL3_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_GETXATTRDIR3resok(data.resok)
        else:
            pass

    def pack_GETACL4args(self, data):
        if hasattr(self, 'filter_GETACL4args'):
            data = getattr(self, 'filter_GETACL4args')(data)
        if data.fh is None:
            raise TypeError('data.fh == None')
        self.pack_nfs_fh4(data.fh)
        if data.mask is None:
            raise TypeError('data.mask == None')
        self.pack_u_int(data.mask)

    def pack_GETACL4resok(self, data):
        if hasattr(self, 'filter_GETACL4resok'):
            data = getattr(self, 'filter_GETACL4resok')(data)
        if data.attr is None:
            raise TypeError('data.attr == None')
        self.pack_post_op_attr(data.attr)
        if data.acl is None:
            raise TypeError('data.acl == None')
        self.pack_secattr(data.acl)

    def pack_GETACL4resfail(self, data):
        if hasattr(self, 'filter_GETACL4resfail'):
            data = getattr(self, 'filter_GETACL4resfail')(data)
        if data.attr is None:
            raise TypeError('data.attr == None')
        self.pack_post_op_attr(data.attr)

    def pack_GETACL4res(self, data):
        if hasattr(self, 'filter_GETACL4res'):
            data = getattr(self, 'filter_GETACL4res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat3(data.status)
        if data.status == const.ACL4_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_GETACL4resok(data.resok)
        else:
            if data.resfail is None:
                raise TypeError('data.resfail == None')
            self.pack_GETACL4resfail(data.resfail)

    def pack_SETACL4args(self, data):
        if hasattr(self, 'filter_SETACL4args'):
            data = getattr(self, 'filter_SETACL4args')(data)
        if data.fh is None:
            raise TypeError('data.fh == None')
        self.pack_nfs_fh4(data.fh)
        if data.acl is None:
            raise TypeError('data.acl == None')
        self.pack_secattr(data.acl)

    def pack_SETACL4resok(self, data):
        if hasattr(self, 'filter_SETACL4resok'):
            data = getattr(self, 'filter_SETACL4resok')(data)
        if data.attr is None:
            raise TypeError('data.attr == None')
        self.pack_post_op_attr(data.attr)

    def pack_SETACL4resfail(self, data):
        if hasattr(self, 'filter_SETACL4resfail'):
            data = getattr(self, 'filter_SETACL4resfail')(data)
        if data.attr is None:
            raise TypeError('data.attr == None')
        self.pack_post_op_attr(data.attr)

    def pack_SETACL4res(self, data):
        if hasattr(self, 'filter_SETACL4res'):
            data = getattr(self, 'filter_SETACL4res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat3(data.status)
        if data.status == const.ACL4_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_SETACL4resok(data.resok)
        else:
            if data.resfail is None:
                raise TypeError('data.resfail == None')
            self.pack_SETACL4resfail(data.resfail)

class ACLUnpacker(xdrlib.Unpacker):
    def __init__(self, data, check_enum=True, check_array=True):
        xdrlib.Unpacker.__init__(self, data)
        self.check_enum = check_enum
        self.check_array = check_array

    unpack_int = xdrlib.Unpacker.unpack_int
    unpack_long = xdrlib.Unpacker.unpack_int
    unpack_uint = xdrlib.Unpacker.unpack_uint
    unpack_unsigned = xdrlib.Unpacker.unpack_uint
    unpack_hyper = xdrlib.Unpacker.unpack_hyper
    unpack_uhyper = xdrlib.Unpacker.unpack_uhyper
    unpack_float = xdrlib.Unpacker.unpack_float
    unpack_double = xdrlib.Unpacker.unpack_double
    unpack_quadruple = xdrlib.Unpacker.unpack_double
    unpack_bool = xdrlib.Unpacker.unpack_bool
    unpack_opaque = xdrlib.Unpacker.unpack_opaque
    unpack_string = xdrlib.Unpacker.unpack_string
    def unpack_ftype3(self):
        data = self.unpack_int()
        if self.check_enum and data not in [const.NF3REG, const.NF3DIR, const.NF3BLK, const.NF3CHR, const.NF3LNK, const.NF3SOCK, const.NF3FIFO]:
            raise XDRError('value=%s not in enum ftype3' % data)
        if hasattr(self, 'filter_ftype3'):
            data = getattr(self, 'filter_ftype3')(data)
        return data

    def unpack_nfsftype(self):
        data = self.unpack_int()
        if self.check_enum and data not in [const.NFNON, const.NFREG, const.NFDIR, const.NFBLK, const.NFCHR, const.NFLNK]:
            raise XDRError('value=%s not in enum nfsftype' % data)
        if hasattr(self, 'filter_nfsftype'):
            data = getattr(self, 'filter_nfsftype')(data)
        return data

    def unpack_nfsstat3(self):
        data = self.unpack_int()
        if self.check_enum and data not in [const.NFS3_OK, const.NFS3ERR_PERM, const.NFS3ERR_NOENT, const.NFS3ERR_IO, const.NFS3ERR_NXIO, const.NFS3ERR_ACCES, const.NFS3ERR_EXIST, const.NFS3ERR_XDEV, const.NFS3ERR_NODEV, const.NFS3ERR_NOTDIR, const.NFS3ERR_ISDIR, const.NFS3ERR_INVAL, const.NFS3ERR_FBIG, const.NFS3ERR_NOSPC, const.NFS3ERR_ROFS, const.NFS3ERR_MLINK, const.NFS3ERR_NAMETOOLONG, const.NFS3ERR_NOTEMPTY, const.NFS3ERR_DQUOT, const.NFS3ERR_STALE, const.NFS3ERR_REMOTE, const.NFS3ERR_BADHANDLE, const.NFS3ERR_NOT_SYNC, const.NFS3ERR_BAD_COOKIE, const.NFS3ERR_NOTSUPP, const.NFS3ERR_TOOSMALL, const.NFS3ERR_SERVERFAULT, const.NFS3ERR_BADTYPE, const.NFS3ERR_JUKEBOX, const.NFS3ERR_FPRINTNOTFOUND, const.NFS3ERR_ABORTED]:
            raise XDRError('value=%s not in enum nfsstat3' % data)
        if hasattr(self, 'filter_nfsstat3'):
            data = getattr(self, 'filter_nfsstat3')(data)
        return data

    unpack_uint64 = unpack_uhyper

    unpack_int64 = unpack_hyper

    unpack_uint32 = unpack_uint

    unpack_int32 = unpack_int

    unpack_uid = unpack_int

    unpack_o_mode = unpack_uint32

    unpack_u_int = unpack_uint

    def unpack_nfs_fh(self):
        data = types.nfs_fh()
        data.data = self.unpack_fopaque(const.NFS_FHSIZE)
        if hasattr(self, 'filter_nfs_fh'):
            data = getattr(self, 'filter_nfs_fh')(data)
        return data

    def unpack_nfs_fh3(self):
        data = types.nfs_fh3()
        data.data = self.unpack_opaque()
        if len(data.data) > const.NFS3_FHSIZE and self.check_array:
            raise XDRError('array length too long for data.data')
        if hasattr(self, 'filter_nfs_fh3'):
            data = getattr(self, 'filter_nfs_fh3')(data)
        return data

    def unpack_nfs_fh4(self):
        data = types.nfs_fh4()
        data.data = self.unpack_fopaque(const.NFS_FHSIZE)
        if hasattr(self, 'filter_nfs_fh4'):
            data = getattr(self, 'filter_nfs_fh4')(data)
        return data

    def unpack_post_op_attr(self):
        data = types.post_op_attr()
        data.present = self.unpack_bool()
        if data.present == const.TRUE:
            data.attributes = self.unpack_fattr3()
        elif data.present == const.FALSE:
            pass
        else:
            raise XDRError('bad switch=%s' % data.present)
        if hasattr(self, 'filter_post_op_attr'):
            data = getattr(self, 'filter_post_op_attr')(data)
        return data

    def unpack_specdata3(self):
        data = types.specdata3()
        data.major = self.unpack_uint32()
        data.minor = self.unpack_uint32()
        if hasattr(self, 'filter_specdata3'):
            data = getattr(self, 'filter_specdata3')(data)
        return data

    def unpack_fattr3(self):
        data = types.fattr3()
        data.type = self.unpack_ftype3()
        data.mode = self.unpack_uint32()
        data.nlink = self.unpack_uint32()
        data.uid = self.unpack_uint32()
        data.gid = self.unpack_uint32()
        data.size = self.unpack_uint64()
        data.used = self.unpack_uint64()
        data.rdev = self.unpack_specdata3()
        data.fsid = self.unpack_uint64()
        data.fileid = self.unpack_uint64()
        data.atime = self.unpack_nfstime3()
        data.mtime = self.unpack_nfstime3()
        data.ctime = self.unpack_nfstime3()
        if hasattr(self, 'filter_fattr3'):
            data = getattr(self, 'filter_fattr3')(data)
        return data

    def unpack_nfstime3(self):
        data = types.nfstime3()
        data.seconds = self.unpack_uint32()
        data.nseconds = self.unpack_uint32()
        if hasattr(self, 'filter_nfstime3'):
            data = getattr(self, 'filter_nfstime3')(data)
        return data

    def unpack_nfsfattr(self):
        data = types.nfsfattr()
        data.na_type = self.unpack_nfsftype()
        data.na_mode = self.unpack_uint64()
        data.na_nlink = self.unpack_uint64()
        data.na_uid = self.unpack_uint64()
        data.na_gid = self.unpack_uint64()
        data.na_size = self.unpack_uint64()
        data.na_blocksize = self.unpack_uint64()
        data.na_rdev = self.unpack_uint64()
        data.na_blocks = self.unpack_uint64()
        data.na_fsid = self.unpack_uint64()
        data.na_nodeid = self.unpack_uint64()
        data.na_atime = self.unpack_nfstime3()
        data.na_mtime = self.unpack_nfstime3()
        data.na_ctime = self.unpack_nfstime3()
        if hasattr(self, 'filter_nfsfattr'):
            data = getattr(self, 'filter_nfsfattr')(data)
        return data

    def unpack_aclent(self):
        data = types.aclent()
        data.type = self.unpack_int()
        data.id = self.unpack_uid()
        data.perm = self.unpack_o_mode()
        if hasattr(self, 'filter_aclent'):
            data = getattr(self, 'filter_aclent')(data)
        return data

    def unpack_secattr(self):
        data = types.secattr()
        data.mask = self.unpack_u_int()
        data.aclcnt = self.unpack_int()
        data.aclent = self.unpack_array(self.unpack_aclent)
        if len(data.aclent) > const.NFS_ACL_MAX_ENTRIES and self.check_array:
            raise XDRError('array length too long for data.aclent')
        data.dfaclcnt = self.unpack_int()
        data.dfaclent = self.unpack_array(self.unpack_aclent)
        if len(data.dfaclent) > const.NFS_ACL_MAX_ENTRIES and self.check_array:
            raise XDRError('array length too long for data.dfaclent')
        if hasattr(self, 'filter_secattr'):
            data = getattr(self, 'filter_secattr')(data)
        return data

    def unpack_GETACL2args(self):
        data = types.GETACL2args()
        data.fh = self.unpack_nfs_fh()
        data.mask = self.unpack_u_int()
        if hasattr(self, 'filter_GETACL2args'):
            data = getattr(self, 'filter_GETACL2args')(data)
        return data

    def unpack_GETACL2resok(self):
        data = types.GETACL2resok()
        data.attr = self.unpack_nfsfattr()
        data.acl = self.unpack_secattr()
        if hasattr(self, 'filter_GETACL2resok'):
            data = getattr(self, 'filter_GETACL2resok')(data)
        return data

    def unpack_GETACL2res(self):
        data = types.GETACL2res()
        data.status = self.unpack_nfsstat()
        if data.status == const.ACL2_OK:
            data.resok = self.unpack_GETACL2resok()
        else:
            pass
        if hasattr(self, 'filter_GETACL2res'):
            data = getattr(self, 'filter_GETACL2res')(data)
        return data

    def unpack_SETACL2args(self):
        data = types.SETACL2args()
        data.fh = self.unpack_nfs_fh()
        data.acl = self.unpack_secattr()
        if hasattr(self, 'filter_SETACL2args'):
            data = getattr(self, 'filter_SETACL2args')(data)
        return data

    def unpack_SETACL2resok(self):
        data = types.SETACL2resok()
        data.attr = self.unpack_nfsfattr()
        if hasattr(self, 'filter_SETACL2resok'):
            data = getattr(self, 'filter_SETACL2resok')(data)
        return data

    def unpack_SETACL2res(self):
        data = types.SETACL2res()
        data.status = self.unpack_nfsstat()
        if data.status == const.ACL2_OK:
            data.resok = self.unpack_SETACL2resok()
        else:
            pass
        if hasattr(self, 'filter_SETACL2res'):
            data = getattr(self, 'filter_SETACL2res')(data)
        return data

    def unpack_GETATTR2args(self):
        data = types.GETATTR2args()
        data.fh = self.unpack_nfs_fh()
        if hasattr(self, 'filter_GETATTR2args'):
            data = getattr(self, 'filter_GETATTR2args')(data)
        return data

    def unpack_GETATTR2resok(self):
        data = types.GETATTR2resok()
        data.attr = self.unpack_nfs_fh()
        if hasattr(self, 'filter_GETATTR2resok'):
            data = getattr(self, 'filter_GETATTR2resok')(data)
        return data

    def unpack_GETATTR2res(self):
        data = types.GETATTR2res()
        data.status = self.unpack_nfsstat()
        if data.status == const.ACL2_OK:
            data.resok = self.unpack_GETATTR2resok()
        else:
            pass
        if hasattr(self, 'filter_GETATTR2res'):
            data = getattr(self, 'filter_GETATTR2res')(data)
        return data

    def unpack_ACCESS2args(self):
        data = types.ACCESS2args()
        data.fh = self.unpack_nfs_fh()
        data.access = self.unpack_uint32()
        if hasattr(self, 'filter_ACCESS2args'):
            data = getattr(self, 'filter_ACCESS2args')(data)
        return data

    def unpack_ACCESS2resok(self):
        data = types.ACCESS2resok()
        data.attr = self.unpack_nfsfattr()
        data.access = self.unpack_uint32()
        if hasattr(self, 'filter_ACCESS2resok'):
            data = getattr(self, 'filter_ACCESS2resok')(data)
        return data

    def unpack_ACCESS2res(self):
        data = types.ACCESS2res()
        data.status = self.unpack_nfsstat()
        if data.status == const.ACL2_OK:
            data.resok = self.unpack_ACCESS2resok()
        else:
            pass
        if hasattr(self, 'filter_ACCESS2res'):
            data = getattr(self, 'filter_ACCESS2res')(data)
        return data

    def unpack_GETXATTRDIR2args(self):
        data = types.GETXATTRDIR2args()
        data.fh = self.unpack_nfs_fh()
        data.create = self.unpack_bool()
        if hasattr(self, 'filter_GETXATTRDIR2args'):
            data = getattr(self, 'filter_GETXATTRDIR2args')(data)
        return data

    def unpack_GETXATTRDIR2resok(self):
        data = types.GETXATTRDIR2resok()
        data.fh = self.unpack_nfs_fh()
        data.attr = self.unpack_nfsfattr()
        if hasattr(self, 'filter_GETXATTRDIR2resok'):
            data = getattr(self, 'filter_GETXATTRDIR2resok')(data)
        return data

    def unpack_GETXATTRDIR2res(self):
        data = types.GETXATTRDIR2res()
        data.status = self.unpack_nfsstat()
        if data.status == const.ACL2_OK:
            data.resok = self.unpack_GETXATTRDIR2resok()
        else:
            pass
        if hasattr(self, 'filter_GETXATTRDIR2res'):
            data = getattr(self, 'filter_GETXATTRDIR2res')(data)
        return data

    def unpack_GETACL3args(self):
        data = types.GETACL3args()
        data.fh = self.unpack_nfs_fh3()
        data.mask = self.unpack_u_int()
        if hasattr(self, 'filter_GETACL3args'):
            data = getattr(self, 'filter_GETACL3args')(data)
        return data

    def unpack_GETACL3resok(self):
        data = types.GETACL3resok()
        data.attr = self.unpack_post_op_attr()
        data.acl = self.unpack_secattr()
        if hasattr(self, 'filter_GETACL3resok'):
            data = getattr(self, 'filter_GETACL3resok')(data)
        return data

    def unpack_GETACL3resfail(self):
        data = types.GETACL3resfail()
        data.attr = self.unpack_post_op_attr()
        if hasattr(self, 'filter_GETACL3resfail'):
            data = getattr(self, 'filter_GETACL3resfail')(data)
        return data

    def unpack_GETACL3res(self):
        data = types.GETACL3res()
        data.status = self.unpack_nfsstat3()
        if data.status == const.ACL3_OK:
            data.resok = self.unpack_GETACL3resok()
        else:
            data.resfail = self.unpack_GETACL3resfail()
        if hasattr(self, 'filter_GETACL3res'):
            data = getattr(self, 'filter_GETACL3res')(data)
        return data

    def unpack_SETACL3args(self):
        data = types.SETACL3args()
        data.fh = self.unpack_nfs_fh3()
        data.acl = self.unpack_secattr()
        if hasattr(self, 'filter_SETACL3args'):
            data = getattr(self, 'filter_SETACL3args')(data)
        return data

    def unpack_SETACL3resok(self):
        data = types.SETACL3resok()
        data.attr = self.unpack_post_op_attr()
        if hasattr(self, 'filter_SETACL3resok'):
            data = getattr(self, 'filter_SETACL3resok')(data)
        return data

    def unpack_SETACL3resfail(self):
        data = types.SETACL3resfail()
        data.attr = self.unpack_post_op_attr()
        if hasattr(self, 'filter_SETACL3resfail'):
            data = getattr(self, 'filter_SETACL3resfail')(data)
        return data

    def unpack_SETACL3res(self):
        data = types.SETACL3res()
        data.status = self.unpack_nfsstat3()
        if data.status == const.ACL3_OK:
            data.resok = self.unpack_SETACL3resok()
        else:
            data.resfail = self.unpack_SETACL3resfail()
        if hasattr(self, 'filter_SETACL3res'):
            data = getattr(self, 'filter_SETACL3res')(data)
        return data

    def unpack_GETXATTRDIR3args(self):
        data = types.GETXATTRDIR3args()
        data.fh = self.unpack_nfs_fh3()
        data.create = self.unpack_bool()
        if hasattr(self, 'filter_GETXATTRDIR3args'):
            data = getattr(self, 'filter_GETXATTRDIR3args')(data)
        return data

    def unpack_GETXATTRDIR3resok(self):
        data = types.GETXATTRDIR3resok()
        data.fh = self.unpack_nfs_fh3()
        data.attr = self.unpack_post_op_attr()
        if hasattr(self, 'filter_GETXATTRDIR3resok'):
            data = getattr(self, 'filter_GETXATTRDIR3resok')(data)
        return data

    def unpack_GETXATTRDIR3res(self):
        data = types.GETXATTRDIR3res()
        data.status = self.unpack_nfsstat3()
        if data.status == const.ACL3_OK:
            data.resok = self.unpack_GETXATTRDIR3resok()
        else:
            pass
        if hasattr(self, 'filter_GETXATTRDIR3res'):
            data = getattr(self, 'filter_GETXATTRDIR3res')(data)
        return data

    def unpack_GETACL4args(self):
        data = types.GETACL4args()
        data.fh = self.unpack_nfs_fh4()
        data.mask = self.unpack_u_int()
        if hasattr(self, 'filter_GETACL4args'):
            data = getattr(self, 'filter_GETACL4args')(data)
        return data

    def unpack_GETACL4resok(self):
        data = types.GETACL4resok()
        data.attr = self.unpack_post_op_attr()
        data.acl = self.unpack_secattr()
        if hasattr(self, 'filter_GETACL4resok'):
            data = getattr(self, 'filter_GETACL4resok')(data)
        return data

    def unpack_GETACL4resfail(self):
        data = types.GETACL4resfail()
        data.attr = self.unpack_post_op_attr()
        if hasattr(self, 'filter_GETACL4resfail'):
            data = getattr(self, 'filter_GETACL4resfail')(data)
        return data

    def unpack_GETACL4res(self):
        data = types.GETACL4res()
        data.status = self.unpack_nfsstat3()
        if data.status == const.ACL4_OK:
            data.resok = self.unpack_GETACL4resok()
        else:
            data.resfail = self.unpack_GETACL4resfail()
        if hasattr(self, 'filter_GETACL4res'):
            data = getattr(self, 'filter_GETACL4res')(data)
        return data

    def unpack_SETACL4args(self):
        data = types.SETACL4args()
        data.fh = self.unpack_nfs_fh4()
        data.acl = self.unpack_secattr()
        if hasattr(self, 'filter_SETACL4args'):
            data = getattr(self, 'filter_SETACL4args')(data)
        return data

    def unpack_SETACL4resok(self):
        data = types.SETACL4resok()
        data.attr = self.unpack_post_op_attr()
        if hasattr(self, 'filter_SETACL4resok'):
            data = getattr(self, 'filter_SETACL4resok')(data)
        return data

    def unpack_SETACL4resfail(self):
        data = types.SETACL4resfail()
        data.attr = self.unpack_post_op_attr()
        if hasattr(self, 'filter_SETACL4resfail'):
            data = getattr(self, 'filter_SETACL4resfail')(data)
        return data

    def unpack_SETACL4res(self):
        data = types.SETACL4res()
        data.status = self.unpack_nfsstat3()
        if data.status == const.ACL4_OK:
            data.resok = self.unpack_SETACL4resok()
        else:
            data.resfail = self.unpack_SETACL4resfail()
        if hasattr(self, 'filter_SETACL4res'):
            data = getattr(self, 'filter_SETACL4res')(data)
        return data

