# Generated by rpcgen.py from acl.x on Wed Jun 24 11:38:48 2026
import acl_const as const
class nfs_fh:
    # XDR definition:
    # struct nfs_fh {
    #     opaque data[NFS_FHSIZE];
    # };
    def __init__(self, data=None):
        self.data = data

    def __repr__(self):
        out = []
        if self.data is not None:
            out += ['data=%s' % repr(self.data)]
        return 'nfs_fh(%s)' % ', '.join(out)
    __str__ = __repr__

class nfs_fh3:
    # XDR definition:
    # struct nfs_fh3 {
    #     opaque data<NFS3_FHSIZE>;
    # };
    def __init__(self, data=None):
        self.data = data

    def __repr__(self):
        out = []
        if self.data is not None:
            out += ['data=%s' % repr(self.data)]
        return 'nfs_fh3(%s)' % ', '.join(out)
    __str__ = __repr__

class nfs_fh4:
    # XDR definition:
    # struct nfs_fh4 {
    #     opaque data[NFS_FHSIZE];
    # };
    def __init__(self, data=None):
        self.data = data

    def __repr__(self):
        out = []
        if self.data is not None:
            out += ['data=%s' % repr(self.data)]
        return 'nfs_fh4(%s)' % ', '.join(out)
    __str__ = __repr__

class post_op_attr:
    # XDR definition:
    # union post_op_attr switch(bool present) {
    #     case TRUE:
    #         fattr3 attributes;
    #     case FALSE:
    #         void;
    # };
    def __init__(self, present=None, attributes=None):
        self.present = present
        self.attributes = attributes

    switch = property(lambda s: {const.TRUE:s.attributes,const.FALSE:None,}[s.present])

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.present is not None:
            out += ['present=%s' % repr(self.present)]
        if self.attributes is not None:
            out += ['attributes=%s' % repr(self.attributes)]
        return 'post_op_attr(%s)' % ', '.join(out)
    __str__ = __repr__

class specdata3:
    # XDR definition:
    # struct specdata3 {
    #     uint32 major;
    #     uint32 minor;
    # };
    def __init__(self, major=None, minor=None):
        self.major = major
        self.minor = minor

    def __repr__(self):
        out = []
        if self.major is not None:
            out += ['major=%s' % repr(self.major)]
        if self.minor is not None:
            out += ['minor=%s' % repr(self.minor)]
        return 'specdata3(%s)' % ', '.join(out)
    __str__ = __repr__

class fattr3:
    # XDR definition:
    # struct fattr3 {
    #     ftype3 type;
    #     uint32 mode;
    #     uint32 nlink;
    #     uint32 uid;
    #     uint32 gid;
    #     uint64 size;
    #     uint64 used;
    #     specdata3 rdev;
    #     uint64 fsid;
    #     uint64 fileid;
    #     nfstime3 atime;
    #     nfstime3 mtime;
    #     nfstime3 ctime;
    # };
    def __init__(self, type=None, mode=None, nlink=None, uid=None, gid=None, size=None, used=None, rdev=None, fsid=None, fileid=None, atime=None, mtime=None, ctime=None):
        self.type = type
        self.mode = mode
        self.nlink = nlink
        self.uid = uid
        self.gid = gid
        self.size = size
        self.used = used
        self.rdev = rdev
        self.fsid = fsid
        self.fileid = fileid
        self.atime = atime
        self.mtime = mtime
        self.ctime = ctime

    def __repr__(self):
        out = []
        if self.type is not None:
            out += ['type=%s' % const.ftype3.get(self.type, self.type)]
        if self.mode is not None:
            out += ['mode=%s' % repr(self.mode)]
        if self.nlink is not None:
            out += ['nlink=%s' % repr(self.nlink)]
        if self.uid is not None:
            out += ['uid=%s' % repr(self.uid)]
        if self.gid is not None:
            out += ['gid=%s' % repr(self.gid)]
        if self.size is not None:
            out += ['size=%s' % repr(self.size)]
        if self.used is not None:
            out += ['used=%s' % repr(self.used)]
        if self.rdev is not None:
            out += ['rdev=%s' % repr(self.rdev)]
        if self.fsid is not None:
            out += ['fsid=%s' % repr(self.fsid)]
        if self.fileid is not None:
            out += ['fileid=%s' % repr(self.fileid)]
        if self.atime is not None:
            out += ['atime=%s' % repr(self.atime)]
        if self.mtime is not None:
            out += ['mtime=%s' % repr(self.mtime)]
        if self.ctime is not None:
            out += ['ctime=%s' % repr(self.ctime)]
        return 'fattr3(%s)' % ', '.join(out)
    __str__ = __repr__

class nfstime3:
    # XDR definition:
    # struct nfstime3 {
    #     uint32 seconds;
    #     uint32 nseconds;
    # };
    def __init__(self, seconds=None, nseconds=None):
        self.seconds = seconds
        self.nseconds = nseconds

    def __repr__(self):
        out = []
        if self.seconds is not None:
            out += ['seconds=%s' % repr(self.seconds)]
        if self.nseconds is not None:
            out += ['nseconds=%s' % repr(self.nseconds)]
        return 'nfstime3(%s)' % ', '.join(out)
    __str__ = __repr__

class nfsfattr:
    # XDR definition:
    # struct nfsfattr {
    #     nfsftype na_type;
    #     uint64 na_mode;
    #     uint64 na_nlink;
    #     uint64 na_uid;
    #     uint64 na_gid;
    #     uint64 na_size;
    #     uint64 na_blocksize;
    #     uint64 na_rdev;
    #     uint64 na_blocks;
    #     uint64 na_fsid;
    #     uint64 na_nodeid;
    #     nfstime3 na_atime;
    #     nfstime3 na_mtime;
    #     nfstime3 na_ctime;
    # };
    def __init__(self, na_type=None, na_mode=None, na_nlink=None, na_uid=None, na_gid=None, na_size=None, na_blocksize=None, na_rdev=None, na_blocks=None, na_fsid=None, na_nodeid=None, na_atime=None, na_mtime=None, na_ctime=None):
        self.na_type = na_type
        self.na_mode = na_mode
        self.na_nlink = na_nlink
        self.na_uid = na_uid
        self.na_gid = na_gid
        self.na_size = na_size
        self.na_blocksize = na_blocksize
        self.na_rdev = na_rdev
        self.na_blocks = na_blocks
        self.na_fsid = na_fsid
        self.na_nodeid = na_nodeid
        self.na_atime = na_atime
        self.na_mtime = na_mtime
        self.na_ctime = na_ctime

    def __repr__(self):
        out = []
        if self.na_type is not None:
            out += ['na_type=%s' % const.nfsftype.get(self.na_type, self.na_type)]
        if self.na_mode is not None:
            out += ['na_mode=%s' % repr(self.na_mode)]
        if self.na_nlink is not None:
            out += ['na_nlink=%s' % repr(self.na_nlink)]
        if self.na_uid is not None:
            out += ['na_uid=%s' % repr(self.na_uid)]
        if self.na_gid is not None:
            out += ['na_gid=%s' % repr(self.na_gid)]
        if self.na_size is not None:
            out += ['na_size=%s' % repr(self.na_size)]
        if self.na_blocksize is not None:
            out += ['na_blocksize=%s' % repr(self.na_blocksize)]
        if self.na_rdev is not None:
            out += ['na_rdev=%s' % repr(self.na_rdev)]
        if self.na_blocks is not None:
            out += ['na_blocks=%s' % repr(self.na_blocks)]
        if self.na_fsid is not None:
            out += ['na_fsid=%s' % repr(self.na_fsid)]
        if self.na_nodeid is not None:
            out += ['na_nodeid=%s' % repr(self.na_nodeid)]
        if self.na_atime is not None:
            out += ['na_atime=%s' % repr(self.na_atime)]
        if self.na_mtime is not None:
            out += ['na_mtime=%s' % repr(self.na_mtime)]
        if self.na_ctime is not None:
            out += ['na_ctime=%s' % repr(self.na_ctime)]
        return 'nfsfattr(%s)' % ', '.join(out)
    __str__ = __repr__

class aclent:
    # XDR definition:
    # struct aclent {
    #     int type;
    #     uid id;
    #     o_mode perm;
    # };
    def __init__(self, type=None, id=None, perm=None):
        self.type = type
        self.id = id
        self.perm = perm

    def __repr__(self):
        out = []
        if self.type is not None:
            out += ['type=%s' % repr(self.type)]
        if self.id is not None:
            out += ['id=%s' % repr(self.id)]
        if self.perm is not None:
            out += ['perm=%s' % repr(self.perm)]
        return 'aclent(%s)' % ', '.join(out)
    __str__ = __repr__

class secattr:
    # XDR definition:
    # struct secattr {
    #     u_int mask;
    #     int aclcnt;
    #     aclent aclent<NFS_ACL_MAX_ENTRIES>;
    #     int dfaclcnt;
    #     aclent dfaclent<NFS_ACL_MAX_ENTRIES>;
    # };
    def __init__(self, mask=None, aclcnt=None, aclent=None, dfaclcnt=None, dfaclent=None):
        self.mask = mask
        self.aclcnt = aclcnt
        self.aclent = aclent
        self.dfaclcnt = dfaclcnt
        self.dfaclent = dfaclent

    def __repr__(self):
        out = []
        if self.mask is not None:
            out += ['mask=%s' % repr(self.mask)]
        if self.aclcnt is not None:
            out += ['aclcnt=%s' % repr(self.aclcnt)]
        if self.aclent is not None:
            out += ['aclent=%s' % repr(self.aclent)]
        if self.dfaclcnt is not None:
            out += ['dfaclcnt=%s' % repr(self.dfaclcnt)]
        if self.dfaclent is not None:
            out += ['dfaclent=%s' % repr(self.dfaclent)]
        return 'secattr(%s)' % ', '.join(out)
    __str__ = __repr__

class GETACL2args:
    # XDR definition:
    # struct GETACL2args {
    #     nfs_fh fh;
    #     u_int mask;
    # };
    def __init__(self, fh=None, mask=None):
        self.fh = fh
        self.mask = mask

    def __getattr__(self, attr):
        return getattr(self.fh, attr)

    def __repr__(self):
        out = []
        if self.fh is not None:
            out += ['fh=%s' % repr(self.fh)]
        if self.mask is not None:
            out += ['mask=%s' % repr(self.mask)]
        return 'GETACL2args(%s)' % ', '.join(out)
    __str__ = __repr__

class GETACL2resok:
    # XDR definition:
    # struct GETACL2resok {
    #     nfsfattr attr;
    #     secattr acl;
    # };
    def __init__(self, attr=None, acl=None):
        self.attr = attr
        self.acl = acl

    def __repr__(self):
        out = []
        if self.attr is not None:
            out += ['attr=%s' % repr(self.attr)]
        if self.acl is not None:
            out += ['acl=%s' % repr(self.acl)]
        return 'GETACL2resok(%s)' % ', '.join(out)
    __str__ = __repr__

class GETACL2res:
    # XDR definition:
    # union GETACL2res switch(nfsstat status) {
    #     case ACL2_OK:
    #         GETACL2resok resok;
    #     default:
    #         void;
    # };
    def __init__(self, status=None, resok=None):
        self.status = status
        self.resok = resok

    switch = property(lambda s: {const.ACL2_OK:s.resok,}.get(s.status, None))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.status is not None:
            out += ['status=%s' % repr(self.status)]
        if self.resok is not None:
            out += ['resok=%s' % repr(self.resok)]
        return 'GETACL2res(%s)' % ', '.join(out)
    __str__ = __repr__

class SETACL2args:
    # XDR definition:
    # struct SETACL2args {
    #     nfs_fh fh;
    #     secattr acl;
    # };
    def __init__(self, fh=None, acl=None):
        self.fh = fh
        self.acl = acl

    def __repr__(self):
        out = []
        if self.fh is not None:
            out += ['fh=%s' % repr(self.fh)]
        if self.acl is not None:
            out += ['acl=%s' % repr(self.acl)]
        return 'SETACL2args(%s)' % ', '.join(out)
    __str__ = __repr__

class SETACL2resok:
    # XDR definition:
    # struct SETACL2resok {
    #     nfsfattr attr;
    # };
    def __init__(self, attr=None):
        self.attr = attr

    def __getattr__(self, attr):
        return getattr(self.attr, attr)

    def __repr__(self):
        out = []
        if self.attr is not None:
            out += ['attr=%s' % repr(self.attr)]
        return 'SETACL2resok(%s)' % ', '.join(out)
    __str__ = __repr__

class SETACL2res:
    # XDR definition:
    # union SETACL2res switch(nfsstat status) {
    #     case ACL2_OK:
    #         SETACL2resok resok;
    #     default:
    #         void;
    # };
    def __init__(self, status=None, resok=None):
        self.status = status
        self.resok = resok

    switch = property(lambda s: {const.ACL2_OK:s.resok,}.get(s.status, None))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.status is not None:
            out += ['status=%s' % repr(self.status)]
        if self.resok is not None:
            out += ['resok=%s' % repr(self.resok)]
        return 'SETACL2res(%s)' % ', '.join(out)
    __str__ = __repr__

class GETATTR2args:
    # XDR definition:
    # struct GETATTR2args {
    #     nfs_fh fh;
    # };
    def __init__(self, fh=None):
        self.fh = fh

    def __getattr__(self, attr):
        return getattr(self.fh, attr)

    def __repr__(self):
        out = []
        if self.fh is not None:
            out += ['fh=%s' % repr(self.fh)]
        return 'GETATTR2args(%s)' % ', '.join(out)
    __str__ = __repr__

class GETATTR2resok:
    # XDR definition:
    # struct GETATTR2resok {
    #     nfs_fh attr;
    # };
    def __init__(self, attr=None):
        self.attr = attr

    def __getattr__(self, attr):
        return getattr(self.attr, attr)

    def __repr__(self):
        out = []
        if self.attr is not None:
            out += ['attr=%s' % repr(self.attr)]
        return 'GETATTR2resok(%s)' % ', '.join(out)
    __str__ = __repr__

class GETATTR2res:
    # XDR definition:
    # union GETATTR2res switch(nfsstat status) {
    #     case ACL2_OK:
    #         GETATTR2resok resok;
    #     default:
    #         void;
    # };
    def __init__(self, status=None, resok=None):
        self.status = status
        self.resok = resok

    switch = property(lambda s: {const.ACL2_OK:s.resok,}.get(s.status, None))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.status is not None:
            out += ['status=%s' % repr(self.status)]
        if self.resok is not None:
            out += ['resok=%s' % repr(self.resok)]
        return 'GETATTR2res(%s)' % ', '.join(out)
    __str__ = __repr__

class ACCESS2args:
    # XDR definition:
    # struct ACCESS2args {
    #     nfs_fh fh;
    #     uint32 access;
    # };
    def __init__(self, fh=None, access=None):
        self.fh = fh
        self.access = access

    def __getattr__(self, attr):
        return getattr(self.fh, attr)

    def __repr__(self):
        out = []
        if self.fh is not None:
            out += ['fh=%s' % repr(self.fh)]
        if self.access is not None:
            out += ['access=%s' % repr(self.access)]
        return 'ACCESS2args(%s)' % ', '.join(out)
    __str__ = __repr__

class ACCESS2resok:
    # XDR definition:
    # struct ACCESS2resok {
    #     nfsfattr attr;
    #     uint32 access;
    # };
    def __init__(self, attr=None, access=None):
        self.attr = attr
        self.access = access

    def __getattr__(self, attr):
        return getattr(self.attr, attr)

    def __repr__(self):
        out = []
        if self.attr is not None:
            out += ['attr=%s' % repr(self.attr)]
        if self.access is not None:
            out += ['access=%s' % repr(self.access)]
        return 'ACCESS2resok(%s)' % ', '.join(out)
    __str__ = __repr__

class ACCESS2res:
    # XDR definition:
    # union ACCESS2res switch(nfsstat status) {
    #     case ACL2_OK:
    #         ACCESS2resok resok;
    #     default:
    #         void;
    # };
    def __init__(self, status=None, resok=None):
        self.status = status
        self.resok = resok

    switch = property(lambda s: {const.ACL2_OK:s.resok,}.get(s.status, None))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.status is not None:
            out += ['status=%s' % repr(self.status)]
        if self.resok is not None:
            out += ['resok=%s' % repr(self.resok)]
        return 'ACCESS2res(%s)' % ', '.join(out)
    __str__ = __repr__

class GETXATTRDIR2args:
    # XDR definition:
    # struct GETXATTRDIR2args {
    #     nfs_fh fh;
    #     bool create;
    # };
    def __init__(self, fh=None, create=None):
        self.fh = fh
        self.create = create

    def __getattr__(self, attr):
        return getattr(self.fh, attr)

    def __repr__(self):
        out = []
        if self.fh is not None:
            out += ['fh=%s' % repr(self.fh)]
        if self.create is not None:
            out += ['create=%s' % repr(self.create)]
        return 'GETXATTRDIR2args(%s)' % ', '.join(out)
    __str__ = __repr__

class GETXATTRDIR2resok:
    # XDR definition:
    # struct GETXATTRDIR2resok {
    #     nfs_fh fh;
    #     nfsfattr attr;
    # };
    def __init__(self, fh=None, attr=None):
        self.fh = fh
        self.attr = attr

    def __repr__(self):
        out = []
        if self.fh is not None:
            out += ['fh=%s' % repr(self.fh)]
        if self.attr is not None:
            out += ['attr=%s' % repr(self.attr)]
        return 'GETXATTRDIR2resok(%s)' % ', '.join(out)
    __str__ = __repr__

class GETXATTRDIR2res:
    # XDR definition:
    # union GETXATTRDIR2res switch(nfsstat status) {
    #     case ACL2_OK:
    #         GETXATTRDIR2resok resok;
    #     default:
    #         void;
    # };
    def __init__(self, status=None, resok=None):
        self.status = status
        self.resok = resok

    switch = property(lambda s: {const.ACL2_OK:s.resok,}.get(s.status, None))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.status is not None:
            out += ['status=%s' % repr(self.status)]
        if self.resok is not None:
            out += ['resok=%s' % repr(self.resok)]
        return 'GETXATTRDIR2res(%s)' % ', '.join(out)
    __str__ = __repr__

class GETACL3args:
    # XDR definition:
    # struct GETACL3args {
    #     nfs_fh3 fh;
    #     u_int mask;
    # };
    def __init__(self, fh=None, mask=None):
        self.fh = fh
        self.mask = mask

    def __getattr__(self, attr):
        return getattr(self.fh, attr)

    def __repr__(self):
        out = []
        if self.fh is not None:
            out += ['fh=%s' % repr(self.fh)]
        if self.mask is not None:
            out += ['mask=%s' % repr(self.mask)]
        return 'GETACL3args(%s)' % ', '.join(out)
    __str__ = __repr__

class GETACL3resok:
    # XDR definition:
    # struct GETACL3resok {
    #     post_op_attr attr;
    #     secattr acl;
    # };
    def __init__(self, attr=None, acl=None):
        self.attr = attr
        self.acl = acl

    def __repr__(self):
        out = []
        if self.attr is not None:
            out += ['attr=%s' % repr(self.attr)]
        if self.acl is not None:
            out += ['acl=%s' % repr(self.acl)]
        return 'GETACL3resok(%s)' % ', '.join(out)
    __str__ = __repr__

class GETACL3resfail:
    # XDR definition:
    # struct GETACL3resfail {
    #     post_op_attr attr;
    # };
    def __init__(self, attr=None):
        self.attr = attr

    def __getattr__(self, attr):
        return getattr(self.attr, attr)

    def __repr__(self):
        out = []
        if self.attr is not None:
            out += ['attr=%s' % repr(self.attr)]
        return 'GETACL3resfail(%s)' % ', '.join(out)
    __str__ = __repr__

class GETACL3res:
    # XDR definition:
    # union GETACL3res switch(nfsstat3 status) {
    #     case ACL3_OK:
    #         GETACL3resok resok;
    #     default:
    #         GETACL3resfail resfail;
    # };
    def __init__(self, status=None, resok=None, resfail=None):
        self.status = status
        self.resok = resok
        self.resfail = resfail

    switch = property(lambda s: {const.ACL3_OK:s.resok,}.get(s.status, s.resfail))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.status is not None:
            out += ['status=%s' % const.nfsstat3.get(self.status, self.status)]
        if self.resok is not None:
            out += ['resok=%s' % repr(self.resok)]
        if self.resfail is not None:
            out += ['resfail=%s' % repr(self.resfail)]
        return 'GETACL3res(%s)' % ', '.join(out)
    __str__ = __repr__

class SETACL3args:
    # XDR definition:
    # struct SETACL3args {
    #     nfs_fh3 fh;
    #     secattr acl;
    # };
    def __init__(self, fh=None, acl=None):
        self.fh = fh
        self.acl = acl

    def __repr__(self):
        out = []
        if self.fh is not None:
            out += ['fh=%s' % repr(self.fh)]
        if self.acl is not None:
            out += ['acl=%s' % repr(self.acl)]
        return 'SETACL3args(%s)' % ', '.join(out)
    __str__ = __repr__

class SETACL3resok:
    # XDR definition:
    # struct SETACL3resok {
    #     post_op_attr attr;
    # };
    def __init__(self, attr=None):
        self.attr = attr

    def __getattr__(self, attr):
        return getattr(self.attr, attr)

    def __repr__(self):
        out = []
        if self.attr is not None:
            out += ['attr=%s' % repr(self.attr)]
        return 'SETACL3resok(%s)' % ', '.join(out)
    __str__ = __repr__

class SETACL3resfail:
    # XDR definition:
    # struct SETACL3resfail {
    #     post_op_attr attr;
    # };
    def __init__(self, attr=None):
        self.attr = attr

    def __getattr__(self, attr):
        return getattr(self.attr, attr)

    def __repr__(self):
        out = []
        if self.attr is not None:
            out += ['attr=%s' % repr(self.attr)]
        return 'SETACL3resfail(%s)' % ', '.join(out)
    __str__ = __repr__

class SETACL3res:
    # XDR definition:
    # union SETACL3res switch(nfsstat3 status) {
    #     case ACL3_OK:
    #         SETACL3resok resok;
    #     default:
    #         SETACL3resfail resfail;
    # };
    def __init__(self, status=None, resok=None, resfail=None):
        self.status = status
        self.resok = resok
        self.resfail = resfail

    switch = property(lambda s: {const.ACL3_OK:s.resok,}.get(s.status, s.resfail))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.status is not None:
            out += ['status=%s' % const.nfsstat3.get(self.status, self.status)]
        if self.resok is not None:
            out += ['resok=%s' % repr(self.resok)]
        if self.resfail is not None:
            out += ['resfail=%s' % repr(self.resfail)]
        return 'SETACL3res(%s)' % ', '.join(out)
    __str__ = __repr__

class GETXATTRDIR3args:
    # XDR definition:
    # struct GETXATTRDIR3args {
    #     nfs_fh3 fh;
    #     bool create;
    # };
    def __init__(self, fh=None, create=None):
        self.fh = fh
        self.create = create

    def __getattr__(self, attr):
        return getattr(self.fh, attr)

    def __repr__(self):
        out = []
        if self.fh is not None:
            out += ['fh=%s' % repr(self.fh)]
        if self.create is not None:
            out += ['create=%s' % repr(self.create)]
        return 'GETXATTRDIR3args(%s)' % ', '.join(out)
    __str__ = __repr__

class GETXATTRDIR3resok:
    # XDR definition:
    # struct GETXATTRDIR3resok {
    #     nfs_fh3 fh;
    #     post_op_attr attr;
    # };
    def __init__(self, fh=None, attr=None):
        self.fh = fh
        self.attr = attr

    def __repr__(self):
        out = []
        if self.fh is not None:
            out += ['fh=%s' % repr(self.fh)]
        if self.attr is not None:
            out += ['attr=%s' % repr(self.attr)]
        return 'GETXATTRDIR3resok(%s)' % ', '.join(out)
    __str__ = __repr__

class GETXATTRDIR3res:
    # XDR definition:
    # union GETXATTRDIR3res switch(nfsstat3 status) {
    #     case ACL3_OK:
    #         GETXATTRDIR3resok resok;
    #     default:
    #         void;
    # };
    def __init__(self, status=None, resok=None):
        self.status = status
        self.resok = resok

    switch = property(lambda s: {const.ACL3_OK:s.resok,}.get(s.status, None))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.status is not None:
            out += ['status=%s' % const.nfsstat3.get(self.status, self.status)]
        if self.resok is not None:
            out += ['resok=%s' % repr(self.resok)]
        return 'GETXATTRDIR3res(%s)' % ', '.join(out)
    __str__ = __repr__

class GETACL4args:
    # XDR definition:
    # struct GETACL4args {
    #     nfs_fh4 fh;
    #     u_int mask;
    # };
    def __init__(self, fh=None, mask=None):
        self.fh = fh
        self.mask = mask

    def __getattr__(self, attr):
        return getattr(self.fh, attr)

    def __repr__(self):
        out = []
        if self.fh is not None:
            out += ['fh=%s' % repr(self.fh)]
        if self.mask is not None:
            out += ['mask=%s' % repr(self.mask)]
        return 'GETACL4args(%s)' % ', '.join(out)
    __str__ = __repr__

class GETACL4resok:
    # XDR definition:
    # struct GETACL4resok {
    #     post_op_attr attr;
    #     secattr acl;
    # };
    def __init__(self, attr=None, acl=None):
        self.attr = attr
        self.acl = acl

    def __repr__(self):
        out = []
        if self.attr is not None:
            out += ['attr=%s' % repr(self.attr)]
        if self.acl is not None:
            out += ['acl=%s' % repr(self.acl)]
        return 'GETACL4resok(%s)' % ', '.join(out)
    __str__ = __repr__

class GETACL4resfail:
    # XDR definition:
    # struct GETACL4resfail {
    #     post_op_attr attr;
    # };
    def __init__(self, attr=None):
        self.attr = attr

    def __getattr__(self, attr):
        return getattr(self.attr, attr)

    def __repr__(self):
        out = []
        if self.attr is not None:
            out += ['attr=%s' % repr(self.attr)]
        return 'GETACL4resfail(%s)' % ', '.join(out)
    __str__ = __repr__

class GETACL4res:
    # XDR definition:
    # union GETACL4res switch(nfsstat3 status) {
    #     case ACL4_OK:
    #         GETACL4resok resok;
    #     default:
    #         GETACL4resfail resfail;
    # };
    def __init__(self, status=None, resok=None, resfail=None):
        self.status = status
        self.resok = resok
        self.resfail = resfail

    switch = property(lambda s: {const.ACL4_OK:s.resok,}.get(s.status, s.resfail))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.status is not None:
            out += ['status=%s' % const.nfsstat3.get(self.status, self.status)]
        if self.resok is not None:
            out += ['resok=%s' % repr(self.resok)]
        if self.resfail is not None:
            out += ['resfail=%s' % repr(self.resfail)]
        return 'GETACL4res(%s)' % ', '.join(out)
    __str__ = __repr__

class SETACL4args:
    # XDR definition:
    # struct SETACL4args {
    #     nfs_fh4 fh;
    #     secattr acl;
    # };
    def __init__(self, fh=None, acl=None):
        self.fh = fh
        self.acl = acl

    def __repr__(self):
        out = []
        if self.fh is not None:
            out += ['fh=%s' % repr(self.fh)]
        if self.acl is not None:
            out += ['acl=%s' % repr(self.acl)]
        return 'SETACL4args(%s)' % ', '.join(out)
    __str__ = __repr__

class SETACL4resok:
    # XDR definition:
    # struct SETACL4resok {
    #     post_op_attr attr;
    # };
    def __init__(self, attr=None):
        self.attr = attr

    def __getattr__(self, attr):
        return getattr(self.attr, attr)

    def __repr__(self):
        out = []
        if self.attr is not None:
            out += ['attr=%s' % repr(self.attr)]
        return 'SETACL4resok(%s)' % ', '.join(out)
    __str__ = __repr__

class SETACL4resfail:
    # XDR definition:
    # struct SETACL4resfail {
    #     post_op_attr attr;
    # };
    def __init__(self, attr=None):
        self.attr = attr

    def __getattr__(self, attr):
        return getattr(self.attr, attr)

    def __repr__(self):
        out = []
        if self.attr is not None:
            out += ['attr=%s' % repr(self.attr)]
        return 'SETACL4resfail(%s)' % ', '.join(out)
    __str__ = __repr__

class SETACL4res:
    # XDR definition:
    # union SETACL4res switch(nfsstat3 status) {
    #     case ACL4_OK:
    #         SETACL4resok resok;
    #     default:
    #         SETACL4resfail resfail;
    # };
    def __init__(self, status=None, resok=None, resfail=None):
        self.status = status
        self.resok = resok
        self.resfail = resfail

    switch = property(lambda s: {const.ACL4_OK:s.resok,}.get(s.status, s.resfail))

    def __getattr__(self, attr):
        return getattr(self.switch, attr)

    def __repr__(self):
        out = []
        if self.status is not None:
            out += ['status=%s' % const.nfsstat3.get(self.status, self.status)]
        if self.resok is not None:
            out += ['resok=%s' % repr(self.resok)]
        if self.resfail is not None:
            out += ['resfail=%s' % repr(self.resfail)]
        return 'SETACL4res(%s)' % ', '.join(out)
    __str__ = __repr__

