# Generated by rpcgen.py from nfs3.x on Wed Jun 24 11:38:48 2026
import nfs3_const as const
import nfs3_type as types
import xdrlib
from xdrlib import Error as XDRError

class nullclass(object):
    pass

def _str2bytes(data):
    # Python 3: xdrlib requires bytes for opaque/string fields.  Python 2 str
    # values were raw bytes, so latin-1 reproduces those byte values exactly
    # (and is identical to ASCII/utf-8 for plain text).
    if isinstance(data, str):
        return data.encode('latin-1')
    return data

class NFS3Packer(xdrlib.Packer):
    def __init__(self, check_enum=True, check_array=True):
        xdrlib.Packer.__init__(self)
        self.check_enum = check_enum
        self.check_array = check_array

    pack_int = xdrlib.Packer.pack_int
    pack_long = xdrlib.Packer.pack_int
    pack_uint = xdrlib.Packer.pack_uint
    pack_unsigned = xdrlib.Packer.pack_uint
    pack_hyper = xdrlib.Packer.pack_hyper
    pack_uhyper = xdrlib.Packer.pack_uhyper
    pack_float = xdrlib.Packer.pack_float
    pack_double = xdrlib.Packer.pack_double
    pack_quadruple = xdrlib.Packer.pack_double
    pack_bool = xdrlib.Packer.pack_bool
    def pack_opaque(self, data):
        return xdrlib.Packer.pack_opaque(self, _str2bytes(data))
    def pack_string(self, data):
        return xdrlib.Packer.pack_string(self, _str2bytes(data))
    def pack_fopaque(self, n, data):
        return xdrlib.Packer.pack_fopaque(self, n, _str2bytes(data))
    def pack_fstring(self, n, data):
        return xdrlib.Packer.pack_fstring(self, n, _str2bytes(data))
    pack_uint64 = pack_uhyper

    pack_int64 = pack_hyper

    pack_uint32 = pack_uint

    pack_int32 = pack_int

    def pack_filename3(self, data):
        if hasattr(self, 'filter_filename3'):
            data = getattr(self, 'filter_filename3')(data)
        self.pack_string(data)

    def pack_nfspath3(self, data):
        if hasattr(self, 'filter_nfspath3'):
            data = getattr(self, 'filter_nfspath3')(data)
        self.pack_string(data)

    def pack_cookieverf3(self, data):
        if hasattr(self, 'filter_cookieverf3'):
            data = getattr(self, 'filter_cookieverf3')(data)
        self.pack_fopaque(const.NFS3_COOKIEVERFSIZE, data)

    def pack_createverf3(self, data):
        if hasattr(self, 'filter_createverf3'):
            data = getattr(self, 'filter_createverf3')(data)
        self.pack_fopaque(const.NFS3_CREATEVERFSIZE, data)

    def pack_writeverf3(self, data):
        if hasattr(self, 'filter_writeverf3'):
            data = getattr(self, 'filter_writeverf3')(data)
        self.pack_fopaque(const.NFS3_WRITEVERFSIZE, data)

    def pack_nfsstat3(self, data):
        if hasattr(self, 'filter_nfsstat3'):
            data = getattr(self, 'filter_nfsstat3')(data)
        if self.check_enum and data not in [const.NFS3_OK, const.NFS3ERR_PERM, const.NFS3ERR_NOENT, const.NFS3ERR_IO, const.NFS3ERR_NXIO, const.NFS3ERR_ACCES, const.NFS3ERR_EXIST, const.NFS3ERR_XDEV, const.NFS3ERR_NODEV, const.NFS3ERR_NOTDIR, const.NFS3ERR_ISDIR, const.NFS3ERR_INVAL, const.NFS3ERR_FBIG, const.NFS3ERR_NOSPC, const.NFS3ERR_ROFS, const.NFS3ERR_MLINK, const.NFS3ERR_NAMETOOLONG, const.NFS3ERR_NOTEMPTY, const.NFS3ERR_DQUOT, const.NFS3ERR_STALE, const.NFS3ERR_REMOTE, const.NFS3ERR_BADHANDLE, const.NFS3ERR_NOT_SYNC, const.NFS3ERR_BAD_COOKIE, const.NFS3ERR_NOTSUPP, const.NFS3ERR_TOOSMALL, const.NFS3ERR_SERVERFAULT, const.NFS3ERR_BADTYPE, const.NFS3ERR_JUKEBOX, const.NFS3ERR_FPRINTNOTFOUND, const.NFS3ERR_ABORTED]:
            raise XDRError('value=%s not in enum nfsstat3' % data)
        self.pack_int(data)

    def pack_ftype3(self, data):
        if hasattr(self, 'filter_ftype3'):
            data = getattr(self, 'filter_ftype3')(data)
        if self.check_enum and data not in [const.NF3REG, const.NF3DIR, const.NF3BLK, const.NF3CHR, const.NF3LNK, const.NF3SOCK, const.NF3FIFO]:
            raise XDRError('value=%s not in enum ftype3' % data)
        self.pack_int(data)

    def pack_specdata3(self, data):
        if hasattr(self, 'filter_specdata3'):
            data = getattr(self, 'filter_specdata3')(data)
        if data.major is None:
            raise TypeError('data.major == None')
        self.pack_uint32(data.major)
        if data.minor is None:
            raise TypeError('data.minor == None')
        self.pack_uint32(data.minor)

    def pack_nfs_fh3(self, data):
        if hasattr(self, 'filter_nfs_fh3'):
            data = getattr(self, 'filter_nfs_fh3')(data)
        if data.data is None:
            raise TypeError('data.data == None')
        if len(data.data) > const.NFS3_FHSIZE and self.check_array:
            raise XDRError('array length too long for data.data')
        self.pack_opaque(data.data)

    def pack_nfstime3(self, data):
        if hasattr(self, 'filter_nfstime3'):
            data = getattr(self, 'filter_nfstime3')(data)
        if data.seconds is None:
            raise TypeError('data.seconds == None')
        self.pack_uint32(data.seconds)
        if data.nseconds is None:
            raise TypeError('data.nseconds == None')
        self.pack_uint32(data.nseconds)

    def pack_fattr3(self, data):
        if hasattr(self, 'filter_fattr3'):
            data = getattr(self, 'filter_fattr3')(data)
        if data.type is None:
            raise TypeError('data.type == None')
        self.pack_ftype3(data.type)
        if data.mode is None:
            raise TypeError('data.mode == None')
        self.pack_uint32(data.mode)
        if data.nlink is None:
            raise TypeError('data.nlink == None')
        self.pack_uint32(data.nlink)
        if data.uid is None:
            raise TypeError('data.uid == None')
        self.pack_uint32(data.uid)
        if data.gid is None:
            raise TypeError('data.gid == None')
        self.pack_uint32(data.gid)
        if data.size is None:
            raise TypeError('data.size == None')
        self.pack_uint64(data.size)
        if data.used is None:
            raise TypeError('data.used == None')
        self.pack_uint64(data.used)
        if data.rdev is None:
            raise TypeError('data.rdev == None')
        self.pack_specdata3(data.rdev)
        if data.fsid is None:
            raise TypeError('data.fsid == None')
        self.pack_uint64(data.fsid)
        if data.fileid is None:
            raise TypeError('data.fileid == None')
        self.pack_uint64(data.fileid)
        if data.atime is None:
            raise TypeError('data.atime == None')
        self.pack_nfstime3(data.atime)
        if data.mtime is None:
            raise TypeError('data.mtime == None')
        self.pack_nfstime3(data.mtime)
        if data.ctime is None:
            raise TypeError('data.ctime == None')
        self.pack_nfstime3(data.ctime)

    def pack_post_op_attr(self, data):
        if hasattr(self, 'filter_post_op_attr'):
            data = getattr(self, 'filter_post_op_attr')(data)
        if data.present is None:
            raise TypeError('data.present == None')
        self.pack_bool(data.present)
        if data.present == const.TRUE:
            if data.attributes is None:
                raise TypeError('data.attributes == None')
            self.pack_fattr3(data.attributes)
        elif data.present == const.FALSE:
            pass
        else:
            raise XDRError('bad switch=%s' % data.present)

    def pack_wcc_attr(self, data):
        if hasattr(self, 'filter_wcc_attr'):
            data = getattr(self, 'filter_wcc_attr')(data)
        if data.size is None:
            raise TypeError('data.size == None')
        self.pack_uint64(data.size)
        if data.mtime is None:
            raise TypeError('data.mtime == None')
        self.pack_nfstime3(data.mtime)
        if data.ctime is None:
            raise TypeError('data.ctime == None')
        self.pack_nfstime3(data.ctime)

    def pack_pre_op_attr(self, data):
        if hasattr(self, 'filter_pre_op_attr'):
            data = getattr(self, 'filter_pre_op_attr')(data)
        if data.present is None:
            raise TypeError('data.present == None')
        self.pack_bool(data.present)
        if data.present == const.TRUE:
            if data.attributes is None:
                raise TypeError('data.attributes == None')
            self.pack_wcc_attr(data.attributes)
        elif data.present == const.FALSE:
            pass
        else:
            raise XDRError('bad switch=%s' % data.present)

    def pack_wcc_data(self, data):
        if hasattr(self, 'filter_wcc_data'):
            data = getattr(self, 'filter_wcc_data')(data)
        if data.before is None:
            raise TypeError('data.before == None')
        self.pack_pre_op_attr(data.before)
        if data.after is None:
            raise TypeError('data.after == None')
        self.pack_post_op_attr(data.after)

    def pack_post_op_fh3(self, data):
        if hasattr(self, 'filter_post_op_fh3'):
            data = getattr(self, 'filter_post_op_fh3')(data)
        if data.present is None:
            raise TypeError('data.present == None')
        self.pack_bool(data.present)
        if data.present == const.TRUE:
            if data.handle is None:
                raise TypeError('data.handle == None')
            self.pack_nfs_fh3(data.handle)
        elif data.present == const.FALSE:
            pass
        else:
            raise XDRError('bad switch=%s' % data.present)

    def pack_set_uint32(self, data):
        if hasattr(self, 'filter_set_uint32'):
            data = getattr(self, 'filter_set_uint32')(data)
        if data.set is None:
            raise TypeError('data.set == None')
        self.pack_bool(data.set)
        if data.set == const.TRUE:
            if data.val is None:
                raise TypeError('data.val == None')
            self.pack_uint32(data.val)
        else:
            pass

    def pack_set_uint64(self, data):
        if hasattr(self, 'filter_set_uint64'):
            data = getattr(self, 'filter_set_uint64')(data)
        if data.set is None:
            raise TypeError('data.set == None')
        self.pack_bool(data.set)
        if data.set == const.TRUE:
            if data.val is None:
                raise TypeError('data.val == None')
            self.pack_uint64(data.val)
        else:
            pass

    def pack_time_how(self, data):
        if hasattr(self, 'filter_time_how'):
            data = getattr(self, 'filter_time_how')(data)
        if self.check_enum and data not in [const.DONT_CHANGE, const.SET_TO_SERVER_TIME, const.SET_TO_CLIENT_TIME]:
            raise XDRError('value=%s not in enum time_how' % data)
        self.pack_int(data)

    def pack_set_time(self, data):
        if hasattr(self, 'filter_set_time'):
            data = getattr(self, 'filter_set_time')(data)
        if data.set is None:
            raise TypeError('data.set == None')
        self.pack_time_how(data.set)
        if data.set == const.SET_TO_CLIENT_TIME:
            if data.time is None:
                raise TypeError('data.time == None')
            self.pack_nfstime3(data.time)
        else:
            pass

    def pack_sattr3(self, data):
        if hasattr(self, 'filter_sattr3'):
            data = getattr(self, 'filter_sattr3')(data)
        if data.mode is None:
            raise TypeError('data.mode == None')
        self.pack_set_uint32(data.mode)
        if data.uid is None:
            raise TypeError('data.uid == None')
        self.pack_set_uint32(data.uid)
        if data.gid is None:
            raise TypeError('data.gid == None')
        self.pack_set_uint32(data.gid)
        if data.size is None:
            raise TypeError('data.size == None')
        self.pack_set_uint64(data.size)
        if data.atime is None:
            raise TypeError('data.atime == None')
        self.pack_set_time(data.atime)
        if data.mtime is None:
            raise TypeError('data.mtime == None')
        self.pack_set_time(data.mtime)

    def pack_diropargs3(self, data):
        if hasattr(self, 'filter_diropargs3'):
            data = getattr(self, 'filter_diropargs3')(data)
        if data.dir is None:
            raise TypeError('data.dir == None')
        self.pack_nfs_fh3(data.dir)
        if data.name is None:
            raise TypeError('data.name == None')
        self.pack_filename3(data.name)

    def pack_diropres3ok(self, data):
        if hasattr(self, 'filter_diropres3ok'):
            data = getattr(self, 'filter_diropres3ok')(data)
        if data.obj is None:
            raise TypeError('data.obj == None')
        self.pack_post_op_fh3(data.obj)
        if data.obj_attributes is None:
            raise TypeError('data.obj_attributes == None')
        self.pack_post_op_attr(data.obj_attributes)
        if data.dir_wcc is None:
            raise TypeError('data.dir_wcc == None')
        self.pack_wcc_data(data.dir_wcc)

    def pack_diropres3(self, data):
        if hasattr(self, 'filter_diropres3'):
            data = getattr(self, 'filter_diropres3')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat3(data.status)
        if data.status == const.NFS3_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_diropres3ok(data.resok)
        else:
            if data.resfail is None:
                raise TypeError('data.resfail == None')
            self.pack_wcc_data(data.resfail)

    def pack_wccstat3(self, data):
        if hasattr(self, 'filter_wccstat3'):
            data = getattr(self, 'filter_wccstat3')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat3(data.status)
        if data.status == -1:
            pass
        else:
            if data.wcc is None:
                raise TypeError('data.wcc == None')
            self.pack_wcc_data(data.wcc)

    def pack_getattr3res(self, data):
        if hasattr(self, 'filter_getattr3res'):
            data = getattr(self, 'filter_getattr3res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat3(data.status)
        if data.status == const.NFS3_OK:
            if data.attributes is None:
                raise TypeError('data.attributes == None')
            self.pack_fattr3(data.attributes)
        else:
            pass

    def pack_sattrguard3(self, data):
        if hasattr(self, 'filter_sattrguard3'):
            data = getattr(self, 'filter_sattrguard3')(data)
        if data.check is None:
            raise TypeError('data.check == None')
        self.pack_bool(data.check)
        if data.check == const.TRUE:
            if data.ctime is None:
                raise TypeError('data.ctime == None')
            self.pack_nfstime3(data.ctime)
        elif data.check == const.FALSE:
            pass
        else:
            raise XDRError('bad switch=%s' % data.check)

    def pack_setattr3args(self, data):
        if hasattr(self, 'filter_setattr3args'):
            data = getattr(self, 'filter_setattr3args')(data)
        if data.object is None:
            raise TypeError('data.object == None')
        self.pack_nfs_fh3(data.object)
        if data.new_attributes is None:
            raise TypeError('data.new_attributes == None')
        self.pack_sattr3(data.new_attributes)
        if data.guard is None:
            raise TypeError('data.guard == None')
        self.pack_sattrguard3(data.guard)

    def pack_lookup3resok(self, data):
        if hasattr(self, 'filter_lookup3resok'):
            data = getattr(self, 'filter_lookup3resok')(data)
        if data.object is None:
            raise TypeError('data.object == None')
        self.pack_nfs_fh3(data.object)
        if data.obj_attributes is None:
            raise TypeError('data.obj_attributes == None')
        self.pack_post_op_attr(data.obj_attributes)
        if data.dir_attributes is None:
            raise TypeError('data.dir_attributes == None')
        self.pack_post_op_attr(data.dir_attributes)

    def pack_lookup3res(self, data):
        if hasattr(self, 'filter_lookup3res'):
            data = getattr(self, 'filter_lookup3res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat3(data.status)
        if data.status == const.NFS3_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_lookup3resok(data.resok)
        else:
            if data.resfail is None:
                raise TypeError('data.resfail == None')
            self.pack_post_op_attr(data.resfail)

    def pack_access3args(self, data):
        if hasattr(self, 'filter_access3args'):
            data = getattr(self, 'filter_access3args')(data)
        if data.object is None:
            raise TypeError('data.object == None')
        self.pack_nfs_fh3(data.object)
        if data.access is None:
            raise TypeError('data.access == None')
        self.pack_uint32(data.access)

    def pack_access3resok(self, data):
        if hasattr(self, 'filter_access3resok'):
            data = getattr(self, 'filter_access3resok')(data)
        if data.obj_attributes is None:
            raise TypeError('data.obj_attributes == None')
        self.pack_post_op_attr(data.obj_attributes)
        if data.access is None:
            raise TypeError('data.access == None')
        self.pack_uint32(data.access)

    def pack_access3res(self, data):
        if hasattr(self, 'filter_access3res'):
            data = getattr(self, 'filter_access3res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat3(data.status)
        if data.status == const.NFS3_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_access3resok(data.resok)
        else:
            if data.resfail is None:
                raise TypeError('data.resfail == None')
            self.pack_post_op_attr(data.resfail)

    def pack_readlink3resok(self, data):
        if hasattr(self, 'filter_readlink3resok'):
            data = getattr(self, 'filter_readlink3resok')(data)
        if data.symlink_attributes is None:
            raise TypeError('data.symlink_attributes == None')
        self.pack_post_op_attr(data.symlink_attributes)
        if data.data is None:
            raise TypeError('data.data == None')
        self.pack_nfspath3(data.data)

    def pack_readlink3res(self, data):
        if hasattr(self, 'filter_readlink3res'):
            data = getattr(self, 'filter_readlink3res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat3(data.status)
        if data.status == const.NFS3_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_readlink3resok(data.resok)
        else:
            if data.resfail is None:
                raise TypeError('data.resfail == None')
            self.pack_post_op_attr(data.resfail)

    def pack_read3args(self, data):
        if hasattr(self, 'filter_read3args'):
            data = getattr(self, 'filter_read3args')(data)
        if data.file is None:
            raise TypeError('data.file == None')
        self.pack_nfs_fh3(data.file)
        if data.offset is None:
            raise TypeError('data.offset == None')
        self.pack_uint64(data.offset)
        if data.count is None:
            raise TypeError('data.count == None')
        self.pack_uint32(data.count)

    def pack_read3resok(self, data):
        if hasattr(self, 'filter_read3resok'):
            data = getattr(self, 'filter_read3resok')(data)
        if data.file_attributes is None:
            raise TypeError('data.file_attributes == None')
        self.pack_post_op_attr(data.file_attributes)
        if data.count is None:
            raise TypeError('data.count == None')
        self.pack_uint32(data.count)
        if data.eof is None:
            raise TypeError('data.eof == None')
        self.pack_bool(data.eof)
        if data.data is None:
            raise TypeError('data.data == None')
        self.pack_opaque(data.data)

    def pack_read3res(self, data):
        if hasattr(self, 'filter_read3res'):
            data = getattr(self, 'filter_read3res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat3(data.status)
        if data.status == const.NFS3_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_read3resok(data.resok)
        else:
            if data.resfail is None:
                raise TypeError('data.resfail == None')
            self.pack_post_op_attr(data.resfail)

    def pack_stable_how(self, data):
        if hasattr(self, 'filter_stable_how'):
            data = getattr(self, 'filter_stable_how')(data)
        if self.check_enum and data not in [const.UNSTABLE, const.DATA_SYNC, const.FILE_SYNC]:
            raise XDRError('value=%s not in enum stable_how' % data)
        self.pack_int(data)

    def pack_write3args(self, data):
        if hasattr(self, 'filter_write3args'):
            data = getattr(self, 'filter_write3args')(data)
        if data.file is None:
            raise TypeError('data.file == None')
        self.pack_nfs_fh3(data.file)
        if data.offset is None:
            raise TypeError('data.offset == None')
        self.pack_uint64(data.offset)
        if data.count is None:
            raise TypeError('data.count == None')
        self.pack_uint32(data.count)
        if data.stable is None:
            raise TypeError('data.stable == None')
        self.pack_stable_how(data.stable)
        if data.data is None:
            raise TypeError('data.data == None')
        self.pack_opaque(data.data)

    def pack_write3resok(self, data):
        if hasattr(self, 'filter_write3resok'):
            data = getattr(self, 'filter_write3resok')(data)
        if data.file_wcc is None:
            raise TypeError('data.file_wcc == None')
        self.pack_wcc_data(data.file_wcc)
        if data.count is None:
            raise TypeError('data.count == None')
        self.pack_uint32(data.count)
        if data.committed is None:
            raise TypeError('data.committed == None')
        self.pack_stable_how(data.committed)
        if data.verf is None:
            raise TypeError('data.verf == None')
        self.pack_writeverf3(data.verf)

    def pack_write3res(self, data):
        if hasattr(self, 'filter_write3res'):
            data = getattr(self, 'filter_write3res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat3(data.status)
        if data.status == const.NFS3_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_write3resok(data.resok)
        else:
            if data.resfail is None:
                raise TypeError('data.resfail == None')
            self.pack_wcc_data(data.resfail)

    def pack_createmode3(self, data):
        if hasattr(self, 'filter_createmode3'):
            data = getattr(self, 'filter_createmode3')(data)
        if self.check_enum and data not in [const.UNCHECKED, const.GUARDED, const.EXCLUSIVE]:
            raise XDRError('value=%s not in enum createmode3' % data)
        self.pack_int(data)

    def pack_createhow3(self, data):
        if hasattr(self, 'filter_createhow3'):
            data = getattr(self, 'filter_createhow3')(data)
        if data.mode is None:
            raise TypeError('data.mode == None')
        self.pack_createmode3(data.mode)
        if data.mode == const.UNCHECKED or data.mode == const.GUARDED:
            if data.obj_attributes is None:
                raise TypeError('data.obj_attributes == None')
            self.pack_sattr3(data.obj_attributes)
        elif data.mode == const.EXCLUSIVE:
            if data.verf is None:
                raise TypeError('data.verf == None')
            self.pack_createverf3(data.verf)
        else:
            raise XDRError('bad switch=%s' % data.mode)

    def pack_create3args(self, data):
        if hasattr(self, 'filter_create3args'):
            data = getattr(self, 'filter_create3args')(data)
        if data.where is None:
            raise TypeError('data.where == None')
        self.pack_diropargs3(data.where)
        if data.how is None:
            raise TypeError('data.how == None')
        self.pack_createhow3(data.how)

    def pack_mkdir3args(self, data):
        if hasattr(self, 'filter_mkdir3args'):
            data = getattr(self, 'filter_mkdir3args')(data)
        if data.where is None:
            raise TypeError('data.where == None')
        self.pack_diropargs3(data.where)
        if data.attributes is None:
            raise TypeError('data.attributes == None')
        self.pack_sattr3(data.attributes)

    def pack_symlinkdata3(self, data):
        if hasattr(self, 'filter_symlinkdata3'):
            data = getattr(self, 'filter_symlinkdata3')(data)
        if data.symlink_attributes is None:
            raise TypeError('data.symlink_attributes == None')
        self.pack_sattr3(data.symlink_attributes)
        if data.symlink_data is None:
            raise TypeError('data.symlink_data == None')
        self.pack_nfspath3(data.symlink_data)

    def pack_symlink3args(self, data):
        if hasattr(self, 'filter_symlink3args'):
            data = getattr(self, 'filter_symlink3args')(data)
        if data.where is None:
            raise TypeError('data.where == None')
        self.pack_diropargs3(data.where)
        if data.symlink is None:
            raise TypeError('data.symlink == None')
        self.pack_symlinkdata3(data.symlink)

    def pack_devicedata3(self, data):
        if hasattr(self, 'filter_devicedata3'):
            data = getattr(self, 'filter_devicedata3')(data)
        if data.dev_attributes is None:
            raise TypeError('data.dev_attributes == None')
        self.pack_sattr3(data.dev_attributes)
        if data.spec is None:
            raise TypeError('data.spec == None')
        self.pack_specdata3(data.spec)

    def pack_mknoddata3(self, data):
        if hasattr(self, 'filter_mknoddata3'):
            data = getattr(self, 'filter_mknoddata3')(data)
        if data.type is None:
            raise TypeError('data.type == None')
        self.pack_ftype3(data.type)
        if data.type == const.NF3CHR or data.type == const.NF3BLK:
            if data.device is None:
                raise TypeError('data.device == None')
            self.pack_devicedata3(data.device)
        elif data.type == const.NF3SOCK or data.type == const.NF3FIFO:
            if data.pipe_attributes is None:
                raise TypeError('data.pipe_attributes == None')
            self.pack_sattr3(data.pipe_attributes)
        else:
            pass

    def pack_mknod3args(self, data):
        if hasattr(self, 'filter_mknod3args'):
            data = getattr(self, 'filter_mknod3args')(data)
        if data.where is None:
            raise TypeError('data.where == None')
        self.pack_diropargs3(data.where)
        if data.what is None:
            raise TypeError('data.what == None')
        self.pack_mknoddata3(data.what)

    def pack_rename3args(self, data):
        if hasattr(self, 'filter_rename3args'):
            data = getattr(self, 'filter_rename3args')(data)
        if data.from_dir is None:
            raise TypeError('data.from_dir == None')
        self.pack_diropargs3(data.from_dir)
        if data.to_dir is None:
            raise TypeError('data.to_dir == None')
        self.pack_diropargs3(data.to_dir)

    def pack_rename3wcc(self, data):
        if hasattr(self, 'filter_rename3wcc'):
            data = getattr(self, 'filter_rename3wcc')(data)
        if data.fromdir_wcc is None:
            raise TypeError('data.fromdir_wcc == None')
        self.pack_wcc_data(data.fromdir_wcc)
        if data.todir_wcc is None:
            raise TypeError('data.todir_wcc == None')
        self.pack_wcc_data(data.todir_wcc)

    def pack_rename3res(self, data):
        if hasattr(self, 'filter_rename3res'):
            data = getattr(self, 'filter_rename3res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat3(data.status)
        if data.status == -1:
            pass
        else:
            if data.res is None:
                raise TypeError('data.res == None')
            self.pack_rename3wcc(data.res)

    def pack_link3args(self, data):
        if hasattr(self, 'filter_link3args'):
            data = getattr(self, 'filter_link3args')(data)
        if data.file is None:
            raise TypeError('data.file == None')
        self.pack_nfs_fh3(data.file)
        if data.link is None:
            raise TypeError('data.link == None')
        self.pack_diropargs3(data.link)

    def pack_link3wcc(self, data):
        if hasattr(self, 'filter_link3wcc'):
            data = getattr(self, 'filter_link3wcc')(data)
        if data.file_attributes is None:
            raise TypeError('data.file_attributes == None')
        self.pack_post_op_attr(data.file_attributes)
        if data.linkdir_wcc is None:
            raise TypeError('data.linkdir_wcc == None')
        self.pack_wcc_data(data.linkdir_wcc)

    def pack_link3res(self, data):
        if hasattr(self, 'filter_link3res'):
            data = getattr(self, 'filter_link3res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat3(data.status)
        if data.status == -1:
            pass
        else:
            if data.res is None:
                raise TypeError('data.res == None')
            self.pack_link3wcc(data.res)

    def pack_readdir3args(self, data):
        if hasattr(self, 'filter_readdir3args'):
            data = getattr(self, 'filter_readdir3args')(data)
        if data.dir is None:
            raise TypeError('data.dir == None')
        self.pack_nfs_fh3(data.dir)
        if data.cookie is None:
            raise TypeError('data.cookie == None')
        self.pack_uint64(data.cookie)
        if data.cookieverf is None:
            raise TypeError('data.cookieverf == None')
        self.pack_cookieverf3(data.cookieverf)
        if data.count is None:
            raise TypeError('data.count == None')
        self.pack_uint32(data.count)

    def pack_entry3(self, data):
        if hasattr(self, 'filter_entry3'):
            data = getattr(self, 'filter_entry3')(data)
        if data.fileid is None:
            raise TypeError('data.fileid == None')
        self.pack_uint64(data.fileid)
        if data.name is None:
            raise TypeError('data.name == None')
        self.pack_filename3(data.name)
        if data.cookie is None:
            raise TypeError('data.cookie == None')
        self.pack_uint64(data.cookie)
        if data.nextentry is None:
            raise TypeError('data.nextentry == None')
        if len(data.nextentry) > 1 and self.check_array:
            raise XDRError('array length too long for data.nextentry')
        self.pack_array(data.nextentry, self.pack_entry3)

    def pack_dirlist3(self, data):
        if hasattr(self, 'filter_dirlist3'):
            data = getattr(self, 'filter_dirlist3')(data)
        if data.entries is None:
            raise TypeError('data.entries == None')
        if len(data.entries) > 1 and self.check_array:
            raise XDRError('array length too long for data.entries')
        self.pack_array(data.entries, self.pack_entry3)
        if data.eof is None:
            raise TypeError('data.eof == None')
        self.pack_bool(data.eof)

    def pack_readdir3resok(self, data):
        if hasattr(self, 'filter_readdir3resok'):
            data = getattr(self, 'filter_readdir3resok')(data)
        if data.dir_attributes is None:
            raise TypeError('data.dir_attributes == None')
        self.pack_post_op_attr(data.dir_attributes)
        if data.cookieverf is None:
            raise TypeError('data.cookieverf == None')
        self.pack_cookieverf3(data.cookieverf)
        if data.reply is None:
            raise TypeError('data.reply == None')
        self.pack_dirlist3(data.reply)

    def pack_readdir3res(self, data):
        if hasattr(self, 'filter_readdir3res'):
            data = getattr(self, 'filter_readdir3res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat3(data.status)
        if data.status == const.NFS3_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_readdir3resok(data.resok)
        else:
            if data.resfail is None:
                raise TypeError('data.resfail == None')
            self.pack_post_op_attr(data.resfail)

    def pack_readdirplus3args(self, data):
        if hasattr(self, 'filter_readdirplus3args'):
            data = getattr(self, 'filter_readdirplus3args')(data)
        if data.dir is None:
            raise TypeError('data.dir == None')
        self.pack_nfs_fh3(data.dir)
        if data.cookie is None:
            raise TypeError('data.cookie == None')
        self.pack_uint64(data.cookie)
        if data.cookieverf is None:
            raise TypeError('data.cookieverf == None')
        self.pack_cookieverf3(data.cookieverf)
        if data.dircount is None:
            raise TypeError('data.dircount == None')
        self.pack_uint32(data.dircount)
        if data.maxcount is None:
            raise TypeError('data.maxcount == None')
        self.pack_uint32(data.maxcount)

    def pack_entryplus3(self, data):
        if hasattr(self, 'filter_entryplus3'):
            data = getattr(self, 'filter_entryplus3')(data)
        if data.fileid is None:
            raise TypeError('data.fileid == None')
        self.pack_uint64(data.fileid)
        if data.name is None:
            raise TypeError('data.name == None')
        self.pack_filename3(data.name)
        if data.cookie is None:
            raise TypeError('data.cookie == None')
        self.pack_uint64(data.cookie)
        if data.name_attributes is None:
            raise TypeError('data.name_attributes == None')
        self.pack_post_op_attr(data.name_attributes)
        if data.name_handle is None:
            raise TypeError('data.name_handle == None')
        self.pack_post_op_fh3(data.name_handle)
        if data.nextentry is None:
            raise TypeError('data.nextentry == None')
        if len(data.nextentry) > 1 and self.check_array:
            raise XDRError('array length too long for data.nextentry')
        self.pack_array(data.nextentry, self.pack_entryplus3)

    def pack_dirlistplus3(self, data):
        if hasattr(self, 'filter_dirlistplus3'):
            data = getattr(self, 'filter_dirlistplus3')(data)
        if data.entries is None:
            raise TypeError('data.entries == None')
        if len(data.entries) > 1 and self.check_array:
            raise XDRError('array length too long for data.entries')
        self.pack_array(data.entries, self.pack_entryplus3)
        if data.eof is None:
            raise TypeError('data.eof == None')
        self.pack_bool(data.eof)

    def pack_readdirplus3resok(self, data):
        if hasattr(self, 'filter_readdirplus3resok'):
            data = getattr(self, 'filter_readdirplus3resok')(data)
        if data.dir_attributes is None:
            raise TypeError('data.dir_attributes == None')
        self.pack_post_op_attr(data.dir_attributes)
        if data.cookieverf is None:
            raise TypeError('data.cookieverf == None')
        self.pack_cookieverf3(data.cookieverf)
        if data.reply is None:
            raise TypeError('data.reply == None')
        self.pack_dirlistplus3(data.reply)

    def pack_readdirplus3res(self, data):
        if hasattr(self, 'filter_readdirplus3res'):
            data = getattr(self, 'filter_readdirplus3res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat3(data.status)
        if data.status == const.NFS3_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_readdirplus3resok(data.resok)
        else:
            if data.resfail is None:
                raise TypeError('data.resfail == None')
            self.pack_post_op_attr(data.resfail)

    def pack_fsstat3resok(self, data):
        if hasattr(self, 'filter_fsstat3resok'):
            data = getattr(self, 'filter_fsstat3resok')(data)
        if data.obj_attributes is None:
            raise TypeError('data.obj_attributes == None')
        self.pack_post_op_attr(data.obj_attributes)
        if data.tbytes is None:
            raise TypeError('data.tbytes == None')
        self.pack_uint64(data.tbytes)
        if data.fbytes is None:
            raise TypeError('data.fbytes == None')
        self.pack_uint64(data.fbytes)
        if data.abytes is None:
            raise TypeError('data.abytes == None')
        self.pack_uint64(data.abytes)
        if data.tfiles is None:
            raise TypeError('data.tfiles == None')
        self.pack_uint64(data.tfiles)
        if data.ffiles is None:
            raise TypeError('data.ffiles == None')
        self.pack_uint64(data.ffiles)
        if data.afiles is None:
            raise TypeError('data.afiles == None')
        self.pack_uint64(data.afiles)
        if data.invarsec is None:
            raise TypeError('data.invarsec == None')
        self.pack_uint32(data.invarsec)

    def pack_fsstat3res(self, data):
        if hasattr(self, 'filter_fsstat3res'):
            data = getattr(self, 'filter_fsstat3res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat3(data.status)
        if data.status == const.NFS3_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_fsstat3resok(data.resok)
        else:
            if data.resfail is None:
                raise TypeError('data.resfail == None')
            self.pack_post_op_attr(data.resfail)

    def pack_fsinfo3resok(self, data):
        if hasattr(self, 'filter_fsinfo3resok'):
            data = getattr(self, 'filter_fsinfo3resok')(data)
        if data.obj_attributes is None:
            raise TypeError('data.obj_attributes == None')
        self.pack_post_op_attr(data.obj_attributes)
        if data.rtmax is None:
            raise TypeError('data.rtmax == None')
        self.pack_uint32(data.rtmax)
        if data.rtpref is None:
            raise TypeError('data.rtpref == None')
        self.pack_uint32(data.rtpref)
        if data.rtmult is None:
            raise TypeError('data.rtmult == None')
        self.pack_uint32(data.rtmult)
        if data.wtmax is None:
            raise TypeError('data.wtmax == None')
        self.pack_uint32(data.wtmax)
        if data.wtpref is None:
            raise TypeError('data.wtpref == None')
        self.pack_uint32(data.wtpref)
        if data.wtmult is None:
            raise TypeError('data.wtmult == None')
        self.pack_uint32(data.wtmult)
        if data.dtpref is None:
            raise TypeError('data.dtpref == None')
        self.pack_uint32(data.dtpref)
        if data.maxfilesize is None:
            raise TypeError('data.maxfilesize == None')
        self.pack_uint64(data.maxfilesize)
        if data.time_delta is None:
            raise TypeError('data.time_delta == None')
        self.pack_nfstime3(data.time_delta)
        if data.properties is None:
            raise TypeError('data.properties == None')
        self.pack_uint32(data.properties)

    def pack_fsinfo3res(self, data):
        if hasattr(self, 'filter_fsinfo3res'):
            data = getattr(self, 'filter_fsinfo3res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat3(data.status)
        if data.status == const.NFS3_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_fsinfo3resok(data.resok)
        else:
            if data.resfail is None:
                raise TypeError('data.resfail == None')
            self.pack_post_op_attr(data.resfail)

    def pack_pathconf3resok(self, data):
        if hasattr(self, 'filter_pathconf3resok'):
            data = getattr(self, 'filter_pathconf3resok')(data)
        if data.obj_attributes is None:
            raise TypeError('data.obj_attributes == None')
        self.pack_post_op_attr(data.obj_attributes)
        if data.linkmax is None:
            raise TypeError('data.linkmax == None')
        self.pack_uint32(data.linkmax)
        if data.name_max is None:
            raise TypeError('data.name_max == None')
        self.pack_uint32(data.name_max)
        if data.no_trunc is None:
            raise TypeError('data.no_trunc == None')
        self.pack_bool(data.no_trunc)
        if data.chown_restricted is None:
            raise TypeError('data.chown_restricted == None')
        self.pack_bool(data.chown_restricted)
        if data.case_insensitive is None:
            raise TypeError('data.case_insensitive == None')
        self.pack_bool(data.case_insensitive)
        if data.case_preserving is None:
            raise TypeError('data.case_preserving == None')
        self.pack_bool(data.case_preserving)

    def pack_pathconf3res(self, data):
        if hasattr(self, 'filter_pathconf3res'):
            data = getattr(self, 'filter_pathconf3res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat3(data.status)
        if data.status == const.NFS3_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_pathconf3resok(data.resok)
        else:
            if data.resfail is None:
                raise TypeError('data.resfail == None')
            self.pack_post_op_attr(data.resfail)

    def pack_commit3args(self, data):
        if hasattr(self, 'filter_commit3args'):
            data = getattr(self, 'filter_commit3args')(data)
        if data.file is None:
            raise TypeError('data.file == None')
        self.pack_nfs_fh3(data.file)
        if data.offset is None:
            raise TypeError('data.offset == None')
        self.pack_uint64(data.offset)
        if data.count is None:
            raise TypeError('data.count == None')
        self.pack_uint32(data.count)

    def pack_commit3resok(self, data):
        if hasattr(self, 'filter_commit3resok'):
            data = getattr(self, 'filter_commit3resok')(data)
        if data.file_wcc is None:
            raise TypeError('data.file_wcc == None')
        self.pack_wcc_data(data.file_wcc)
        if data.verf is None:
            raise TypeError('data.verf == None')
        self.pack_writeverf3(data.verf)

    def pack_commit3res(self, data):
        if hasattr(self, 'filter_commit3res'):
            data = getattr(self, 'filter_commit3res')(data)
        if data.status is None:
            raise TypeError('data.status == None')
        self.pack_nfsstat3(data.status)
        if data.status == const.NFS3_OK:
            if data.resok is None:
                raise TypeError('data.resok == None')
            self.pack_commit3resok(data.resok)
        else:
            if data.resfail is None:
                raise TypeError('data.resfail == None')
            self.pack_wcc_data(data.resfail)

    def pack_setaclargs(self, data):
        if hasattr(self, 'filter_setaclargs'):
            data = getattr(self, 'filter_setaclargs')(data)
        if data.dargs is None:
            raise TypeError('data.dargs == None')
        self.pack_diropargs3(data.dargs)
        if data.wargs is None:
            raise TypeError('data.wargs == None')
        self.pack_write3args(data.wargs)

class NFS3Unpacker(xdrlib.Unpacker):
    def __init__(self, data, check_enum=True, check_array=True):
        xdrlib.Unpacker.__init__(self, data)
        self.check_enum = check_enum
        self.check_array = check_array

    unpack_int = xdrlib.Unpacker.unpack_int
    unpack_long = xdrlib.Unpacker.unpack_int
    unpack_uint = xdrlib.Unpacker.unpack_uint
    unpack_unsigned = xdrlib.Unpacker.unpack_uint
    unpack_hyper = xdrlib.Unpacker.unpack_hyper
    unpack_uhyper = xdrlib.Unpacker.unpack_uhyper
    unpack_float = xdrlib.Unpacker.unpack_float
    unpack_double = xdrlib.Unpacker.unpack_double
    unpack_quadruple = xdrlib.Unpacker.unpack_double
    unpack_bool = xdrlib.Unpacker.unpack_bool
    unpack_opaque = xdrlib.Unpacker.unpack_opaque
    unpack_string = xdrlib.Unpacker.unpack_string
    unpack_uint64 = unpack_uhyper

    unpack_int64 = unpack_hyper

    unpack_uint32 = unpack_uint

    unpack_int32 = unpack_int

    def unpack_filename3(self):
        data = self.unpack_string()
        if hasattr(self, 'filter_filename3'):
            data = getattr(self, 'filter_filename3')(data)
        return data

    def unpack_nfspath3(self):
        data = self.unpack_string()
        if hasattr(self, 'filter_nfspath3'):
            data = getattr(self, 'filter_nfspath3')(data)
        return data

    def unpack_cookieverf3(self):
        data = self.unpack_fopaque(const.NFS3_COOKIEVERFSIZE)
        if hasattr(self, 'filter_cookieverf3'):
            data = getattr(self, 'filter_cookieverf3')(data)
        return data

    def unpack_createverf3(self):
        data = self.unpack_fopaque(const.NFS3_CREATEVERFSIZE)
        if hasattr(self, 'filter_createverf3'):
            data = getattr(self, 'filter_createverf3')(data)
        return data

    def unpack_writeverf3(self):
        data = self.unpack_fopaque(const.NFS3_WRITEVERFSIZE)
        if hasattr(self, 'filter_writeverf3'):
            data = getattr(self, 'filter_writeverf3')(data)
        return data

    def unpack_nfsstat3(self):
        data = self.unpack_int()
        if self.check_enum and data not in [const.NFS3_OK, const.NFS3ERR_PERM, const.NFS3ERR_NOENT, const.NFS3ERR_IO, const.NFS3ERR_NXIO, const.NFS3ERR_ACCES, const.NFS3ERR_EXIST, const.NFS3ERR_XDEV, const.NFS3ERR_NODEV, const.NFS3ERR_NOTDIR, const.NFS3ERR_ISDIR, const.NFS3ERR_INVAL, const.NFS3ERR_FBIG, const.NFS3ERR_NOSPC, const.NFS3ERR_ROFS, const.NFS3ERR_MLINK, const.NFS3ERR_NAMETOOLONG, const.NFS3ERR_NOTEMPTY, const.NFS3ERR_DQUOT, const.NFS3ERR_STALE, const.NFS3ERR_REMOTE, const.NFS3ERR_BADHANDLE, const.NFS3ERR_NOT_SYNC, const.NFS3ERR_BAD_COOKIE, const.NFS3ERR_NOTSUPP, const.NFS3ERR_TOOSMALL, const.NFS3ERR_SERVERFAULT, const.NFS3ERR_BADTYPE, const.NFS3ERR_JUKEBOX, const.NFS3ERR_FPRINTNOTFOUND, const.NFS3ERR_ABORTED]:
            raise XDRError('value=%s not in enum nfsstat3' % data)
        if hasattr(self, 'filter_nfsstat3'):
            data = getattr(self, 'filter_nfsstat3')(data)
        return data

    def unpack_ftype3(self):
        data = self.unpack_int()
        if self.check_enum and data not in [const.NF3REG, const.NF3DIR, const.NF3BLK, const.NF3CHR, const.NF3LNK, const.NF3SOCK, const.NF3FIFO]:
            raise XDRError('value=%s not in enum ftype3' % data)
        if hasattr(self, 'filter_ftype3'):
            data = getattr(self, 'filter_ftype3')(data)
        return data

    def unpack_specdata3(self):
        data = types.specdata3()
        data.major = self.unpack_uint32()
        data.minor = self.unpack_uint32()
        if hasattr(self, 'filter_specdata3'):
            data = getattr(self, 'filter_specdata3')(data)
        return data

    def unpack_nfs_fh3(self):
        data = types.nfs_fh3()
        data.data = self.unpack_opaque()
        if len(data.data) > const.NFS3_FHSIZE and self.check_array:
            raise XDRError('array length too long for data.data')
        if hasattr(self, 'filter_nfs_fh3'):
            data = getattr(self, 'filter_nfs_fh3')(data)
        return data

    def unpack_nfstime3(self):
        data = types.nfstime3()
        data.seconds = self.unpack_uint32()
        data.nseconds = self.unpack_uint32()
        if hasattr(self, 'filter_nfstime3'):
            data = getattr(self, 'filter_nfstime3')(data)
        return data

    def unpack_fattr3(self):
        data = types.fattr3()
        data.type = self.unpack_ftype3()
        data.mode = self.unpack_uint32()
        data.nlink = self.unpack_uint32()
        data.uid = self.unpack_uint32()
        data.gid = self.unpack_uint32()
        data.size = self.unpack_uint64()
        data.used = self.unpack_uint64()
        data.rdev = self.unpack_specdata3()
        data.fsid = self.unpack_uint64()
        data.fileid = self.unpack_uint64()
        data.atime = self.unpack_nfstime3()
        data.mtime = self.unpack_nfstime3()
        data.ctime = self.unpack_nfstime3()
        if hasattr(self, 'filter_fattr3'):
            data = getattr(self, 'filter_fattr3')(data)
        return data

    def unpack_post_op_attr(self):
        data = types.post_op_attr()
        data.present = self.unpack_bool()
        if data.present == const.TRUE:
            data.attributes = self.unpack_fattr3()
        elif data.present == const.FALSE:
            pass
        else:
            raise XDRError('bad switch=%s' % data.present)
        if hasattr(self, 'filter_post_op_attr'):
            data = getattr(self, 'filter_post_op_attr')(data)
        return data

    def unpack_wcc_attr(self):
        data = types.wcc_attr()
        data.size = self.unpack_uint64()
        data.mtime = self.unpack_nfstime3()
        data.ctime = self.unpack_nfstime3()
        if hasattr(self, 'filter_wcc_attr'):
            data = getattr(self, 'filter_wcc_attr')(data)
        return data

    def unpack_pre_op_attr(self):
        data = types.pre_op_attr()
        data.present = self.unpack_bool()
        if data.present == const.TRUE:
            data.attributes = self.unpack_wcc_attr()
        elif data.present == const.FALSE:
            pass
        else:
            raise XDRError('bad switch=%s' % data.present)
        if hasattr(self, 'filter_pre_op_attr'):
            data = getattr(self, 'filter_pre_op_attr')(data)
        return data

    def unpack_wcc_data(self):
        data = types.wcc_data()
        data.before = self.unpack_pre_op_attr()
        data.after = self.unpack_post_op_attr()
        if hasattr(self, 'filter_wcc_data'):
            data = getattr(self, 'filter_wcc_data')(data)
        return data

    def unpack_post_op_fh3(self):
        data = types.post_op_fh3()
        data.present = self.unpack_bool()
        if data.present == const.TRUE:
            data.handle = self.unpack_nfs_fh3()
        elif data.present == const.FALSE:
            pass
        else:
            raise XDRError('bad switch=%s' % data.present)
        if hasattr(self, 'filter_post_op_fh3'):
            data = getattr(self, 'filter_post_op_fh3')(data)
        return data

    def unpack_set_uint32(self):
        data = types.set_uint32()
        data.set = self.unpack_bool()
        if data.set == const.TRUE:
            data.val = self.unpack_uint32()
        else:
            pass
        if hasattr(self, 'filter_set_uint32'):
            data = getattr(self, 'filter_set_uint32')(data)
        return data

    def unpack_set_uint64(self):
        data = types.set_uint64()
        data.set = self.unpack_bool()
        if data.set == const.TRUE:
            data.val = self.unpack_uint64()
        else:
            pass
        if hasattr(self, 'filter_set_uint64'):
            data = getattr(self, 'filter_set_uint64')(data)
        return data

    def unpack_time_how(self):
        data = self.unpack_int()
        if self.check_enum and data not in [const.DONT_CHANGE, const.SET_TO_SERVER_TIME, const.SET_TO_CLIENT_TIME]:
            raise XDRError('value=%s not in enum time_how' % data)
        if hasattr(self, 'filter_time_how'):
            data = getattr(self, 'filter_time_how')(data)
        return data

    def unpack_set_time(self):
        data = types.set_time()
        data.set = self.unpack_time_how()
        if data.set == const.SET_TO_CLIENT_TIME:
            data.time = self.unpack_nfstime3()
        else:
            pass
        if hasattr(self, 'filter_set_time'):
            data = getattr(self, 'filter_set_time')(data)
        return data

    def unpack_sattr3(self):
        data = types.sattr3()
        data.mode = self.unpack_set_uint32()
        data.uid = self.unpack_set_uint32()
        data.gid = self.unpack_set_uint32()
        data.size = self.unpack_set_uint64()
        data.atime = self.unpack_set_time()
        data.mtime = self.unpack_set_time()
        if hasattr(self, 'filter_sattr3'):
            data = getattr(self, 'filter_sattr3')(data)
        return data

    def unpack_diropargs3(self):
        data = types.diropargs3()
        data.dir = self.unpack_nfs_fh3()
        data.name = self.unpack_filename3()
        if hasattr(self, 'filter_diropargs3'):
            data = getattr(self, 'filter_diropargs3')(data)
        return data

    def unpack_diropres3ok(self):
        data = types.diropres3ok()
        data.obj = self.unpack_post_op_fh3()
        data.obj_attributes = self.unpack_post_op_attr()
        data.dir_wcc = self.unpack_wcc_data()
        if hasattr(self, 'filter_diropres3ok'):
            data = getattr(self, 'filter_diropres3ok')(data)
        return data

    def unpack_diropres3(self):
        data = types.diropres3()
        data.status = self.unpack_nfsstat3()
        if data.status == const.NFS3_OK:
            data.resok = self.unpack_diropres3ok()
        else:
            data.resfail = self.unpack_wcc_data()
        if hasattr(self, 'filter_diropres3'):
            data = getattr(self, 'filter_diropres3')(data)
        return data

    def unpack_wccstat3(self):
        data = types.wccstat3()
        data.status = self.unpack_nfsstat3()
        if data.status == -1:
            pass
        else:
            data.wcc = self.unpack_wcc_data()
        if hasattr(self, 'filter_wccstat3'):
            data = getattr(self, 'filter_wccstat3')(data)
        return data

    def unpack_getattr3res(self):
        data = types.getattr3res()
        data.status = self.unpack_nfsstat3()
        if data.status == const.NFS3_OK:
            data.attributes = self.unpack_fattr3()
        else:
            pass
        if hasattr(self, 'filter_getattr3res'):
            data = getattr(self, 'filter_getattr3res')(data)
        return data

    def unpack_sattrguard3(self):
        data = types.sattrguard3()
        data.check = self.unpack_bool()
        if data.check == const.TRUE:
            data.ctime = self.unpack_nfstime3()
        elif data.check == const.FALSE:
            pass
        else:
            raise XDRError('bad switch=%s' % data.check)
        if hasattr(self, 'filter_sattrguard3'):
            data = getattr(self, 'filter_sattrguard3')(data)
        return data

    def unpack_setattr3args(self):
        data = types.setattr3args()
        data.object = self.unpack_nfs_fh3()
        data.new_attributes = self.unpack_sattr3()
        data.guard = self.unpack_sattrguard3()
        if hasattr(self, 'filter_setattr3args'):
            data = getattr(self, 'filter_setattr3args')(data)
        return data

    def unpack_lookup3resok(self):
        data = types.lookup3resok()
        data.object = self.unpack_nfs_fh3()
        data.obj_attributes = self.unpack_post_op_attr()
        data.dir_attributes = self.unpack_post_op_attr()
        if hasattr(self, 'filter_lookup3resok'):
            data = getattr(self, 'filter_lookup3resok')(data)
        return data

    def unpack_lookup3res(self):
        data = types.lookup3res()
        data.status = self.unpack_nfsstat3()
        if data.status == const.NFS3_OK:
            data.resok = self.unpack_lookup3resok()
        else:
            data.resfail = self.unpack_post_op_attr()
        if hasattr(self, 'filter_lookup3res'):
            data = getattr(self, 'filter_lookup3res')(data)
        return data

    def unpack_access3args(self):
        data = types.access3args()
        data.object = self.unpack_nfs_fh3()
        data.access = self.unpack_uint32()
        if hasattr(self, 'filter_access3args'):
            data = getattr(self, 'filter_access3args')(data)
        return data

    def unpack_access3resok(self):
        data = types.access3resok()
        data.obj_attributes = self.unpack_post_op_attr()
        data.access = self.unpack_uint32()
        if hasattr(self, 'filter_access3resok'):
            data = getattr(self, 'filter_access3resok')(data)
        return data

    def unpack_access3res(self):
        data = types.access3res()
        data.status = self.unpack_nfsstat3()
        if data.status == const.NFS3_OK:
            data.resok = self.unpack_access3resok()
        else:
            data.resfail = self.unpack_post_op_attr()
        if hasattr(self, 'filter_access3res'):
            data = getattr(self, 'filter_access3res')(data)
        return data

    def unpack_readlink3resok(self):
        data = types.readlink3resok()
        data.symlink_attributes = self.unpack_post_op_attr()
        data.data = self.unpack_nfspath3()
        if hasattr(self, 'filter_readlink3resok'):
            data = getattr(self, 'filter_readlink3resok')(data)
        return data

    def unpack_readlink3res(self):
        data = types.readlink3res()
        data.status = self.unpack_nfsstat3()
        if data.status == const.NFS3_OK:
            data.resok = self.unpack_readlink3resok()
        else:
            data.resfail = self.unpack_post_op_attr()
        if hasattr(self, 'filter_readlink3res'):
            data = getattr(self, 'filter_readlink3res')(data)
        return data

    def unpack_read3args(self):
        data = types.read3args()
        data.file = self.unpack_nfs_fh3()
        data.offset = self.unpack_uint64()
        data.count = self.unpack_uint32()
        if hasattr(self, 'filter_read3args'):
            data = getattr(self, 'filter_read3args')(data)
        return data

    def unpack_read3resok(self):
        data = types.read3resok()
        data.file_attributes = self.unpack_post_op_attr()
        data.count = self.unpack_uint32()
        data.eof = self.unpack_bool()
        data.data = self.unpack_opaque()
        if hasattr(self, 'filter_read3resok'):
            data = getattr(self, 'filter_read3resok')(data)
        return data

    def unpack_read3res(self):
        data = types.read3res()
        data.status = self.unpack_nfsstat3()
        if data.status == const.NFS3_OK:
            data.resok = self.unpack_read3resok()
        else:
            data.resfail = self.unpack_post_op_attr()
        if hasattr(self, 'filter_read3res'):
            data = getattr(self, 'filter_read3res')(data)
        return data

    def unpack_stable_how(self):
        data = self.unpack_int()
        if self.check_enum and data not in [const.UNSTABLE, const.DATA_SYNC, const.FILE_SYNC]:
            raise XDRError('value=%s not in enum stable_how' % data)
        if hasattr(self, 'filter_stable_how'):
            data = getattr(self, 'filter_stable_how')(data)
        return data

    def unpack_write3args(self):
        data = types.write3args()
        data.file = self.unpack_nfs_fh3()
        data.offset = self.unpack_uint64()
        data.count = self.unpack_uint32()
        data.stable = self.unpack_stable_how()
        data.data = self.unpack_opaque()
        if hasattr(self, 'filter_write3args'):
            data = getattr(self, 'filter_write3args')(data)
        return data

    def unpack_write3resok(self):
        data = types.write3resok()
        data.file_wcc = self.unpack_wcc_data()
        data.count = self.unpack_uint32()
        data.committed = self.unpack_stable_how()
        data.verf = self.unpack_writeverf3()
        if hasattr(self, 'filter_write3resok'):
            data = getattr(self, 'filter_write3resok')(data)
        return data

    def unpack_write3res(self):
        data = types.write3res()
        data.status = self.unpack_nfsstat3()
        if data.status == const.NFS3_OK:
            data.resok = self.unpack_write3resok()
        else:
            data.resfail = self.unpack_wcc_data()
        if hasattr(self, 'filter_write3res'):
            data = getattr(self, 'filter_write3res')(data)
        return data

    def unpack_createmode3(self):
        data = self.unpack_int()
        if self.check_enum and data not in [const.UNCHECKED, const.GUARDED, const.EXCLUSIVE]:
            raise XDRError('value=%s not in enum createmode3' % data)
        if hasattr(self, 'filter_createmode3'):
            data = getattr(self, 'filter_createmode3')(data)
        return data

    def unpack_createhow3(self):
        data = types.createhow3()
        data.mode = self.unpack_createmode3()
        if data.mode == const.UNCHECKED or data.mode == const.GUARDED:
            data.obj_attributes = self.unpack_sattr3()
        elif data.mode == const.EXCLUSIVE:
            data.verf = self.unpack_createverf3()
        else:
            raise XDRError('bad switch=%s' % data.mode)
        if hasattr(self, 'filter_createhow3'):
            data = getattr(self, 'filter_createhow3')(data)
        return data

    def unpack_create3args(self):
        data = types.create3args()
        data.where = self.unpack_diropargs3()
        data.how = self.unpack_createhow3()
        if hasattr(self, 'filter_create3args'):
            data = getattr(self, 'filter_create3args')(data)
        return data

    def unpack_mkdir3args(self):
        data = types.mkdir3args()
        data.where = self.unpack_diropargs3()
        data.attributes = self.unpack_sattr3()
        if hasattr(self, 'filter_mkdir3args'):
            data = getattr(self, 'filter_mkdir3args')(data)
        return data

    def unpack_symlinkdata3(self):
        data = types.symlinkdata3()
        data.symlink_attributes = self.unpack_sattr3()
        data.symlink_data = self.unpack_nfspath3()
        if hasattr(self, 'filter_symlinkdata3'):
            data = getattr(self, 'filter_symlinkdata3')(data)
        return data

    def unpack_symlink3args(self):
        data = types.symlink3args()
        data.where = self.unpack_diropargs3()
        data.symlink = self.unpack_symlinkdata3()
        if hasattr(self, 'filter_symlink3args'):
            data = getattr(self, 'filter_symlink3args')(data)
        return data

    def unpack_devicedata3(self):
        data = types.devicedata3()
        data.dev_attributes = self.unpack_sattr3()
        data.spec = self.unpack_specdata3()
        if hasattr(self, 'filter_devicedata3'):
            data = getattr(self, 'filter_devicedata3')(data)
        return data

    def unpack_mknoddata3(self):
        data = types.mknoddata3()
        data.type = self.unpack_ftype3()
        if data.type == const.NF3CHR or data.type == const.NF3BLK:
            data.device = self.unpack_devicedata3()
        elif data.type == const.NF3SOCK or data.type == const.NF3FIFO:
            data.pipe_attributes = self.unpack_sattr3()
        else:
            pass
        if hasattr(self, 'filter_mknoddata3'):
            data = getattr(self, 'filter_mknoddata3')(data)
        return data

    def unpack_mknod3args(self):
        data = types.mknod3args()
        data.where = self.unpack_diropargs3()
        data.what = self.unpack_mknoddata3()
        if hasattr(self, 'filter_mknod3args'):
            data = getattr(self, 'filter_mknod3args')(data)
        return data

    def unpack_rename3args(self):
        data = types.rename3args()
        data.from_dir = self.unpack_diropargs3()
        data.to_dir = self.unpack_diropargs3()
        if hasattr(self, 'filter_rename3args'):
            data = getattr(self, 'filter_rename3args')(data)
        return data

    def unpack_rename3wcc(self):
        data = types.rename3wcc()
        data.fromdir_wcc = self.unpack_wcc_data()
        data.todir_wcc = self.unpack_wcc_data()
        if hasattr(self, 'filter_rename3wcc'):
            data = getattr(self, 'filter_rename3wcc')(data)
        return data

    def unpack_rename3res(self):
        data = types.rename3res()
        data.status = self.unpack_nfsstat3()
        if data.status == -1:
            pass
        else:
            data.res = self.unpack_rename3wcc()
        if hasattr(self, 'filter_rename3res'):
            data = getattr(self, 'filter_rename3res')(data)
        return data

    def unpack_link3args(self):
        data = types.link3args()
        data.file = self.unpack_nfs_fh3()
        data.link = self.unpack_diropargs3()
        if hasattr(self, 'filter_link3args'):
            data = getattr(self, 'filter_link3args')(data)
        return data

    def unpack_link3wcc(self):
        data = types.link3wcc()
        data.file_attributes = self.unpack_post_op_attr()
        data.linkdir_wcc = self.unpack_wcc_data()
        if hasattr(self, 'filter_link3wcc'):
            data = getattr(self, 'filter_link3wcc')(data)
        return data

    def unpack_link3res(self):
        data = types.link3res()
        data.status = self.unpack_nfsstat3()
        if data.status == -1:
            pass
        else:
            data.res = self.unpack_link3wcc()
        if hasattr(self, 'filter_link3res'):
            data = getattr(self, 'filter_link3res')(data)
        return data

    def unpack_readdir3args(self):
        data = types.readdir3args()
        data.dir = self.unpack_nfs_fh3()
        data.cookie = self.unpack_uint64()
        data.cookieverf = self.unpack_cookieverf3()
        data.count = self.unpack_uint32()
        if hasattr(self, 'filter_readdir3args'):
            data = getattr(self, 'filter_readdir3args')(data)
        return data

    def unpack_entry3(self):
        data = types.entry3()
        data.fileid = self.unpack_uint64()
        data.name = self.unpack_filename3()
        data.cookie = self.unpack_uint64()
        data.nextentry = self.unpack_array(self.unpack_entry3)
        if len(data.nextentry) > 1 and self.check_array:
            raise XDRError('array length too long for data.nextentry')
        if hasattr(self, 'filter_entry3'):
            data = getattr(self, 'filter_entry3')(data)
        return data

    def unpack_dirlist3(self):
        data = types.dirlist3()
        data.entries = self.unpack_array(self.unpack_entry3)
        if len(data.entries) > 1 and self.check_array:
            raise XDRError('array length too long for data.entries')
        data.eof = self.unpack_bool()
        if hasattr(self, 'filter_dirlist3'):
            data = getattr(self, 'filter_dirlist3')(data)
        return data

    def unpack_readdir3resok(self):
        data = types.readdir3resok()
        data.dir_attributes = self.unpack_post_op_attr()
        data.cookieverf = self.unpack_cookieverf3()
        data.reply = self.unpack_dirlist3()
        if hasattr(self, 'filter_readdir3resok'):
            data = getattr(self, 'filter_readdir3resok')(data)
        return data

    def unpack_readdir3res(self):
        data = types.readdir3res()
        data.status = self.unpack_nfsstat3()
        if data.status == const.NFS3_OK:
            data.resok = self.unpack_readdir3resok()
        else:
            data.resfail = self.unpack_post_op_attr()
        if hasattr(self, 'filter_readdir3res'):
            data = getattr(self, 'filter_readdir3res')(data)
        return data

    def unpack_readdirplus3args(self):
        data = types.readdirplus3args()
        data.dir = self.unpack_nfs_fh3()
        data.cookie = self.unpack_uint64()
        data.cookieverf = self.unpack_cookieverf3()
        data.dircount = self.unpack_uint32()
        data.maxcount = self.unpack_uint32()
        if hasattr(self, 'filter_readdirplus3args'):
            data = getattr(self, 'filter_readdirplus3args')(data)
        return data

    def unpack_entryplus3(self):
        data = types.entryplus3()
        data.fileid = self.unpack_uint64()
        data.name = self.unpack_filename3()
        data.cookie = self.unpack_uint64()
        data.name_attributes = self.unpack_post_op_attr()
        data.name_handle = self.unpack_post_op_fh3()
        data.nextentry = self.unpack_array(self.unpack_entryplus3)
        if len(data.nextentry) > 1 and self.check_array:
            raise XDRError('array length too long for data.nextentry')
        if hasattr(self, 'filter_entryplus3'):
            data = getattr(self, 'filter_entryplus3')(data)
        return data

    def unpack_dirlistplus3(self):
        data = types.dirlistplus3()
        data.entries = self.unpack_array(self.unpack_entryplus3)
        if len(data.entries) > 1 and self.check_array:
            raise XDRError('array length too long for data.entries')
        data.eof = self.unpack_bool()
        if hasattr(self, 'filter_dirlistplus3'):
            data = getattr(self, 'filter_dirlistplus3')(data)
        return data

    def unpack_readdirplus3resok(self):
        data = types.readdirplus3resok()
        data.dir_attributes = self.unpack_post_op_attr()
        data.cookieverf = self.unpack_cookieverf3()
        data.reply = self.unpack_dirlistplus3()
        if hasattr(self, 'filter_readdirplus3resok'):
            data = getattr(self, 'filter_readdirplus3resok')(data)
        return data

    def unpack_readdirplus3res(self):
        data = types.readdirplus3res()
        data.status = self.unpack_nfsstat3()
        if data.status == const.NFS3_OK:
            data.resok = self.unpack_readdirplus3resok()
        else:
            data.resfail = self.unpack_post_op_attr()
        if hasattr(self, 'filter_readdirplus3res'):
            data = getattr(self, 'filter_readdirplus3res')(data)
        return data

    def unpack_fsstat3resok(self):
        data = types.fsstat3resok()
        data.obj_attributes = self.unpack_post_op_attr()
        data.tbytes = self.unpack_uint64()
        data.fbytes = self.unpack_uint64()
        data.abytes = self.unpack_uint64()
        data.tfiles = self.unpack_uint64()
        data.ffiles = self.unpack_uint64()
        data.afiles = self.unpack_uint64()
        data.invarsec = self.unpack_uint32()
        if hasattr(self, 'filter_fsstat3resok'):
            data = getattr(self, 'filter_fsstat3resok')(data)
        return data

    def unpack_fsstat3res(self):
        data = types.fsstat3res()
        data.status = self.unpack_nfsstat3()
        if data.status == const.NFS3_OK:
            data.resok = self.unpack_fsstat3resok()
        else:
            data.resfail = self.unpack_post_op_attr()
        if hasattr(self, 'filter_fsstat3res'):
            data = getattr(self, 'filter_fsstat3res')(data)
        return data

    def unpack_fsinfo3resok(self):
        data = types.fsinfo3resok()
        data.obj_attributes = self.unpack_post_op_attr()
        data.rtmax = self.unpack_uint32()
        data.rtpref = self.unpack_uint32()
        data.rtmult = self.unpack_uint32()
        data.wtmax = self.unpack_uint32()
        data.wtpref = self.unpack_uint32()
        data.wtmult = self.unpack_uint32()
        data.dtpref = self.unpack_uint32()
        data.maxfilesize = self.unpack_uint64()
        data.time_delta = self.unpack_nfstime3()
        data.properties = self.unpack_uint32()
        if hasattr(self, 'filter_fsinfo3resok'):
            data = getattr(self, 'filter_fsinfo3resok')(data)
        return data

    def unpack_fsinfo3res(self):
        data = types.fsinfo3res()
        data.status = self.unpack_nfsstat3()
        if data.status == const.NFS3_OK:
            data.resok = self.unpack_fsinfo3resok()
        else:
            data.resfail = self.unpack_post_op_attr()
        if hasattr(self, 'filter_fsinfo3res'):
            data = getattr(self, 'filter_fsinfo3res')(data)
        return data

    def unpack_pathconf3resok(self):
        data = types.pathconf3resok()
        data.obj_attributes = self.unpack_post_op_attr()
        data.linkmax = self.unpack_uint32()
        data.name_max = self.unpack_uint32()
        data.no_trunc = self.unpack_bool()
        data.chown_restricted = self.unpack_bool()
        data.case_insensitive = self.unpack_bool()
        data.case_preserving = self.unpack_bool()
        if hasattr(self, 'filter_pathconf3resok'):
            data = getattr(self, 'filter_pathconf3resok')(data)
        return data

    def unpack_pathconf3res(self):
        data = types.pathconf3res()
        data.status = self.unpack_nfsstat3()
        if data.status == const.NFS3_OK:
            data.resok = self.unpack_pathconf3resok()
        else:
            data.resfail = self.unpack_post_op_attr()
        if hasattr(self, 'filter_pathconf3res'):
            data = getattr(self, 'filter_pathconf3res')(data)
        return data

    def unpack_commit3args(self):
        data = types.commit3args()
        data.file = self.unpack_nfs_fh3()
        data.offset = self.unpack_uint64()
        data.count = self.unpack_uint32()
        if hasattr(self, 'filter_commit3args'):
            data = getattr(self, 'filter_commit3args')(data)
        return data

    def unpack_commit3resok(self):
        data = types.commit3resok()
        data.file_wcc = self.unpack_wcc_data()
        data.verf = self.unpack_writeverf3()
        if hasattr(self, 'filter_commit3resok'):
            data = getattr(self, 'filter_commit3resok')(data)
        return data

    def unpack_commit3res(self):
        data = types.commit3res()
        data.status = self.unpack_nfsstat3()
        if data.status == const.NFS3_OK:
            data.resok = self.unpack_commit3resok()
        else:
            data.resfail = self.unpack_wcc_data()
        if hasattr(self, 'filter_commit3res'):
            data = getattr(self, 'filter_commit3res')(data)
        return data

    def unpack_setaclargs(self):
        data = types.setaclargs()
        data.dargs = self.unpack_diropargs3()
        data.wargs = self.unpack_write3args()
        if hasattr(self, 'filter_setaclargs'):
            data = getattr(self, 'filter_setaclargs')(data)
        return data

