# Generated by rpcgen.py from rpcb.x on Wed Jun 24 11:38:48 2026
import rpcb_const as const
class mapping:
    # XDR definition:
    # struct mapping {
    #     uint prog;
    #     uint vers;
    #     uint prot;
    #     uint port;
    # };
    def __init__(self, prog=None, vers=None, prot=None, port=None):
        self.prog = prog
        self.vers = vers
        self.prot = prot
        self.port = port

    def __repr__(self):
        out = []
        if self.prog is not None:
            out += ['prog=%s' % repr(self.prog)]
        if self.vers is not None:
            out += ['vers=%s' % repr(self.vers)]
        if self.prot is not None:
            out += ['prot=%s' % repr(self.prot)]
        if self.port is not None:
            out += ['port=%s' % repr(self.port)]
        return 'mapping(%s)' % ', '.join(out)
    __str__ = __repr__

class pmaplist:
    # XDR definition:
    # struct pmaplist {
    #     mapping map;
    #     pmaplist next<1>;
    # };
    def __init__(self, map=None, next=None):
        self.map = map
        self.next = next

    def __getattr__(self, attr):
        return getattr(self.map, attr)

    def __repr__(self):
        out = []
        if self.map is not None:
            out += ['map=%s' % repr(self.map)]
        if self.next is not None:
            out += ['next=%s' % repr(self.next)]
        return 'pmaplist(%s)' % ', '.join(out)
    __str__ = __repr__

class call_args:
    # XDR definition:
    # struct call_args {
    #     uint prog;
    #     uint vers;
    #     uint proc;
    #     opaque args<>;
    # };
    def __init__(self, prog=None, vers=None, proc=None, args=None):
        self.prog = prog
        self.vers = vers
        self.proc = proc
        self.args = args

    def __repr__(self):
        out = []
        if self.prog is not None:
            out += ['prog=%s' % repr(self.prog)]
        if self.vers is not None:
            out += ['vers=%s' % repr(self.vers)]
        if self.proc is not None:
            out += ['proc=%s' % repr(self.proc)]
        if self.args is not None:
            out += ['args=%s' % repr(self.args)]
        return 'call_args(%s)' % ', '.join(out)
    __str__ = __repr__

class call_result:
    # XDR definition:
    # struct call_result {
    #     uint port;
    #     opaque res<>;
    # };
    def __init__(self, port=None, res=None):
        self.port = port
        self.res = res

    def __repr__(self):
        out = []
        if self.port is not None:
            out += ['port=%s' % repr(self.port)]
        if self.res is not None:
            out += ['res=%s' % repr(self.res)]
        return 'call_result(%s)' % ', '.join(out)
    __str__ = __repr__

class rpcb:
    # XDR definition:
    # struct rpcb {
    #     uint r_prog;
    #     uint r_vers;
    #     string r_netid<>;
    #     string r_addr<>;
    #     string r_owner<>;
    # };
    def __init__(self, r_prog=None, r_vers=None, r_netid=None, r_addr=None, r_owner=None):
        self.r_prog = r_prog
        self.r_vers = r_vers
        self.r_netid = r_netid
        self.r_addr = r_addr
        self.r_owner = r_owner

    def __repr__(self):
        out = []
        if self.r_prog is not None:
            out += ['r_prog=%s' % repr(self.r_prog)]
        if self.r_vers is not None:
            out += ['r_vers=%s' % repr(self.r_vers)]
        if self.r_netid is not None:
            out += ['r_netid=%s' % repr(self.r_netid)]
        if self.r_addr is not None:
            out += ['r_addr=%s' % repr(self.r_addr)]
        if self.r_owner is not None:
            out += ['r_owner=%s' % repr(self.r_owner)]
        return 'rpcb(%s)' % ', '.join(out)
    __str__ = __repr__

class rp__list:
    # XDR definition:
    # struct rp__list {
    #     rpcb rpcb_map;
    #     rp__list rpcb_next<1>;
    # };
    def __init__(self, rpcb_map=None, rpcb_next=None):
        self.rpcb_map = rpcb_map
        self.rpcb_next = rpcb_next

    def __getattr__(self, attr):
        return getattr(self.rpcb_map, attr)

    def __repr__(self):
        out = []
        if self.rpcb_map is not None:
            out += ['rpcb_map=%s' % repr(self.rpcb_map)]
        if self.rpcb_next is not None:
            out += ['rpcb_next=%s' % repr(self.rpcb_next)]
        return 'rp__list(%s)' % ', '.join(out)
    __str__ = __repr__

class rpcb_rmtcallargs:
    # XDR definition:
    # struct rpcb_rmtcallargs {
    #     uint prog;
    #     uint vers;
    #     uint proc;
    #     opaque args<>;
    # };
    def __init__(self, prog=None, vers=None, proc=None, args=None):
        self.prog = prog
        self.vers = vers
        self.proc = proc
        self.args = args

    def __repr__(self):
        out = []
        if self.prog is not None:
            out += ['prog=%s' % repr(self.prog)]
        if self.vers is not None:
            out += ['vers=%s' % repr(self.vers)]
        if self.proc is not None:
            out += ['proc=%s' % repr(self.proc)]
        if self.args is not None:
            out += ['args=%s' % repr(self.args)]
        return 'rpcb_rmtcallargs(%s)' % ', '.join(out)
    __str__ = __repr__

class rpcb_rmtcallres:
    # XDR definition:
    # struct rpcb_rmtcallres {
    #     string addr<>;
    #     opaque results<>;
    # };
    def __init__(self, addr=None, results=None):
        self.addr = addr
        self.results = results

    def __repr__(self):
        out = []
        if self.addr is not None:
            out += ['addr=%s' % repr(self.addr)]
        if self.results is not None:
            out += ['results=%s' % repr(self.results)]
        return 'rpcb_rmtcallres(%s)' % ', '.join(out)
    __str__ = __repr__

class rpcb_entry:
    # XDR definition:
    # struct rpcb_entry {
    #     string r_maddr<>;
    #     string r_nc_netid<>;
    #     uint r_nc_semantics;
    #     string r_nc_protofmly<>;
    #     string r_nc_proto<>;
    # };
    def __init__(self, r_maddr=None, r_nc_netid=None, r_nc_semantics=None, r_nc_protofmly=None, r_nc_proto=None):
        self.r_maddr = r_maddr
        self.r_nc_netid = r_nc_netid
        self.r_nc_semantics = r_nc_semantics
        self.r_nc_protofmly = r_nc_protofmly
        self.r_nc_proto = r_nc_proto

    def __repr__(self):
        out = []
        if self.r_maddr is not None:
            out += ['r_maddr=%s' % repr(self.r_maddr)]
        if self.r_nc_netid is not None:
            out += ['r_nc_netid=%s' % repr(self.r_nc_netid)]
        if self.r_nc_semantics is not None:
            out += ['r_nc_semantics=%s' % repr(self.r_nc_semantics)]
        if self.r_nc_protofmly is not None:
            out += ['r_nc_protofmly=%s' % repr(self.r_nc_protofmly)]
        if self.r_nc_proto is not None:
            out += ['r_nc_proto=%s' % repr(self.r_nc_proto)]
        return 'rpcb_entry(%s)' % ', '.join(out)
    __str__ = __repr__

class rpcb_entry_list:
    # XDR definition:
    # struct rpcb_entry_list {
    #     rpcb_entry rpcb_entry_map;
    #     rpcb_entry_list rpcb_entry_next<1>;
    # };
    def __init__(self, rpcb_entry_map=None, rpcb_entry_next=None):
        self.rpcb_entry_map = rpcb_entry_map
        self.rpcb_entry_next = rpcb_entry_next

    def __getattr__(self, attr):
        return getattr(self.rpcb_entry_map, attr)

    def __repr__(self):
        out = []
        if self.rpcb_entry_map is not None:
            out += ['rpcb_entry_map=%s' % repr(self.rpcb_entry_map)]
        if self.rpcb_entry_next is not None:
            out += ['rpcb_entry_next=%s' % repr(self.rpcb_entry_next)]
        return 'rpcb_entry_list(%s)' % ', '.join(out)
    __str__ = __repr__

class rpcbs_addrlist:
    # XDR definition:
    # struct rpcbs_addrlist {
    #     uint prog;
    #     uint vers;
    #     int success;
    #     int failure;
    #     string netid<>;
    #     rpcbs_addrlist next<1>;
    # };
    def __init__(self, prog=None, vers=None, success=None, failure=None, netid=None, next=None):
        self.prog = prog
        self.vers = vers
        self.success = success
        self.failure = failure
        self.netid = netid
        self.next = next

    def __repr__(self):
        out = []
        if self.prog is not None:
            out += ['prog=%s' % repr(self.prog)]
        if self.vers is not None:
            out += ['vers=%s' % repr(self.vers)]
        if self.success is not None:
            out += ['success=%s' % repr(self.success)]
        if self.failure is not None:
            out += ['failure=%s' % repr(self.failure)]
        if self.netid is not None:
            out += ['netid=%s' % repr(self.netid)]
        if self.next is not None:
            out += ['next=%s' % repr(self.next)]
        return 'rpcbs_addrlist(%s)' % ', '.join(out)
    __str__ = __repr__

class rpcbs_rmtcalllist:
    # XDR definition:
    # struct rpcbs_rmtcalllist {
    #     uint prog;
    #     uint vers;
    #     uint proc;
    #     int success;
    #     int failure;
    #     int indirect;
    #     string netid<>;
    #     rpcbs_rmtcalllist next<1>;
    # };
    def __init__(self, prog=None, vers=None, proc=None, success=None, failure=None, indirect=None, netid=None, next=None):
        self.prog = prog
        self.vers = vers
        self.proc = proc
        self.success = success
        self.failure = failure
        self.indirect = indirect
        self.netid = netid
        self.next = next

    def __repr__(self):
        out = []
        if self.prog is not None:
            out += ['prog=%s' % repr(self.prog)]
        if self.vers is not None:
            out += ['vers=%s' % repr(self.vers)]
        if self.proc is not None:
            out += ['proc=%s' % repr(self.proc)]
        if self.success is not None:
            out += ['success=%s' % repr(self.success)]
        if self.failure is not None:
            out += ['failure=%s' % repr(self.failure)]
        if self.indirect is not None:
            out += ['indirect=%s' % repr(self.indirect)]
        if self.netid is not None:
            out += ['netid=%s' % repr(self.netid)]
        if self.next is not None:
            out += ['next=%s' % repr(self.next)]
        return 'rpcbs_rmtcalllist(%s)' % ', '.join(out)
    __str__ = __repr__

class rpcb_stat:
    # XDR definition:
    # struct rpcb_stat {
    #     rpcbs_proc info;
    #     int setinfo;
    #     int unsetinfo;
    #     rpcbs_addrlist_ptr addrinfo;
    #     rpcbs_rmtcalllist_ptr rmtinfo;
    # };
    def __init__(self, info=None, setinfo=None, unsetinfo=None, addrinfo=None, rmtinfo=None):
        self.info = info
        self.setinfo = setinfo
        self.unsetinfo = unsetinfo
        self.addrinfo = addrinfo
        self.rmtinfo = rmtinfo

    def __repr__(self):
        out = []
        if self.info is not None:
            out += ['info=%s' % repr(self.info)]
        if self.setinfo is not None:
            out += ['setinfo=%s' % repr(self.setinfo)]
        if self.unsetinfo is not None:
            out += ['unsetinfo=%s' % repr(self.unsetinfo)]
        if self.addrinfo is not None:
            out += ['addrinfo=%s' % repr(self.addrinfo)]
        if self.rmtinfo is not None:
            out += ['rmtinfo=%s' % repr(self.rmtinfo)]
        return 'rpcb_stat(%s)' % ', '.join(out)
    __str__ = __repr__

class netbuf:
    # XDR definition:
    # struct netbuf {
    #     uint maxlen;
    #     opaque buf<>;
    # };
    def __init__(self, maxlen=None, buf=None):
        self.maxlen = maxlen
        self.buf = buf

    def __repr__(self):
        out = []
        if self.maxlen is not None:
            out += ['maxlen=%s' % repr(self.maxlen)]
        if self.buf is not None:
            out += ['buf=%s' % repr(self.buf)]
        return 'netbuf(%s)' % ', '.join(out)
    __str__ = __repr__

