# Generated by rpcgen.py from rpcb.x on Wed Jun 24 11:38:48 2026
import rpcb_const as const
import rpcb_type as types
import xdrlib
from xdrlib import Error as XDRError

class nullclass(object):
    pass

def _str2bytes(data):
    # Python 3: xdrlib requires bytes for opaque/string fields.  Python 2 str
    # values were raw bytes, so latin-1 reproduces those byte values exactly
    # (and is identical to ASCII/utf-8 for plain text).
    if isinstance(data, str):
        return data.encode('latin-1')
    return data

class RPCBPacker(xdrlib.Packer):
    def __init__(self, check_enum=True, check_array=True):
        xdrlib.Packer.__init__(self)
        self.check_enum = check_enum
        self.check_array = check_array

    pack_int = xdrlib.Packer.pack_int
    pack_long = xdrlib.Packer.pack_int
    pack_uint = xdrlib.Packer.pack_uint
    pack_unsigned = xdrlib.Packer.pack_uint
    pack_hyper = xdrlib.Packer.pack_hyper
    pack_uhyper = xdrlib.Packer.pack_uhyper
    pack_float = xdrlib.Packer.pack_float
    pack_double = xdrlib.Packer.pack_double
    pack_quadruple = xdrlib.Packer.pack_double
    pack_bool = xdrlib.Packer.pack_bool
    def pack_opaque(self, data):
        return xdrlib.Packer.pack_opaque(self, _str2bytes(data))
    def pack_string(self, data):
        return xdrlib.Packer.pack_string(self, _str2bytes(data))
    def pack_fopaque(self, n, data):
        return xdrlib.Packer.pack_fopaque(self, n, _str2bytes(data))
    def pack_fstring(self, n, data):
        return xdrlib.Packer.pack_fstring(self, n, _str2bytes(data))
    def pack_mapping(self, data):
        if hasattr(self, 'filter_mapping'):
            data = getattr(self, 'filter_mapping')(data)
        if data.prog is None:
            raise TypeError('data.prog == None')
        self.pack_uint(data.prog)
        if data.vers is None:
            raise TypeError('data.vers == None')
        self.pack_uint(data.vers)
        if data.prot is None:
            raise TypeError('data.prot == None')
        self.pack_uint(data.prot)
        if data.port is None:
            raise TypeError('data.port == None')
        self.pack_uint(data.port)

    def pack_pmaplist(self, data):
        if hasattr(self, 'filter_pmaplist'):
            data = getattr(self, 'filter_pmaplist')(data)
        if data.map is None:
            raise TypeError('data.map == None')
        self.pack_mapping(data.map)
        if data.next is None:
            raise TypeError('data.next == None')
        if len(data.next) > 1 and self.check_array:
            raise XDRError('array length too long for data.next')
        self.pack_array(data.next, self.pack_pmaplist)

    def pack_call_args(self, data):
        if hasattr(self, 'filter_call_args'):
            data = getattr(self, 'filter_call_args')(data)
        if data.prog is None:
            raise TypeError('data.prog == None')
        self.pack_uint(data.prog)
        if data.vers is None:
            raise TypeError('data.vers == None')
        self.pack_uint(data.vers)
        if data.proc is None:
            raise TypeError('data.proc == None')
        self.pack_uint(data.proc)
        if data.args is None:
            raise TypeError('data.args == None')
        self.pack_opaque(data.args)

    def pack_call_result(self, data):
        if hasattr(self, 'filter_call_result'):
            data = getattr(self, 'filter_call_result')(data)
        if data.port is None:
            raise TypeError('data.port == None')
        self.pack_uint(data.port)
        if data.res is None:
            raise TypeError('data.res == None')
        self.pack_opaque(data.res)

    def pack_rpcb(self, data):
        if hasattr(self, 'filter_rpcb'):
            data = getattr(self, 'filter_rpcb')(data)
        if data.r_prog is None:
            raise TypeError('data.r_prog == None')
        self.pack_uint(data.r_prog)
        if data.r_vers is None:
            raise TypeError('data.r_vers == None')
        self.pack_uint(data.r_vers)
        if data.r_netid is None:
            raise TypeError('data.r_netid == None')
        self.pack_string(data.r_netid)
        if data.r_addr is None:
            raise TypeError('data.r_addr == None')
        self.pack_string(data.r_addr)
        if data.r_owner is None:
            raise TypeError('data.r_owner == None')
        self.pack_string(data.r_owner)

    def pack_rp__list(self, data):
        if hasattr(self, 'filter_rp__list'):
            data = getattr(self, 'filter_rp__list')(data)
        if data.rpcb_map is None:
            raise TypeError('data.rpcb_map == None')
        self.pack_rpcb(data.rpcb_map)
        if data.rpcb_next is None:
            raise TypeError('data.rpcb_next == None')
        if len(data.rpcb_next) > 1 and self.check_array:
            raise XDRError('array length too long for data.rpcb_next')
        self.pack_array(data.rpcb_next, self.pack_rp__list)

    def pack_rpcblist_ptr(self, data):
        if hasattr(self, 'filter_rpcblist_ptr'):
            data = getattr(self, 'filter_rpcblist_ptr')(data)
        if len(data) > 1 and self.check_array:
            raise XDRError('array length too long for data')
        self.pack_array(data, self.pack_rp__list)

    def pack_rpcb_rmtcallargs(self, data):
        if hasattr(self, 'filter_rpcb_rmtcallargs'):
            data = getattr(self, 'filter_rpcb_rmtcallargs')(data)
        if data.prog is None:
            raise TypeError('data.prog == None')
        self.pack_uint(data.prog)
        if data.vers is None:
            raise TypeError('data.vers == None')
        self.pack_uint(data.vers)
        if data.proc is None:
            raise TypeError('data.proc == None')
        self.pack_uint(data.proc)
        if data.args is None:
            raise TypeError('data.args == None')
        self.pack_opaque(data.args)

    def pack_rpcb_rmtcallres(self, data):
        if hasattr(self, 'filter_rpcb_rmtcallres'):
            data = getattr(self, 'filter_rpcb_rmtcallres')(data)
        if data.addr is None:
            raise TypeError('data.addr == None')
        self.pack_string(data.addr)
        if data.results is None:
            raise TypeError('data.results == None')
        self.pack_opaque(data.results)

    def pack_rpcb_entry(self, data):
        if hasattr(self, 'filter_rpcb_entry'):
            data = getattr(self, 'filter_rpcb_entry')(data)
        if data.r_maddr is None:
            raise TypeError('data.r_maddr == None')
        self.pack_string(data.r_maddr)
        if data.r_nc_netid is None:
            raise TypeError('data.r_nc_netid == None')
        self.pack_string(data.r_nc_netid)
        if data.r_nc_semantics is None:
            raise TypeError('data.r_nc_semantics == None')
        self.pack_uint(data.r_nc_semantics)
        if data.r_nc_protofmly is None:
            raise TypeError('data.r_nc_protofmly == None')
        self.pack_string(data.r_nc_protofmly)
        if data.r_nc_proto is None:
            raise TypeError('data.r_nc_proto == None')
        self.pack_string(data.r_nc_proto)

    def pack_rpcb_entry_list(self, data):
        if hasattr(self, 'filter_rpcb_entry_list'):
            data = getattr(self, 'filter_rpcb_entry_list')(data)
        if data.rpcb_entry_map is None:
            raise TypeError('data.rpcb_entry_map == None')
        self.pack_rpcb_entry(data.rpcb_entry_map)
        if data.rpcb_entry_next is None:
            raise TypeError('data.rpcb_entry_next == None')
        if len(data.rpcb_entry_next) > 1 and self.check_array:
            raise XDRError('array length too long for data.rpcb_entry_next')
        self.pack_array(data.rpcb_entry_next, self.pack_rpcb_entry_list)

    def pack_rpcb_entry_list_ptr(self, data):
        if hasattr(self, 'filter_rpcb_entry_list_ptr'):
            data = getattr(self, 'filter_rpcb_entry_list_ptr')(data)
        if len(data) > 1 and self.check_array:
            raise XDRError('array length too long for data')
        self.pack_array(data, self.pack_rpcb_entry_list)

    def pack_rpcbs_addrlist(self, data):
        if hasattr(self, 'filter_rpcbs_addrlist'):
            data = getattr(self, 'filter_rpcbs_addrlist')(data)
        if data.prog is None:
            raise TypeError('data.prog == None')
        self.pack_uint(data.prog)
        if data.vers is None:
            raise TypeError('data.vers == None')
        self.pack_uint(data.vers)
        if data.success is None:
            raise TypeError('data.success == None')
        self.pack_int(data.success)
        if data.failure is None:
            raise TypeError('data.failure == None')
        self.pack_int(data.failure)
        if data.netid is None:
            raise TypeError('data.netid == None')
        self.pack_string(data.netid)
        if data.next is None:
            raise TypeError('data.next == None')
        if len(data.next) > 1 and self.check_array:
            raise XDRError('array length too long for data.next')
        self.pack_array(data.next, self.pack_rpcbs_addrlist)

    def pack_rpcbs_rmtcalllist(self, data):
        if hasattr(self, 'filter_rpcbs_rmtcalllist'):
            data = getattr(self, 'filter_rpcbs_rmtcalllist')(data)
        if data.prog is None:
            raise TypeError('data.prog == None')
        self.pack_uint(data.prog)
        if data.vers is None:
            raise TypeError('data.vers == None')
        self.pack_uint(data.vers)
        if data.proc is None:
            raise TypeError('data.proc == None')
        self.pack_uint(data.proc)
        if data.success is None:
            raise TypeError('data.success == None')
        self.pack_int(data.success)
        if data.failure is None:
            raise TypeError('data.failure == None')
        self.pack_int(data.failure)
        if data.indirect is None:
            raise TypeError('data.indirect == None')
        self.pack_int(data.indirect)
        if data.netid is None:
            raise TypeError('data.netid == None')
        self.pack_string(data.netid)
        if data.next is None:
            raise TypeError('data.next == None')
        if len(data.next) > 1 and self.check_array:
            raise XDRError('array length too long for data.next')
        self.pack_array(data.next, self.pack_rpcbs_rmtcalllist)

    def pack_rpcbs_proc(self, data):
        if hasattr(self, 'filter_rpcbs_proc'):
            data = getattr(self, 'filter_rpcbs_proc')(data)
        self.pack_farray(const.RPCBSTAT_HIGHPROC, data, self.pack_int)

    def pack_rpcbs_addrlist_ptr(self, data):
        if hasattr(self, 'filter_rpcbs_addrlist_ptr'):
            data = getattr(self, 'filter_rpcbs_addrlist_ptr')(data)
        if len(data) > 1 and self.check_array:
            raise XDRError('array length too long for data')
        self.pack_array(data, self.pack_rpcbs_addrlist)

    def pack_rpcbs_rmtcalllist_ptr(self, data):
        if hasattr(self, 'filter_rpcbs_rmtcalllist_ptr'):
            data = getattr(self, 'filter_rpcbs_rmtcalllist_ptr')(data)
        if len(data) > 1 and self.check_array:
            raise XDRError('array length too long for data')
        self.pack_array(data, self.pack_rpcbs_rmtcalllist)

    def pack_rpcb_stat(self, data):
        if hasattr(self, 'filter_rpcb_stat'):
            data = getattr(self, 'filter_rpcb_stat')(data)
        if data.info is None:
            raise TypeError('data.info == None')
        self.pack_rpcbs_proc(data.info)
        if data.setinfo is None:
            raise TypeError('data.setinfo == None')
        self.pack_int(data.setinfo)
        if data.unsetinfo is None:
            raise TypeError('data.unsetinfo == None')
        self.pack_int(data.unsetinfo)
        if data.addrinfo is None:
            raise TypeError('data.addrinfo == None')
        self.pack_rpcbs_addrlist_ptr(data.addrinfo)
        if data.rmtinfo is None:
            raise TypeError('data.rmtinfo == None')
        self.pack_rpcbs_rmtcalllist_ptr(data.rmtinfo)

    def pack_rpcb_stat_byvers(self, data):
        if hasattr(self, 'filter_rpcb_stat_byvers'):
            data = getattr(self, 'filter_rpcb_stat_byvers')(data)
        self.pack_farray(const.RPCBVERS_STAT, data, self.pack_rpcb_stat)

    def pack_netbuf(self, data):
        if hasattr(self, 'filter_netbuf'):
            data = getattr(self, 'filter_netbuf')(data)
        if data.maxlen is None:
            raise TypeError('data.maxlen == None')
        self.pack_uint(data.maxlen)
        if data.buf is None:
            raise TypeError('data.buf == None')
        self.pack_opaque(data.buf)

    def pack_astring(self, data):
        if hasattr(self, 'filter_astring'):
            data = getattr(self, 'filter_astring')(data)
        self.pack_string(data)

class RPCBUnpacker(xdrlib.Unpacker):
    def __init__(self, data, check_enum=True, check_array=True):
        xdrlib.Unpacker.__init__(self, data)
        self.check_enum = check_enum
        self.check_array = check_array

    unpack_int = xdrlib.Unpacker.unpack_int
    unpack_long = xdrlib.Unpacker.unpack_int
    unpack_uint = xdrlib.Unpacker.unpack_uint
    unpack_unsigned = xdrlib.Unpacker.unpack_uint
    unpack_hyper = xdrlib.Unpacker.unpack_hyper
    unpack_uhyper = xdrlib.Unpacker.unpack_uhyper
    unpack_float = xdrlib.Unpacker.unpack_float
    unpack_double = xdrlib.Unpacker.unpack_double
    unpack_quadruple = xdrlib.Unpacker.unpack_double
    unpack_bool = xdrlib.Unpacker.unpack_bool
    unpack_opaque = xdrlib.Unpacker.unpack_opaque
    unpack_string = xdrlib.Unpacker.unpack_string
    def unpack_mapping(self):
        data = types.mapping()
        data.prog = self.unpack_uint()
        data.vers = self.unpack_uint()
        data.prot = self.unpack_uint()
        data.port = self.unpack_uint()
        if hasattr(self, 'filter_mapping'):
            data = getattr(self, 'filter_mapping')(data)
        return data

    def unpack_pmaplist(self):
        data = types.pmaplist()
        data.map = self.unpack_mapping()
        data.next = self.unpack_array(self.unpack_pmaplist)
        if len(data.next) > 1 and self.check_array:
            raise XDRError('array length too long for data.next')
        if hasattr(self, 'filter_pmaplist'):
            data = getattr(self, 'filter_pmaplist')(data)
        return data

    def unpack_call_args(self):
        data = types.call_args()
        data.prog = self.unpack_uint()
        data.vers = self.unpack_uint()
        data.proc = self.unpack_uint()
        data.args = self.unpack_opaque()
        if hasattr(self, 'filter_call_args'):
            data = getattr(self, 'filter_call_args')(data)
        return data

    def unpack_call_result(self):
        data = types.call_result()
        data.port = self.unpack_uint()
        data.res = self.unpack_opaque()
        if hasattr(self, 'filter_call_result'):
            data = getattr(self, 'filter_call_result')(data)
        return data

    def unpack_rpcb(self):
        data = types.rpcb()
        data.r_prog = self.unpack_uint()
        data.r_vers = self.unpack_uint()
        data.r_netid = self.unpack_string()
        data.r_addr = self.unpack_string()
        data.r_owner = self.unpack_string()
        if hasattr(self, 'filter_rpcb'):
            data = getattr(self, 'filter_rpcb')(data)
        return data

    def unpack_rp__list(self):
        data = types.rp__list()
        data.rpcb_map = self.unpack_rpcb()
        data.rpcb_next = self.unpack_array(self.unpack_rp__list)
        if len(data.rpcb_next) > 1 and self.check_array:
            raise XDRError('array length too long for data.rpcb_next')
        if hasattr(self, 'filter_rp__list'):
            data = getattr(self, 'filter_rp__list')(data)
        return data

    def unpack_rpcblist_ptr(self):
        data = self.unpack_array(self.unpack_rp__list)
        if len(data) > 1 and self.check_array:
            raise XDRError('array length too long for data')
        if hasattr(self, 'filter_rpcblist_ptr'):
            data = getattr(self, 'filter_rpcblist_ptr')(data)
        return data

    def unpack_rpcb_rmtcallargs(self):
        data = types.rpcb_rmtcallargs()
        data.prog = self.unpack_uint()
        data.vers = self.unpack_uint()
        data.proc = self.unpack_uint()
        data.args = self.unpack_opaque()
        if hasattr(self, 'filter_rpcb_rmtcallargs'):
            data = getattr(self, 'filter_rpcb_rmtcallargs')(data)
        return data

    def unpack_rpcb_rmtcallres(self):
        data = types.rpcb_rmtcallres()
        data.addr = self.unpack_string()
        data.results = self.unpack_opaque()
        if hasattr(self, 'filter_rpcb_rmtcallres'):
            data = getattr(self, 'filter_rpcb_rmtcallres')(data)
        return data

    def unpack_rpcb_entry(self):
        data = types.rpcb_entry()
        data.r_maddr = self.unpack_string()
        data.r_nc_netid = self.unpack_string()
        data.r_nc_semantics = self.unpack_uint()
        data.r_nc_protofmly = self.unpack_string()
        data.r_nc_proto = self.unpack_string()
        if hasattr(self, 'filter_rpcb_entry'):
            data = getattr(self, 'filter_rpcb_entry')(data)
        return data

    def unpack_rpcb_entry_list(self):
        data = types.rpcb_entry_list()
        data.rpcb_entry_map = self.unpack_rpcb_entry()
        data.rpcb_entry_next = self.unpack_array(self.unpack_rpcb_entry_list)
        if len(data.rpcb_entry_next) > 1 and self.check_array:
            raise XDRError('array length too long for data.rpcb_entry_next')
        if hasattr(self, 'filter_rpcb_entry_list'):
            data = getattr(self, 'filter_rpcb_entry_list')(data)
        return data

    def unpack_rpcb_entry_list_ptr(self):
        data = self.unpack_array(self.unpack_rpcb_entry_list)
        if len(data) > 1 and self.check_array:
            raise XDRError('array length too long for data')
        if hasattr(self, 'filter_rpcb_entry_list_ptr'):
            data = getattr(self, 'filter_rpcb_entry_list_ptr')(data)
        return data

    def unpack_rpcbs_addrlist(self):
        data = types.rpcbs_addrlist()
        data.prog = self.unpack_uint()
        data.vers = self.unpack_uint()
        data.success = self.unpack_int()
        data.failure = self.unpack_int()
        data.netid = self.unpack_string()
        data.next = self.unpack_array(self.unpack_rpcbs_addrlist)
        if len(data.next) > 1 and self.check_array:
            raise XDRError('array length too long for data.next')
        if hasattr(self, 'filter_rpcbs_addrlist'):
            data = getattr(self, 'filter_rpcbs_addrlist')(data)
        return data

    def unpack_rpcbs_rmtcalllist(self):
        data = types.rpcbs_rmtcalllist()
        data.prog = self.unpack_uint()
        data.vers = self.unpack_uint()
        data.proc = self.unpack_uint()
        data.success = self.unpack_int()
        data.failure = self.unpack_int()
        data.indirect = self.unpack_int()
        data.netid = self.unpack_string()
        data.next = self.unpack_array(self.unpack_rpcbs_rmtcalllist)
        if len(data.next) > 1 and self.check_array:
            raise XDRError('array length too long for data.next')
        if hasattr(self, 'filter_rpcbs_rmtcalllist'):
            data = getattr(self, 'filter_rpcbs_rmtcalllist')(data)
        return data

    def unpack_rpcbs_proc(self):
        data = self.unpack_farray(const.RPCBSTAT_HIGHPROC, self.unpack_int)
        if hasattr(self, 'filter_rpcbs_proc'):
            data = getattr(self, 'filter_rpcbs_proc')(data)
        return data

    def unpack_rpcbs_addrlist_ptr(self):
        data = self.unpack_array(self.unpack_rpcbs_addrlist)
        if len(data) > 1 and self.check_array:
            raise XDRError('array length too long for data')
        if hasattr(self, 'filter_rpcbs_addrlist_ptr'):
            data = getattr(self, 'filter_rpcbs_addrlist_ptr')(data)
        return data

    def unpack_rpcbs_rmtcalllist_ptr(self):
        data = self.unpack_array(self.unpack_rpcbs_rmtcalllist)
        if len(data) > 1 and self.check_array:
            raise XDRError('array length too long for data')
        if hasattr(self, 'filter_rpcbs_rmtcalllist_ptr'):
            data = getattr(self, 'filter_rpcbs_rmtcalllist_ptr')(data)
        return data

    def unpack_rpcb_stat(self):
        data = types.rpcb_stat()
        data.info = self.unpack_rpcbs_proc()
        data.setinfo = self.unpack_int()
        data.unsetinfo = self.unpack_int()
        data.addrinfo = self.unpack_rpcbs_addrlist_ptr()
        data.rmtinfo = self.unpack_rpcbs_rmtcalllist_ptr()
        if hasattr(self, 'filter_rpcb_stat'):
            data = getattr(self, 'filter_rpcb_stat')(data)
        return data

    def unpack_rpcb_stat_byvers(self):
        data = self.unpack_farray(const.RPCBVERS_STAT, self.unpack_rpcb_stat)
        if hasattr(self, 'filter_rpcb_stat_byvers'):
            data = getattr(self, 'filter_rpcb_stat_byvers')(data)
        return data

    def unpack_netbuf(self):
        data = types.netbuf()
        data.maxlen = self.unpack_uint()
        data.buf = self.unpack_opaque()
        if hasattr(self, 'filter_netbuf'):
            data = getattr(self, 'filter_netbuf')(data)
        return data

    def unpack_astring(self):
        data = self.unpack_string()
        if hasattr(self, 'filter_astring'):
            data = getattr(self, 'filter_astring')(data)
        return data

